# 06c — Extended Downstream Evaluation Adapted from Friend's Notebook

Fixed v3: **single-run notebook**.

The first big code cell only defines functions and configuration. It does **not** start evaluation.

Only the final cell starts:

```python
outputs = run_project_evaluation(...)
```

This version keeps your friend's two-framework design:

```text
FRAMEWORKS = ["tsai", "aeon"]
MODALITIES = ["acc", "bvp", "eda", "temp", "fused"]
```

and adapts it to:

```text
KoVAE: rollout_v1, posterior_bank_v2
TimeVAE: prior_v1
```

In [1]:
from pathlib import Path
import inspect
import itertools
import json
import random
import re
import warnings
import shutil

import joblib
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_recall_fscore_support,
    precision_score,
    recall_score,
)

# =========================
# MAIN RUN KNOBS
# =========================

RUN_REAL_TO_REAL_ONLY = False
USE_REAL_MODELS = True
FRAMEWORKS = ["tsai", "aeon"]

# =========================
# BASIC SETTINGS
# =========================

MODALITIES = ["acc", "bvp", "eda", "temp", "fused"]

EPOCHS_TSAI = 50
BATCH_SIZE = 1024
LR_TSAI = 1e-3
TSAI_ARCH = "InceptionTimePlus"

AEON_N_KERNELS = 5000
AEON_N_JOBS = 8

SEED = 42
SYN_TEST_N_SUBJECTS = 3

OUT_DIR = Path("tsai_aeon_results")
REAL_DIR = Path("processed_all_subjects_native_rates")
SYN_DIR = Path("synth_data")

OUT_DIR.mkdir(parents=True, exist_ok=True)

# =========================
# PATHS AND CONSTANTS
# =========================

REAL_X_ACC_PATH = REAL_DIR / "all_X_acc_32hz.npy"
REAL_X_BVP_PATH = REAL_DIR / "all_X_bvp_64hz.npy"
REAL_X_SLOW_PATH = REAL_DIR / "all_X_slow_4hz.npy"
REAL_Y_PATH = REAL_DIR / "all_y.npy"
REAL_SUBJECT_PATH = REAL_DIR / "all_subject.npy"

SYN_X_ACC_PATH = SYN_DIR / "generated_subjects_X_acc_32hz.npy"
SYN_X_BVP_PATH = SYN_DIR / "generated_subjects_X_bvp_64hz.npy"
SYN_X_SLOW_PATH = SYN_DIR / "generated_subjects_X_slow_4hz.npy"
SYN_Y_PATH = SYN_DIR / "generated_subjects_all_y.npy"
SYN_SUBJECT_PATH = SYN_DIR / "generated_subjects_all_subject.npy"

ACTIVITY_IDS = [1, 2, 3, 4, 5, 6, 7, 8]
LABEL_TO_INDEX = {label: i for i, label in enumerate(ACTIVITY_IDS)}
INDEX_TO_LABEL = {i: label for label, i in LABEL_TO_INDEX.items()}

TRAIN_SUBJECTS = ["S1", "S2", "S3", "S4", "S5", "S6", "S9", "S11", "S12", "S13"]
VAL_SUBJECTS = ["S14", "S15"]
TEST_SUBJECTS = ["S7", "S8", "S10"]

MODALITY_INFO = {
    "acc": {
        "real_path": REAL_X_ACC_PATH,
        "syn_path": SYN_X_ACC_PATH,
        "expected_shape_tail": (256, 3),
        "native_hz": 32,
        "channel_names": ["ACC_x", "ACC_y", "ACC_z"],
    },
    "bvp": {
        "real_path": REAL_X_BVP_PATH,
        "syn_path": SYN_X_BVP_PATH,
        "expected_shape_tail": (512, 1),
        "native_hz": 64,
        "channel_names": ["BVP"],
    },
    "slow": {
        "real_path": REAL_X_SLOW_PATH,
        "syn_path": SYN_X_SLOW_PATH,
        "expected_shape_tail": (32, 2),
        "native_hz": 4,
        "channel_names": ["EDA", "TEMP"],
    },
}

FUSED_MODALITY_NAME = "fused"
FUSED_TARGET_LEN = 512
FUSED_NATIVE_HZ = 64
FUSED_CHANNEL_NAMES = ["ACC_x", "ACC_y", "ACC_z", "BVP", "EDA", "TEMP"]

# =========================
# PROJECT ADAPTATION SETTINGS
# =========================

PROJECT_ROOT = Path("/home/iailab42/khans1/projects/ir")
PRETRAINED_RESULTS_DIR = PROJECT_ROOT / "models/downstream/pretrained/tsai_aeon_results"

CURRENT_MODEL_FAMILY = ""
CURRENT_SYNTHETIC_METHOD = ""
CURRENT_SYNTHETIC_METHOD_DISPLAY = ""

MODEL_FAMILY_CONFIGS = {
    "kovae": {
        "synthetic_base_dir": PROJECT_ROOT / "data/synthetic_subjects/kovae",
        "synthetic_methods": ["rollout_v1", "posterior_bank_v2"],
        "method_display_names": {
            "rollout_v1": "KoVAE-Rollout",
            "posterior_bank_v2": "KoVAE-Posterior",
        },
    },
    "timevae": {
        "synthetic_base_dir": PROJECT_ROOT / "data/synthetic_subjects/timevae",
        "synthetic_methods": ["prior_v1"],
        "method_display_names": {
            "prior_v1": "TimeVAE-Prior",
        },
    },
}

# aeon compatibility fix used only for temporary classifier arrays.
AEON_FIX_LOW_VARIATION = True
AEON_MIN_STD = 1e-6


# =========================
# HELPERS
# =========================

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)


def require_file(path):
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Missing file: {path}")
    return path


def subject_sort_key(s):
    s = str(s)
    if s.startswith("S") and s[1:].isdigit():
        return ("S", int(s[1:]))
    m = re.search(r"(\d+)$", s)
    if m is not None:
        return (s[:m.start(1)], int(m.group(1)))
    return (s, -1)


def labels_to_indices(y):
    y = np.asarray(y).astype(np.int64)
    out = np.zeros_like(y, dtype=np.int64)
    for i, lab in enumerate(y):
        lab = int(lab)
        if lab not in LABEL_TO_INDEX:
            raise ValueError(f"Unexpected label {lab}. Expected labels: {ACTIVITY_IDS}")
        out[i] = LABEL_TO_INDEX[lab]
    return out


def indices_to_labels(y_idx):
    y_idx = np.asarray(y_idx).astype(np.int64)
    return np.array([INDEX_TO_LABEL[int(i)] for i in y_idx], dtype=np.int64)


def to_channels_first(X_native):
    X_native = np.asarray(X_native, dtype=np.float32)
    if X_native.ndim != 3:
        raise ValueError(f"Expected [N,T,C], got {X_native.shape}")
    return np.transpose(X_native, (0, 2, 1)).astype(np.float32)


def resample_time_axis(X_native, target_len):
    X_native = np.asarray(X_native, dtype=np.float32)
    if X_native.ndim != 3:
        raise ValueError(f"Expected [N,T,C], got {X_native.shape}")

    n, old_len, channels = X_native.shape
    if old_len == target_len:
        return X_native.copy().astype(np.float32)
    if old_len < 2:
        raise ValueError(f"Cannot resample time axis with old_len={old_len}")

    old_positions = np.linspace(0.0, old_len - 1, int(target_len), dtype=np.float32)
    left = np.floor(old_positions).astype(np.int64)
    right = np.minimum(left + 1, old_len - 1)
    weight = (old_positions - left).astype(np.float32)

    out = ((1.0 - weight)[None, :, None] * X_native[:, left, :]
           + weight[None, :, None] * X_native[:, right, :])
    return out.astype(np.float32)


def split_slow_to_eda_temp(X_slow):
    X_slow = np.asarray(X_slow, dtype=np.float32)
    if X_slow.ndim != 3 or X_slow.shape[2] != 2:
        raise ValueError(f"Expected SLOW [N,32,2], got {X_slow.shape}")
    return X_slow[:, :, 0:1].astype(np.float32), X_slow[:, :, 1:2].astype(np.float32)


def build_fused_native_view(X_dict, target_len=FUSED_TARGET_LEN):
    X_acc = resample_time_axis(X_dict["acc"], target_len)
    X_bvp = resample_time_axis(X_dict["bvp"], target_len)
    X_eda = resample_time_axis(X_dict["eda"], target_len)
    X_temp = resample_time_axis(X_dict["temp"], target_len)

    lengths = {"acc": len(X_acc), "bvp": len(X_bvp), "eda": len(X_eda), "temp": len(X_temp)}
    if len(set(lengths.values())) != 1:
        raise ValueError(f"Fused view length mismatch: {lengths}")

    return np.concatenate([X_acc, X_bvp, X_eda, X_temp], axis=2).astype(np.float32)


def filter_valid_activities(X_dict, y, subjects):
    keep = np.isin(y, np.array(ACTIVITY_IDS, dtype=np.int64))
    return {k: v[keep] for k, v in X_dict.items()}, y[keep].astype(np.int64), subjects[keep].astype(str)


def filter_by_subjects(X_dict, y, subjects, selected_subjects):
    selected_subjects = set(str(s) for s in selected_subjects)
    keep = np.array([str(s) in selected_subjects for s in subjects], dtype=bool)
    return {k: v[keep] for k, v in X_dict.items()}, y[keep].astype(np.int64), subjects[keep].astype(str)


def sanitize_name(name):
    return str(name).replace(" ", "_").replace("/", "_").replace("\\", "_")



def configure_project_paths(project_root, model_family, synthetic_method, output_root=None, pretrained_results_dir=None):
    global PROJECT_ROOT, PRETRAINED_RESULTS_DIR
    global CURRENT_MODEL_FAMILY, CURRENT_SYNTHETIC_METHOD, CURRENT_SYNTHETIC_METHOD_DISPLAY
    global OUT_DIR, REAL_DIR, SYN_DIR
    global REAL_X_ACC_PATH, REAL_X_BVP_PATH, REAL_X_SLOW_PATH, REAL_Y_PATH, REAL_SUBJECT_PATH
    global SYN_X_ACC_PATH, SYN_X_BVP_PATH, SYN_X_SLOW_PATH, SYN_Y_PATH, SYN_SUBJECT_PATH
    global MODALITY_INFO

    PROJECT_ROOT = Path(project_root)

    if model_family not in MODEL_FAMILY_CONFIGS:
        raise ValueError(f"Unknown model_family={model_family}. Available: {list(MODEL_FAMILY_CONFIGS.keys())}")

    family_cfg = MODEL_FAMILY_CONFIGS[model_family]
    if synthetic_method not in family_cfg["synthetic_methods"]:
        raise ValueError(
            f"Unknown synthetic_method={synthetic_method} for {model_family}. "
            f"Available: {family_cfg['synthetic_methods']}"
        )

    CURRENT_MODEL_FAMILY = model_family
    CURRENT_SYNTHETIC_METHOD = synthetic_method
    CURRENT_SYNTHETIC_METHOD_DISPLAY = family_cfg["method_display_names"].get(synthetic_method, synthetic_method)

    REAL_DIR = PROJECT_ROOT / "data/processed/native_rates"
    SYN_DIR = family_cfg["synthetic_base_dir"] / synthetic_method

    if output_root is None:
        output_root = PROJECT_ROOT / "results/downstream_extended_tsai_aeon"
    else:
        output_root = Path(output_root)

    OUT_DIR = output_root / model_family / synthetic_method
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    if pretrained_results_dir is not None:
        PRETRAINED_RESULTS_DIR = Path(pretrained_results_dir)

    REAL_X_ACC_PATH = REAL_DIR / "all_X_acc_32hz.npy"
    REAL_X_BVP_PATH = REAL_DIR / "all_X_bvp_64hz.npy"
    REAL_X_SLOW_PATH = REAL_DIR / "all_X_slow_4hz.npy"
    REAL_Y_PATH = REAL_DIR / "all_y.npy"
    REAL_SUBJECT_PATH = REAL_DIR / "all_subject.npy"

    SYN_X_ACC_PATH = SYN_DIR / "generated_subjects_X_acc_32hz.npy"
    SYN_X_BVP_PATH = SYN_DIR / "generated_subjects_X_bvp_64hz.npy"
    SYN_X_SLOW_PATH = SYN_DIR / "generated_subjects_X_slow_4hz.npy"
    SYN_Y_PATH = SYN_DIR / "generated_subjects_all_y.npy"
    SYN_SUBJECT_PATH = SYN_DIR / "generated_subjects_all_subject.npy"

    MODALITY_INFO["acc"]["real_path"] = REAL_X_ACC_PATH
    MODALITY_INFO["acc"]["syn_path"] = SYN_X_ACC_PATH
    MODALITY_INFO["bvp"]["real_path"] = REAL_X_BVP_PATH
    MODALITY_INFO["bvp"]["syn_path"] = SYN_X_BVP_PATH
    MODALITY_INFO["slow"]["real_path"] = REAL_X_SLOW_PATH
    MODALITY_INFO["slow"]["syn_path"] = SYN_X_SLOW_PATH

    print("\nConfigured project paths")
    print("  PROJECT_ROOT:", PROJECT_ROOT)
    print("  model_family:", CURRENT_MODEL_FAMILY)
    print("  synthetic_method:", CURRENT_SYNTHETIC_METHOD)
    print("  synthetic_method_display:", CURRENT_SYNTHETIC_METHOD_DISPLAY)
    print("  REAL_DIR:", REAL_DIR)
    print("  SYN_DIR:", SYN_DIR)
    print("  OUT_DIR:", OUT_DIR)
    print("  PRETRAINED_RESULTS_DIR:", PRETRAINED_RESULTS_DIR)


def add_method_columns(df):
    df = df.copy()
    if len(df) == 0:
        return df

    for col, value, pos in [
        ("model_family", CURRENT_MODEL_FAMILY, 0),
        ("synthetic_method", CURRENT_SYNTHETIC_METHOD, 1),
        ("synthetic_method_display_name", CURRENT_SYNTHETIC_METHOD_DISPLAY, 2),
    ]:
        if col in df.columns:
            df[col] = value
        else:
            df.insert(min(pos, len(df.columns)), col, value)

    return df


def result_csv_candidates(framework):
    candidates = [result_csv_path(framework)]

    if PRETRAINED_RESULTS_DIR.exists():
        candidates.append(PRETRAINED_RESULTS_DIR / f"{framework}_native_downstream_results.csv")
        candidates.append(PRETRAINED_RESULTS_DIR / "all_framework_native_results.csv")
        candidates.extend(sorted(PRETRAINED_RESULTS_DIR.glob(f"**/{framework}_native_downstream_results.csv")))
        candidates.extend(sorted(PRETRAINED_RESULTS_DIR.glob("**/all_framework_native_results.csv")))

    unique = []
    seen = set()

    for p in candidates:
        p = Path(p)
        key = str(p.resolve()) if p.exists() else str(p)
        if key not in seen:
            unique.append(p)
            seen.add(key)

    return unique


def activity_csv_candidates(framework):
    candidates = [activity_csv_path(framework)]

    if PRETRAINED_RESULTS_DIR.exists():
        candidates.append(PRETRAINED_RESULTS_DIR / f"{framework}_native_per_activity_results.csv")
        candidates.append(PRETRAINED_RESULTS_DIR / "all_framework_native_per_activity_results.csv")
        candidates.extend(sorted(PRETRAINED_RESULTS_DIR.glob(f"**/{framework}_native_per_activity_results.csv")))
        candidates.extend(sorted(PRETRAINED_RESULTS_DIR.glob("**/all_framework_native_per_activity_results.csv")))

    unique = []
    seen = set()

    for p in candidates:
        p = Path(p)
        key = str(p.resolve()) if p.exists() else str(p)
        if key not in seen:
            unique.append(p)
            seen.add(key)

    return unique


def copy_external_tsai_model_if_needed(model_file):
    model_file = Path(model_file)
    local_dir = OUT_DIR / "tsai_saved_models"
    local_dir.mkdir(parents=True, exist_ok=True)

    local_file = local_dir / model_file.name

    if model_file.exists() and model_file.resolve() != local_file.resolve():
        shutil.copy2(model_file, local_file)
        print("Copied external tsai model into current output folder:", local_file)
        return local_file

    return model_file


def keep_nonflat_cases_for_aeon(X, y, min_std=1e-6, label=""):
    X = np.asarray(X, dtype=np.float32)
    y = np.asarray(y, dtype=np.int64)

    if X.ndim != 3:
        raise ValueError(f"Expected aeon input [N,C,T], got {X.shape}")

    std = X.std(axis=2)
    keep_mask = np.all(std > float(min_std), axis=1)
    dropped = int((~keep_mask).sum())

    if keep_mask.sum() == 0:
        raise ValueError(f"All windows were dropped by aeon low-variation filter for {label}")

    if dropped > 0:
        print(
            f"aeon low-variation filter {label}: "
            f"dropped {dropped}/{len(keep_mask)} windows with at least one channel std <= {min_std}"
        )

    return X[keep_mask], y[keep_mask], dropped


def safe_display(df, max_rows=20):
    try:
        display(df)
    except Exception:
        print(df.head(max_rows))

# =========================
# METRICS AND SAVING
# =========================

def compute_classification_metrics(y_true, y_pred):
    y_true = np.asarray(y_true, dtype=np.int64)
    y_pred = np.asarray(y_pred, dtype=np.int64)

    metrics = {
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "macro_precision": float(precision_score(y_true, y_pred, labels=ACTIVITY_IDS, average="macro", zero_division=0)),
        "macro_recall": float(recall_score(y_true, y_pred, labels=ACTIVITY_IDS, average="macro", zero_division=0)),
        "macro_f1": float(f1_score(y_true, y_pred, labels=ACTIVITY_IDS, average="macro", zero_division=0)),
        "weighted_precision": float(precision_score(y_true, y_pred, labels=ACTIVITY_IDS, average="weighted", zero_division=0)),
        "weighted_recall": float(recall_score(y_true, y_pred, labels=ACTIVITY_IDS, average="weighted", zero_division=0)),
        "weighted_f1": float(f1_score(y_true, y_pred, labels=ACTIVITY_IDS, average="weighted", zero_division=0)),
    }
    metrics["balanced_accuracy"] = metrics["macro_recall"]
    return metrics


def compute_per_activity_metrics(y_true, y_pred):
    y_true = np.asarray(y_true, dtype=np.int64)
    y_pred = np.asarray(y_pred, dtype=np.int64)
    precision, recall, f1, support = precision_recall_fscore_support(
        y_true, y_pred, labels=ACTIVITY_IDS, zero_division=0
    )

    rows = []
    for i, activity in enumerate(ACTIVITY_IDS):
        true_mask = y_true == activity
        correct = int(np.sum(true_mask & (y_pred == activity)))
        total = int(np.sum(true_mask))
        rows.append({
            "activity_label": int(activity),
            "precision": float(precision[i]),
            "recall": float(recall[i]),
            "f1": float(f1[i]),
            "support": int(support[i]),
            "correct_true_activity_windows": correct,
            "total_true_activity_windows": total,
            "true_activity_window_accuracy": float(correct / total) if total > 0 else np.nan,
        })
    return pd.DataFrame(rows)


def plot_confusion_matrix_image(cm, labels, title, out_path, normalize=False):
    cm_to_plot = cm.astype(np.float64)
    if normalize:
        row_sum = cm_to_plot.sum(axis=1, keepdims=True)
        cm_to_plot = np.divide(cm_to_plot, row_sum, out=np.zeros_like(cm_to_plot), where=row_sum != 0)

    fig, ax = plt.subplots(figsize=(8, 7))
    im = ax.imshow(cm_to_plot, cmap="Blues")
    ax.figure.colorbar(im, ax=ax)
    ax.set_title(title)
    ax.set_xlabel("Predicted activity")
    ax.set_ylabel("True activity")
    ax.set_xticks(np.arange(len(labels)))
    ax.set_yticks(np.arange(len(labels)))
    ax.set_xticklabels(labels)
    ax.set_yticklabels(labels)

    threshold = cm_to_plot.max() / 2.0 if cm_to_plot.size and cm_to_plot.max() > 0 else 0.0
    for i in range(cm_to_plot.shape[0]):
        for j in range(cm_to_plot.shape[1]):
            text = f"{cm_to_plot[i, j]:.2f}" if normalize else str(int(cm[i, j]))
            ax.text(j, i, text, ha="center", va="center", color="white" if cm_to_plot[i, j] > threshold else "black")

    fig.tight_layout()
    fig.savefig(out_path, dpi=200, bbox_inches="tight")
    plt.close(fig)


def save_predictions_cm_and_activity_report(framework, model, experiment, modality, native_hz, channels, y_true, y_pred):
    safe_name = sanitize_name(f"{framework}_{experiment}_{modality}")
    y_true = np.asarray(y_true, dtype=np.int64)
    y_pred = np.asarray(y_pred, dtype=np.int64)

    pred_path = OUT_DIR / f"{safe_name}_predictions.csv"
    pd.DataFrame({"y_true": y_true, "y_pred": y_pred, "correct": y_true == y_pred}).to_csv(pred_path, index=False)

    cm = confusion_matrix(y_true, y_pred, labels=ACTIVITY_IDS)
    cm_df = pd.DataFrame(cm, index=[f"true_{a}" for a in ACTIVITY_IDS], columns=[f"pred_{a}" for a in ACTIVITY_IDS])
    cm_csv_path = OUT_DIR / f"{safe_name}_confusion_matrix.csv"
    cm_df.to_csv(cm_csv_path)

    cm_count_png = OUT_DIR / f"{safe_name}_confusion_matrix_counts.png"
    cm_norm_png = OUT_DIR / f"{safe_name}_confusion_matrix_normalized.png"
    plot_confusion_matrix_image(cm, ACTIVITY_IDS, f"{framework} {experiment} {modality} confusion matrix", cm_count_png, normalize=False)
    plot_confusion_matrix_image(cm, ACTIVITY_IDS, f"{framework} {experiment} {modality} normalized confusion matrix", cm_norm_png, normalize=True)

    activity_df = compute_per_activity_metrics(y_true, y_pred)
    activity_df.insert(0, "framework", framework)
    activity_df.insert(1, "model", model)
    activity_df.insert(2, "experiment", experiment)
    activity_df.insert(3, "native_modality", modality)
    activity_df.insert(4, "native_hz", native_hz)
    activity_df.insert(5, "channels", ",".join(channels))

    activity_path = OUT_DIR / f"{safe_name}_per_activity_metrics.csv"
    activity_df.to_csv(activity_path, index=False)

    print("Saved:", pred_path)
    print("Saved:", cm_csv_path)
    print("Saved:", cm_count_png)
    print("Saved:", cm_norm_png)
    print("Saved:", activity_path)
    return activity_df

# =========================
# DATASET VIEWS
# =========================

def load_native_data(load_synthetic):
    require_file(REAL_Y_PATH)
    require_file(REAL_SUBJECT_PATH)

    real_y = np.load(REAL_Y_PATH).astype(np.int64)
    real_subjects = np.load(REAL_SUBJECT_PATH, allow_pickle=True).astype(str)
    if len(real_y) != len(real_subjects):
        raise ValueError(f"Real y/subject mismatch: {len(real_y)} vs {len(real_subjects)}")

    real_X = {}
    for modality_name, info in MODALITY_INFO.items():
        require_file(info["real_path"])
        Xr = np.load(info["real_path"]).astype(np.float32)
        if Xr.ndim != 3 or Xr.shape[1:] != info["expected_shape_tail"]:
            raise ValueError(f"Real {modality_name}: expected [N,{info['expected_shape_tail']}], got {Xr.shape}")
        if len(Xr) != len(real_y):
            raise ValueError(f"Real {modality_name}/y mismatch: {len(Xr)} vs {len(real_y)}")
        real_X[modality_name] = Xr

    real_X, real_y, real_subjects = filter_valid_activities(real_X, real_y, real_subjects)
    print("\nLoaded real data:")
    print("  y:", real_y.shape)
    print("  subjects:", real_subjects.shape)
    for k, v in real_X.items():
        print(f"  {k}: {v.shape}")

    if not load_synthetic:
        print("\nSynthetic data skipped because RUN_REAL_TO_REAL_ONLY=True.")
        return real_X, real_y, real_subjects, None, None, None

    require_file(SYN_Y_PATH)
    require_file(SYN_SUBJECT_PATH)
    syn_y = np.load(SYN_Y_PATH).astype(np.int64)
    syn_subjects = np.load(SYN_SUBJECT_PATH, allow_pickle=True).astype(str)
    if len(syn_y) != len(syn_subjects):
        raise ValueError(f"Synthetic y/subject mismatch: {len(syn_y)} vs {len(syn_subjects)}")

    syn_X = {}
    for modality_name, info in MODALITY_INFO.items():
        require_file(info["syn_path"])
        Xs = np.load(info["syn_path"]).astype(np.float32)
        if Xs.ndim != 3 or Xs.shape[1:] != info["expected_shape_tail"]:
            raise ValueError(f"Synthetic {modality_name}: expected [N,{info['expected_shape_tail']}], got {Xs.shape}")
        if len(Xs) != len(syn_y):
            raise ValueError(f"Synthetic {modality_name}/y mismatch: {len(Xs)} vs {len(syn_y)}")
        syn_X[modality_name] = Xs

    syn_X, syn_y, syn_subjects = filter_valid_activities(syn_X, syn_y, syn_subjects)
    print("\nLoaded synthetic data:")
    print("  y:", syn_y.shape)
    print("  subjects:", syn_subjects.shape)
    for k, v in syn_X.items():
        print(f"  {k}: {v.shape}")

    return real_X, real_y, real_subjects, syn_X, syn_y, syn_subjects


def validate_fixed_split(real_subjects):
    available = sorted(np.unique(real_subjects.astype(str)), key=subject_sort_key)
    missing_train = sorted(set(TRAIN_SUBJECTS) - set(available), key=subject_sort_key)
    missing_val = sorted(set(VAL_SUBJECTS) - set(available), key=subject_sort_key)
    missing_test = sorted(set(TEST_SUBJECTS) - set(available), key=subject_sort_key)

    if missing_train or missing_val or missing_test:
        raise ValueError(
            "Fixed split subjects missing from real data.\n"
            f"Missing train: {missing_train}\nMissing val: {missing_val}\nMissing test: {missing_test}\nAvailable: {available}"
        )
    if set(TRAIN_SUBJECTS) & set(VAL_SUBJECTS) or set(TRAIN_SUBJECTS) & set(TEST_SUBJECTS) or set(VAL_SUBJECTS) & set(TEST_SUBJECTS):
        raise ValueError("Train/val/test subject split overlaps.")

    print("\nFixed split OK:")
    print("  Train:", TRAIN_SUBJECTS)
    print("  Val:  ", VAL_SUBJECTS)
    print("  Test: ", TEST_SUBJECTS)


def make_native_dataset_views(real_X_all, real_y_all, real_subjects_all, syn_X_all=None, syn_y_all=None, syn_subjects_all=None):
    validate_fixed_split(real_subjects_all)
    use_synthetic = syn_X_all is not None and syn_y_all is not None and syn_subjects_all is not None

    real_train_X, real_train_y, _ = filter_by_subjects(real_X_all, real_y_all, real_subjects_all, TRAIN_SUBJECTS)
    real_val_X, real_val_y, _ = filter_by_subjects(real_X_all, real_y_all, real_subjects_all, VAL_SUBJECTS)
    real_test_X, real_test_y, _ = filter_by_subjects(real_X_all, real_y_all, real_subjects_all, TEST_SUBJECTS)

    syn_test_subjects = []
    syn_test_X = None
    syn_test_y = None
    if use_synthetic:
        unique_syn_subjects = sorted(np.unique(syn_subjects_all.astype(str)), key=subject_sort_key)
        if len(unique_syn_subjects) < SYN_TEST_N_SUBJECTS:
            raise ValueError(f"Need at least {SYN_TEST_N_SUBJECTS} synthetic subjects, found {len(unique_syn_subjects)}")
        syn_test_subjects = unique_syn_subjects[:SYN_TEST_N_SUBJECTS]
        syn_test_X, syn_test_y, _ = filter_by_subjects(syn_X_all, syn_y_all, syn_subjects_all, syn_test_subjects)
        print("\nSynthetic test subjects:", syn_test_subjects)

    real_train_eda, real_train_temp = split_slow_to_eda_temp(real_train_X["slow"])
    real_val_eda, real_val_temp = split_slow_to_eda_temp(real_val_X["slow"])
    real_test_eda, real_test_temp = split_slow_to_eda_temp(real_test_X["slow"])

    real_train_eval = {"acc": real_train_X["acc"], "bvp": real_train_X["bvp"], "eda": real_train_eda, "temp": real_train_temp}
    real_val_eval = {"acc": real_val_X["acc"], "bvp": real_val_X["bvp"], "eda": real_val_eda, "temp": real_val_temp}
    real_test_eval = {"acc": real_test_X["acc"], "bvp": real_test_X["bvp"], "eda": real_test_eda, "temp": real_test_temp}

    syn_eval = None
    syn_test_eval = None
    if use_synthetic:
        syn_eda, syn_temp = split_slow_to_eda_temp(syn_X_all["slow"])
        syn_test_eda, syn_test_temp = split_slow_to_eda_temp(syn_test_X["slow"])
        syn_eval = {"acc": syn_X_all["acc"], "bvp": syn_X_all["bvp"], "eda": syn_eda, "temp": syn_temp}
        syn_test_eval = {"acc": syn_test_X["acc"], "bvp": syn_test_X["bvp"], "eda": syn_test_eda, "temp": syn_test_temp}

    info = {
        "acc": {"native_hz": 32, "channels": ["ACC_x", "ACC_y", "ACC_z"], "description": "ACC only"},
        "bvp": {"native_hz": 64, "channels": ["BVP"], "description": "BVP only"},
        "eda": {"native_hz": 4, "channels": ["EDA"], "description": "EDA only"},
        "temp": {"native_hz": 4, "channels": ["TEMP"], "description": "TEMP only"},
    }

    views = {}
    for modality in ["acc", "bvp", "eda", "temp"]:
        item = {
            "real_train_X_native": real_train_eval[modality],
            "real_val_X_native": real_val_eval[modality],
            "real_test_X_native": real_test_eval[modality],
            "real_train_y": real_train_y,
            "real_val_y": real_val_y,
            "real_test_y": real_test_y,
            "native_hz": info[modality]["native_hz"],
            "channels": info[modality]["channels"],
            "description": info[modality]["description"],
        }
        if use_synthetic:
            item.update({
                "syn_X_native": syn_eval[modality],
                "syn_test_X_native": syn_test_eval[modality],
                "syn_y": syn_y_all,
                "syn_test_y": syn_test_y,
                "syn_test_subjects": syn_test_subjects,
            })
        views[modality] = item

    fused_item = {
        "real_train_X_native": build_fused_native_view(real_train_eval),
        "real_val_X_native": build_fused_native_view(real_val_eval),
        "real_test_X_native": build_fused_native_view(real_test_eval),
        "real_train_y": real_train_y,
        "real_val_y": real_val_y,
        "real_test_y": real_test_y,
        "native_hz": FUSED_NATIVE_HZ,
        "channels": FUSED_CHANNEL_NAMES,
        "description": "ACC+BVP+EDA+TEMP fused",
    }
    if use_synthetic:
        fused_item.update({
            "syn_X_native": build_fused_native_view(syn_eval),
            "syn_test_X_native": build_fused_native_view(syn_test_eval),
            "syn_y": syn_y_all,
            "syn_test_y": syn_test_y,
            "syn_test_subjects": syn_test_subjects,
        })
    views[FUSED_MODALITY_NAME] = fused_item

    for name, view in views.items():
        msg = f"  View {name:6s}: train={view['real_train_X_native'].shape}, val={view['real_val_X_native'].shape}, test={view['real_test_X_native'].shape}"
        if use_synthetic:
            msg += f", syn_all={view['syn_X_native'].shape}, syn_test3={view['syn_test_X_native'].shape}"
        print(msg)

    return views


def save_shape_report(views):
    rows = []
    for name, view in views.items():
        row = {
            "native_view": name,
            "native_hz": view["native_hz"],
            "channels": ",".join(view["channels"]),
            "native_real_train_shape_N_T_C": list(view["real_train_X_native"].shape),
            "native_real_val_shape_N_T_C": list(view["real_val_X_native"].shape),
            "native_real_test_shape_N_T_C": list(view["real_test_X_native"].shape),
            "framework_real_train_shape_N_C_T": list(to_channels_first(view["real_train_X_native"]).shape),
            "framework_real_val_shape_N_C_T": list(to_channels_first(view["real_val_X_native"]).shape),
            "framework_real_test_shape_N_C_T": list(to_channels_first(view["real_test_X_native"]).shape),
        }
        if "syn_X_native" in view:
            row.update({
                "native_syn_all_shape_N_T_C": list(view["syn_X_native"].shape),
                "native_syn_test3_shape_N_T_C": list(view["syn_test_X_native"].shape),
                "syn_test_subjects": ",".join(view.get("syn_test_subjects", [])),
                "framework_syn_all_shape_N_C_T": list(to_channels_first(view["syn_X_native"]).shape),
                "framework_syn_test3_shape_N_C_T": list(to_channels_first(view["syn_test_X_native"]).shape),
            })
        rows.append(row)

    df = pd.DataFrame(rows)
    out_path = OUT_DIR / "native_input_shape_report.csv"
    df.to_csv(out_path, index=False)
    print("\nSaved shape report:", out_path)
    return df

# =========================
# EXPERIMENTS AND SAVED ROWS
# =========================

def get_experiments_for_view(view):
    real_to_real = {
        "name": "real_to_real",
        "train_X": view["real_train_X_native"],
        "train_y": view["real_train_y"],
        "val_X": view["real_val_X_native"],
        "val_y": view["real_val_y"],
        "test_X": view["real_test_X_native"],
        "test_y": view["real_test_y"],
    }

    if RUN_REAL_TO_REAL_ONLY:
        return [real_to_real]

    missing_syn_keys = [k for k in ["syn_X_native", "syn_test_X_native", "syn_y", "syn_test_y"] if k not in view]
    if missing_syn_keys:
        raise ValueError(f"Full evaluation needs synthetic data. Missing keys: {missing_syn_keys}")

    return [
        real_to_real,
        {
            "name": "real_to_synthetic",
            "train_X": view["real_train_X_native"],
            "train_y": view["real_train_y"],
            "val_X": view["real_val_X_native"],
            "val_y": view["real_val_y"],
            "test_X": view["syn_test_X_native"],
            "test_y": view["syn_test_y"],
        },
        {
            "name": "synthetic_to_real",
            "train_X": view["syn_X_native"],
            "train_y": view["syn_y"],
            "val_X": view["real_val_X_native"],
            "val_y": view["real_val_y"],
            "test_X": view["real_test_X_native"],
            "test_y": view["real_test_y"],
        },
        {
            "name": "real_plus_synthetic_to_real",
            "train_X": np.concatenate([view["real_train_X_native"], view["syn_X_native"]], axis=0),
            "train_y": np.concatenate([view["real_train_y"], view["syn_y"]], axis=0),
            "val_X": view["real_val_X_native"],
            "val_y": view["real_val_y"],
            "test_X": view["real_test_X_native"],
            "test_y": view["real_test_y"],
        },
    ]


def result_csv_path(framework):
    return OUT_DIR / f"{framework}_native_downstream_results.csv"


def activity_csv_path(framework):
    return OUT_DIR / f"{framework}_native_per_activity_results.csv"


def get_existing_result_row(framework, experiment, modality, model=None):
    for path in result_csv_candidates(framework):
        if not Path(path).exists():
            continue
        try:
            df = pd.read_csv(path)
        except Exception:
            continue

        required = {"framework", "experiment", "native_modality"}
        if not required.issubset(df.columns):
            continue

        mask = (
            (df["framework"].astype(str) == framework)
            & (df["experiment"].astype(str) == experiment)
            & (df["native_modality"].astype(str) == modality)
        )
        if model is not None and "model" in df.columns:
            mask &= df["model"].astype(str) == str(model)

        if mask.any():
            row = df.loc[mask].iloc[-1].to_dict()
            row["_loaded_from_result_csv"] = str(path)
            return row

    return None


def get_existing_activity_rows(framework, experiment, modality, model=None):
    for path in activity_csv_candidates(framework):
        if not Path(path).exists():
            continue
        try:
            df = pd.read_csv(path)
        except Exception:
            continue

        required = {"framework", "experiment", "native_modality"}
        if not required.issubset(df.columns):
            continue

        mask = (
            (df["framework"].astype(str) == framework)
            & (df["experiment"].astype(str) == experiment)
            & (df["native_modality"].astype(str) == modality)
        )
        if model is not None and "model" in df.columns:
            mask &= df["model"].astype(str) == str(model)

        if mask.any():
            return df.loc[mask].copy()

    return pd.DataFrame()

# =========================
# TSAI
# =========================

def import_tsai_stuff():
    try:
        import torch
        import tsai.all as tsai_all
        from tsai.all import get_ts_dls, TSClassification, TSStandardize, ts_learner
        try:
            from fastai.metrics import accuracy
        except Exception:
            from tsai.all import accuracy
        from fastai.callback.tracker import SaveModelCallback
    except Exception as e:
        raise ImportError(f"Could not import tsai/fastai: {repr(e)}")

    if not hasattr(tsai_all, TSAI_ARCH):
        raise ValueError(f"TSAI_ARCH='{TSAI_ARCH}' was not found in tsai.all")

    return {
        "torch": torch,
        "get_ts_dls": get_ts_dls,
        "TSClassification": TSClassification,
        "TSStandardize": TSStandardize,
        "ts_learner": ts_learner,
        "accuracy": accuracy,
        "SaveModelCallback": SaveModelCallback,
        "arch_obj": getattr(tsai_all, TSAI_ARCH),
    }


def extract_tsai_pred_indices(pred_decoded):
    pred = pred_decoded.detach().cpu().numpy() if hasattr(pred_decoded, "detach") else np.asarray(pred_decoded)
    pred = np.asarray(pred).reshape(-1)
    return np.array([int(x.item() if hasattr(x, "item") else x) for x in pred], dtype=np.int64)


def get_tsai_model_file(experiment, modality):
    stem = sanitize_name(f"best_{TSAI_ARCH}_{experiment}_{modality}")
    return OUT_DIR / "tsai_saved_models" / f"{stem}.pth", stem


def find_tsai_real_model_file(modality):
    candidates = []
    row = get_existing_result_row("tsai", "real_to_real", modality, model=TSAI_ARCH)
    if row is not None:
        saved = row.get("saved_best_model_file", "")
        if str(saved).lower() not in {"", "nan", "none"}:
            candidates.append(Path(saved))

    candidates.append(get_tsai_model_file("real_to_real", modality)[0])

    if PRETRAINED_RESULTS_DIR.exists():
        candidates.extend(sorted(PRETRAINED_RESULTS_DIR.glob(f"**/*{sanitize_name(TSAI_ARCH)}*real_to_real*{sanitize_name(modality)}*.pth")))
        candidates.extend(sorted(PRETRAINED_RESULTS_DIR.glob(f"**/*real_to_real*{sanitize_name(modality)}*.pth")))

    unique = []
    seen = set()
    for p in candidates:
        p = Path(p)
        key = str(p.resolve()) if p.exists() else str(p)
        if key not in seen:
            unique.append(p)
            seen.add(key)

    for p in unique:
        if Path(p).exists():
            return Path(p)

    raise FileNotFoundError(
        f"Missing tsai Real->Real model for modality '{modality}'. "
        f"Looked in current OUT_DIR and PRETRAINED_RESULTS_DIR={PRETRAINED_RESULTS_DIR}."
    )


def build_tsai_learner(exp, tsai_obj):
    X_train = to_channels_first(exp["train_X"])
    X_val = to_channels_first(exp["val_X"])
    X_test = to_channels_first(exp["test_X"])

    y_train_idx = labels_to_indices(exp["train_y"])
    y_val_idx = labels_to_indices(exp["val_y"])
    y_test_idx = labels_to_indices(exp["test_y"])

    X_trainval = np.concatenate([X_train, X_val], axis=0).astype(np.float32)
    y_trainval = np.concatenate([y_train_idx, y_val_idx], axis=0).astype(np.int64)
    splits = (np.arange(0, len(X_train)), np.arange(len(X_train), len(X_trainval)))

    dls = tsai_obj["get_ts_dls"](
        X_trainval,
        y_trainval,
        splits=splits,
        tfms=[None, tsai_obj["TSClassification"]()],
        batch_tfms=tsai_obj["TSStandardize"](),
        bs=BATCH_SIZE,
    )
    learn = tsai_obj["ts_learner"](dls, tsai_obj["arch_obj"], metrics=tsai_obj["accuracy"])
    learn.path = OUT_DIR
    learn.model_dir = "tsai_saved_models"

    return {
        "learn": learn,
        "dls": dls,
        "X_train": X_train,
        "X_test": X_test,
        "y_test_idx": y_test_idx,
        "y_true": indices_to_labels(y_test_idx),
    }


def get_best_tsai_epoch_and_score(learn, monitor="accuracy"):
    values = list(getattr(learn.recorder, "values", []))
    if not values:
        return None, None
    metric_names = list(getattr(learn.recorder, "metric_names", []))
    value_names = metric_names[1:-1] if len(metric_names) >= 2 and len(metric_names) == len(values[0]) + 2 else metric_names
    if monitor not in value_names:
        return None, None
    monitor_values = np.array([float(row[value_names.index(monitor)]) for row in values], dtype=np.float64)
    if len(monitor_values) == 0 or np.all(np.isnan(monitor_values)):
        return None, None
    return int(np.nanargmax(monitor_values)) + 1, float(np.nanmax(monitor_values))


def predict_tsai(learn, X_test, y_test_idx):
    pred_output = learn.get_X_preds(X_test, y_test_idx, bs=BATCH_SIZE, with_decoded=True)
    return indices_to_labels(extract_tsai_pred_indices(pred_output[-1]))


def make_tsai_row(exp, view, modality, X_train, X_test, metrics, epochs, best_epoch, best_val_accuracy,
                  model_file, used_real_model=False):
    return {
        "framework": "tsai",
        "model": TSAI_ARCH,
        "experiment": exp["name"],
        "native_modality": modality,
        "native_hz": view["native_hz"],
        "channels": ",".join(view["channels"]),
        "description": view.get("description", ""),
        "input_shape_train_native_N_T_C": list(exp["train_X"].shape),
        "input_shape_test_native_N_T_C": list(exp["test_X"].shape),
        "input_shape_train_framework_N_C_T": list(X_train.shape),
        "input_shape_test_framework_N_C_T": list(X_test.shape),
        "epochs": epochs,
        "best_epoch_by_val_accuracy": best_epoch,
        "best_val_accuracy": best_val_accuracy,
        "saved_best_model_file": str(model_file),
        "used_saved_real_to_real_model": bool(used_real_model),
        "training_reused_from_experiment": "real_to_real" if used_real_model else "",
        "batch_size": BATCH_SIZE,
        "lr": LR_TSAI,
        **metrics,
    }


def run_tsai(views, modalities):
    try:
        tsai_obj = import_tsai_stuff()
    except Exception as e:
        print("\n[tsai] Skipping tsai.")
        print("Error:", repr(e))
        return pd.DataFrame(), pd.DataFrame()

    rows = []
    activity_rows = []

    for modality in modalities:
        if modality not in views:
            print(f"[tsai] Skipping unknown modality: {modality}")
            continue

        view = views[modality]
        for exp in get_experiments_for_view(view):
            print("\n" + "=" * 80)
            print(f"[tsai] {exp['name']} | {modality}")
            print("=" * 80)

            if exp["name"] == "real_to_real" and not RUN_REAL_TO_REAL_ONLY:
                existing = get_existing_result_row("tsai", "real_to_real", modality, model=TSAI_ARCH)
                if existing is not None:
                    print("Reusing saved tsai Real->Real metrics.")
                    rows.append(existing)
                    existing_activity = get_existing_activity_rows("tsai", "real_to_real", modality, model=TSAI_ARCH)
                    if len(existing_activity) > 0:
                        activity_rows.append(existing_activity)
                    continue

            set_seed(SEED)
            prepared = None
            try:
                prepared = build_tsai_learner(exp, tsai_obj)
                learn = prepared["learn"]

                if exp["name"] == "real_to_synthetic" and USE_REAL_MODELS:
                    model_file = find_tsai_real_model_file(modality)
                    model_file = copy_external_tsai_model_if_needed(model_file)
                    print("Loading tsai Real->Real model:", model_file)
                    learn.load(model_file.stem)
                    best_epoch = None
                    best_val_accuracy = None
                    source = get_existing_result_row("tsai", "real_to_real", modality, model=TSAI_ARCH)
                    if source is not None:
                        best_epoch = source.get("best_epoch_by_val_accuracy", None)
                        best_val_accuracy = source.get("best_val_accuracy", None)
                    epochs = 0
                    used_real_model = True
                else:
                    model_file, model_stem = get_tsai_model_file(exp["name"], modality)
                    save_best_cb = tsai_obj["SaveModelCallback"](monitor="accuracy", comp=np.greater, fname=model_stem)
                    learn.fit_one_cycle(EPOCHS_TSAI, LR_TSAI, cbs=[save_best_cb])
                    best_epoch, best_val_accuracy = get_best_tsai_epoch_and_score(learn, monitor="accuracy")
                    learn.load(model_stem)
                    epochs = EPOCHS_TSAI
                    used_real_model = False

                y_true = prepared["y_true"]
                y_pred = predict_tsai(learn, prepared["X_test"], prepared["y_test_idx"])
                metrics = compute_classification_metrics(y_true, y_pred)

                activity_df = save_predictions_cm_and_activity_report(
                    "tsai", TSAI_ARCH, exp["name"], modality, view["native_hz"], view["channels"], y_true, y_pred
                )
                activity_rows.append(activity_df)

                row = make_tsai_row(
                    exp, view, modality, prepared["X_train"], prepared["X_test"], metrics,
                    epochs, best_epoch, best_val_accuracy, model_file, used_real_model=used_real_model
                )
                rows.append(row)
                print(json.dumps(row, indent=2))

            except Exception as e:
                warnings.warn(f"[tsai] Failed {exp['name']} | {modality}: {repr(e)}")
                rows.append({"framework": "tsai", "model": TSAI_ARCH, "experiment": exp["name"], "native_modality": modality, "error": repr(e)})

            finally:
                try:
                    del prepared
                    if tsai_obj["torch"].cuda.is_available():
                        tsai_obj["torch"].cuda.empty_cache()
                except Exception:
                    pass

    df = pd.DataFrame(rows)
    df.to_csv(result_csv_path("tsai"), index=False)
    activity_df_all = pd.concat(activity_rows, ignore_index=True) if activity_rows else pd.DataFrame()
    activity_df_all.to_csv(activity_csv_path("tsai"), index=False)
    print("\n[tsai] Saved:", result_csv_path("tsai"))
    print("[tsai] Saved:", activity_csv_path("tsai"))
    return df, activity_df_all

# =========================
# AEON
# =========================

def import_aeon_classifier_class():
    try:
        from aeon.classification.convolution_based import MiniRocketClassifier
        return MiniRocketClassifier
    except Exception:
        try:
            from aeon.classification.convolution_based import RocketClassifier
            return RocketClassifier
        except Exception as e:
            raise ImportError(f"Could not import MiniRocketClassifier or RocketClassifier: {repr(e)}")


def make_aeon_classifier():
    Classifier = import_aeon_classifier_class()
    params = inspect.signature(Classifier).parameters
    kwargs = {}
    if "n_kernels" in params:
        kwargs["n_kernels"] = AEON_N_KERNELS
    if "num_kernels" in params:
        kwargs["num_kernels"] = AEON_N_KERNELS
    if "n_jobs" in params:
        kwargs["n_jobs"] = AEON_N_JOBS
    if "random_state" in params:
        kwargs["random_state"] = SEED
    return Classifier(**kwargs)


def get_aeon_model_file(model_name, experiment, modality):
    return OUT_DIR / "aeon_saved_models" / f"{sanitize_name(model_name)}_{sanitize_name(experiment)}_{sanitize_name(modality)}.joblib"


def find_aeon_real_model_file(modality):
    candidates = []
    row = get_existing_result_row("aeon", "real_to_real", modality)
    if row is not None:
        saved = row.get("saved_model_file", "")
        if str(saved).lower() not in {"", "nan", "none"}:
            candidates.append(Path(saved))

    model_dir = OUT_DIR / "aeon_saved_models"
    if model_dir.exists():
        candidates.extend(sorted(model_dir.glob(f"*_real_to_real_{sanitize_name(modality)}.joblib")))

    if PRETRAINED_RESULTS_DIR.exists():
        candidates.extend(sorted(PRETRAINED_RESULTS_DIR.glob(f"**/*_real_to_real_{sanitize_name(modality)}.joblib")))
        candidates.extend(sorted(PRETRAINED_RESULTS_DIR.glob(f"**/*real_to_real*{sanitize_name(modality)}*.joblib")))

    unique = []
    seen = set()
    for p in candidates:
        p = Path(p)
        key = str(p.resolve()) if p.exists() else str(p)
        if key not in seen:
            unique.append(p)
            seen.add(key)

    for p in unique:
        if Path(p).exists():
            return Path(p)

    raise FileNotFoundError(
        f"Missing aeon Real->Real model for modality '{modality}'. "
        f"Looked in current OUT_DIR and PRETRAINED_RESULTS_DIR={PRETRAINED_RESULTS_DIR}."
    )


def save_aeon_model(clf, experiment, modality):
    model_dir = OUT_DIR / "aeon_saved_models"
    model_dir.mkdir(parents=True, exist_ok=True)
    model_path = get_aeon_model_file(clf.__class__.__name__, experiment, modality)
    joblib.dump(clf, model_path)
    print("Saved aeon model:", model_path)
    return str(model_path)


def make_aeon_row(exp, view, modality, model_name, X_train, X_test, metrics, saved_model_file,
                  used_real_model=False):
    return {
        "framework": "aeon",
        "model": model_name,
        "experiment": exp["name"],
        "native_modality": modality,
        "native_hz": view["native_hz"],
        "channels": ",".join(view["channels"]),
        "description": view.get("description", ""),
        "input_shape_train_native_N_T_C": list(exp["train_X"].shape),
        "input_shape_test_native_N_T_C": list(exp["test_X"].shape),
        "input_shape_train_framework_N_C_T": list(X_train.shape),
        "input_shape_test_framework_N_C_T": list(X_test.shape),
        "n_kernels": AEON_N_KERNELS,
        "n_jobs": AEON_N_JOBS,
        "saved_model_file": str(saved_model_file),
        "used_saved_real_to_real_model": bool(used_real_model),
        "training_reused_from_experiment": "real_to_real" if used_real_model else "",
        **metrics,
    }


def run_aeon(views, modalities):
    try:
        import aeon  # noqa: F401
    except Exception as e:
        print("\n[aeon] Skipping aeon.")
        print("Error:", repr(e))
        return pd.DataFrame(), pd.DataFrame()

    rows = []
    activity_rows = []

    for modality in modalities:
        if modality not in views:
            print(f"[aeon] Skipping unknown modality: {modality}")
            continue

        view = views[modality]
        for exp in get_experiments_for_view(view):
            print("\n" + "=" * 80)
            print(f"[aeon] {exp['name']} | {modality}")
            print("=" * 80)

            if exp["name"] == "real_to_real" and not RUN_REAL_TO_REAL_ONLY:
                existing = get_existing_result_row("aeon", "real_to_real", modality)
                if existing is not None:
                    print("Reusing saved aeon Real->Real metrics.")
                    rows.append(existing)
                    existing_activity = get_existing_activity_rows("aeon", "real_to_real", modality)
                    if len(existing_activity) > 0:
                        activity_rows.append(existing_activity)
                    continue

            X_train = to_channels_first(exp["train_X"])
            X_test = to_channels_first(exp["test_X"])
            y_train = exp["train_y"].astype(np.int64)
            y_test = exp["test_y"].astype(np.int64)

            train_windows_original_before_aeon_filter = int(len(y_train))
            test_windows_original_before_aeon_filter = int(len(y_test))
            train_windows_dropped_by_aeon_filter = 0
            test_windows_dropped_by_aeon_filter = 0

            if AEON_FIX_LOW_VARIATION:
                X_test, y_test, test_windows_dropped_by_aeon_filter = keep_nonflat_cases_for_aeon(
                    X_test,
                    y_test,
                    min_std=AEON_MIN_STD,
                    label=f"test {exp['name']} {modality}",
                )

                if not (exp["name"] == "real_to_synthetic" and USE_REAL_MODELS):
                    X_train, y_train, train_windows_dropped_by_aeon_filter = keep_nonflat_cases_for_aeon(
                        X_train,
                        y_train,
                        min_std=AEON_MIN_STD,
                        label=f"train {exp['name']} {modality}",
                    )

            try:
                if exp["name"] == "real_to_synthetic" and USE_REAL_MODELS:
                    model_file = find_aeon_real_model_file(modality)
                    print("Loading aeon Real->Real model:", model_file)
                    clf = joblib.load(model_file)
                    saved_model_file = str(model_file)
                    used_real_model = True
                else:
                    set_seed(SEED)
                    clf = make_aeon_classifier()
                    print("Aeon model:", clf.__class__.__name__)
                    print("Train shape:", X_train.shape)
                    print("Test shape: ", X_test.shape)
                    clf.fit(X_train, y_train)
                    saved_model_file = save_aeon_model(clf, exp["name"], modality)
                    used_real_model = False

                y_pred = clf.predict(X_test).astype(np.int64)
                metrics = compute_classification_metrics(y_test, y_pred)

                activity_df = save_predictions_cm_and_activity_report(
                    "aeon", clf.__class__.__name__, exp["name"], modality, view["native_hz"], view["channels"], y_test, y_pred
                )
                activity_rows.append(activity_df)

                row = make_aeon_row(
                    exp, view, modality, clf.__class__.__name__, X_train, X_test,
                    metrics, saved_model_file, used_real_model=used_real_model
                )
                row.update({
                    "train_windows_original_before_aeon_filter": train_windows_original_before_aeon_filter,
                    "train_windows_dropped_by_aeon_filter": train_windows_dropped_by_aeon_filter,
                    "test_windows_original_before_aeon_filter": test_windows_original_before_aeon_filter,
                    "test_windows_dropped_by_aeon_filter": test_windows_dropped_by_aeon_filter,
                    "aeon_fix_low_variation": AEON_FIX_LOW_VARIATION,
                    "aeon_min_std": AEON_MIN_STD,
                })
                rows.append(row)
                print(json.dumps(row, indent=2))

            except Exception as e:
                warnings.warn(f"[aeon] Failed {exp['name']} | {modality}: {repr(e)}")
                rows.append({"framework": "aeon", "experiment": exp["name"], "native_modality": modality, "error": repr(e)})

    df = pd.DataFrame(rows)
    df.to_csv(result_csv_path("aeon"), index=False)
    activity_df_all = pd.concat(activity_rows, ignore_index=True) if activity_rows else pd.DataFrame()
    activity_df_all.to_csv(activity_csv_path("aeon"), index=False)
    print("\n[aeon] Saved:", result_csv_path("aeon"))
    print("[aeon] Saved:", activity_csv_path("aeon"))
    return df, activity_df_all

# =========================
# RUN AND COVERAGE
# =========================

def expected_experiments():
    if RUN_REAL_TO_REAL_ONLY:
        return ["real_to_real"]
    return ["real_to_real", "real_to_synthetic", "synthetic_to_real", "real_plus_synthetic_to_real"]


def save_coverage_report(final_results_df):
    expected = pd.DataFrame(
        list(itertools.product(FRAMEWORKS, expected_experiments(), MODALITIES)),
        columns=["framework", "experiment", "native_modality"],
    )

    if len(final_results_df) > 0:
        df = final_results_df.copy()
        if "error" not in df.columns:
            df["error"] = ""
        df["has_error"] = df["error"].fillna("").astype(str) != ""
        actual = (
            df.groupby(["framework", "experiment", "native_modality"], dropna=False)
            .agg(row_count=("framework", "size"), error_count=("has_error", "sum"))
            .reset_index()
        )
    else:
        actual = pd.DataFrame(columns=["framework", "experiment", "native_modality", "row_count", "error_count"])

    coverage = expected.merge(actual, on=["framework", "experiment", "native_modality"], how="left")
    coverage["row_count"] = coverage["row_count"].fillna(0).astype(int)
    coverage["error_count"] = coverage["error_count"].fillna(0).astype(int)
    coverage["status"] = np.where(coverage["row_count"] == 0, "missing", np.where(coverage["error_count"] > 0, "error", "ok"))

    path = OUT_DIR / "experiment_coverage_report.csv"
    coverage.to_csv(path, index=False)
    print("Saved coverage report:", path)
    print("Expected rows:", len(expected))
    print("Actual rows:", len(final_results_df))
    print("Rows with errors:", int(coverage["error_count"].sum()))
    return coverage




def main():
    set_seed(SEED)

    print("=" * 80)
    print("Native tsai + aeon evaluation")
    print("=" * 80)
    print("CURRENT_MODEL_FAMILY:", CURRENT_MODEL_FAMILY)
    print("CURRENT_SYNTHETIC_METHOD:", CURRENT_SYNTHETIC_METHOD)
    print("CURRENT_SYNTHETIC_METHOD_DISPLAY:", CURRENT_SYNTHETIC_METHOD_DISPLAY)
    print("RUN_REAL_TO_REAL_ONLY:", RUN_REAL_TO_REAL_ONLY)
    print("USE_REAL_MODELS:", USE_REAL_MODELS)
    print("FRAMEWORKS:", FRAMEWORKS)
    print("MODALITIES:", MODALITIES)
    print("OUT_DIR:", OUT_DIR)
    print("REAL_DIR:", REAL_DIR)
    print("SYN_DIR:", SYN_DIR)
    print("PRETRAINED_RESULTS_DIR:", PRETRAINED_RESULTS_DIR)

    load_synthetic = not RUN_REAL_TO_REAL_ONLY
    real_X, real_y, real_subjects, syn_X, syn_y, syn_subjects = load_native_data(load_synthetic=load_synthetic)

    views = make_native_dataset_views(real_X, real_y, real_subjects, syn_X, syn_y, syn_subjects)
    shape_report_df = save_shape_report(views)
    safe_display(shape_report_df)

    all_results = []
    all_activity_results = []

    if "tsai" in FRAMEWORKS:
        tsai_results, tsai_activity = run_tsai(views, MODALITIES)
        all_results.append(tsai_results)
        all_activity_results.append(tsai_activity)

    if "aeon" in FRAMEWORKS:
        aeon_results, aeon_activity = run_aeon(views, MODALITIES)
        all_results.append(aeon_results)
        all_activity_results.append(aeon_activity)

    final_results = pd.concat(all_results, ignore_index=True) if all_results else pd.DataFrame()
    final_activity = pd.concat(all_activity_results, ignore_index=True) if all_activity_results else pd.DataFrame()

    final_results = add_method_columns(final_results)
    final_activity = add_method_columns(final_activity)

    final_results_path = OUT_DIR / "all_framework_native_results.csv"
    final_activity_path = OUT_DIR / "all_framework_native_per_activity_results.csv"
    final_results.to_csv(final_results_path, index=False)
    final_activity.to_csv(final_activity_path, index=False)
    coverage = save_coverage_report(final_results)

    summary = {
        "model_family": CURRENT_MODEL_FAMILY,
        "synthetic_method": CURRENT_SYNTHETIC_METHOD,
        "synthetic_method_display_name": CURRENT_SYNTHETIC_METHOD_DISPLAY,
        "frameworks": FRAMEWORKS,
        "modalities": MODALITIES,
        "run_real_to_real_only": RUN_REAL_TO_REAL_ONLY,
        "use_real_models": USE_REAL_MODELS,
        "epochs_tsai": EPOCHS_TSAI,
        "batch_size": BATCH_SIZE,
        "lr_tsai": LR_TSAI,
        "tsai_arch": TSAI_ARCH,
        "aeon_n_kernels": AEON_N_KERNELS,
        "aeon_n_jobs": AEON_N_JOBS,
        "aeon_fix_low_variation": AEON_FIX_LOW_VARIATION,
        "aeon_min_std": AEON_MIN_STD,
        "out_dir": str(OUT_DIR),
        "real_dir": str(REAL_DIR),
        "syn_dir": str(SYN_DIR),
        "pretrained_results_dir": str(PRETRAINED_RESULTS_DIR),
        "final_results_path": str(final_results_path),
        "final_activity_path": str(final_activity_path),
    }
    summary_path = OUT_DIR / "evaluation_summary.json"
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print("\n" + "=" * 80)
    print("DONE")
    print("=" * 80)
    print("Saved combined aggregate results:", final_results_path)
    print("Saved combined per-activity results:", final_activity_path)
    print("Saved summary:", summary_path)

    print("\nAggregate results:")
    safe_display(final_results)
    print("\nCoverage:")
    safe_display(coverage)

    return {
        "final_results": final_results,
        "final_activity": final_activity,
        "coverage": coverage,
        "shape_report": shape_report_df,
        "summary_path": summary_path,
        "out_dir": OUT_DIR,
    }


def save_project_combined_outputs(method_outputs, project_root, output_root, model_family):
    output_root = Path(output_root)
    family_dir = output_root / model_family
    family_dir.mkdir(parents=True, exist_ok=True)

    result_frames = []
    activity_frames = []
    coverage_frames = []

    for method_name, outputs in method_outputs.items():
        if outputs is None:
            continue

        res = outputs.get("final_results", pd.DataFrame())
        act = outputs.get("final_activity", pd.DataFrame())
        cov = outputs.get("coverage", pd.DataFrame())

        if len(res) > 0:
            result_frames.append(res.copy())
        if len(act) > 0:
            activity_frames.append(act.copy())
        if len(cov) > 0:
            cov = cov.copy()
            cov.insert(0, "synthetic_method", method_name)
            cov.insert(0, "model_family", model_family)
            coverage_frames.append(cov)

    combined_results = pd.concat(result_frames, ignore_index=True) if result_frames else pd.DataFrame()
    combined_activity = pd.concat(activity_frames, ignore_index=True) if activity_frames else pd.DataFrame()
    combined_coverage = pd.concat(coverage_frames, ignore_index=True) if coverage_frames else pd.DataFrame()

    combined_results_path = family_dir / "combined_all_framework_native_results.csv"
    combined_activity_path = family_dir / "combined_all_framework_native_per_activity_results.csv"
    combined_coverage_path = family_dir / "combined_experiment_coverage_report.csv"
    compact_path = family_dir / "combined_compact_downstream_comparison.csv"
    ranking_path = family_dir / "combined_macro_f1_ranking.csv"

    combined_results.to_csv(combined_results_path, index=False)
    combined_activity.to_csv(combined_activity_path, index=False)
    combined_coverage.to_csv(combined_coverage_path, index=False)

    if len(combined_results) > 0:
        compact_cols = [
            "model_family",
            "synthetic_method",
            "synthetic_method_display_name",
            "framework",
            "model",
            "native_modality",
            "experiment",
            "accuracy",
            "macro_f1",
            "weighted_f1",
            "balanced_accuracy",
            "used_saved_real_to_real_model",
            "training_reused_from_experiment",
            "error",
        ]
        compact_cols = [c for c in compact_cols if c in combined_results.columns]
        compact = combined_results[compact_cols].copy()
        compact.to_csv(compact_path, index=False)

        if "macro_f1" in combined_results.columns:
            ranking = combined_results.dropna(subset=["macro_f1"]).sort_values(
                by=["native_modality", "macro_f1"],
                ascending=[True, False],
            )
            ranking.to_csv(ranking_path, index=False)
        else:
            pd.DataFrame().to_csv(ranking_path, index=False)
    else:
        pd.DataFrame().to_csv(compact_path, index=False)
        pd.DataFrame().to_csv(ranking_path, index=False)

    summary = {
        "model_family": model_family,
        "methods": list(method_outputs.keys()),
        "combined_results_path": str(combined_results_path),
        "combined_activity_path": str(combined_activity_path),
        "combined_coverage_path": str(combined_coverage_path),
        "compact_path": str(compact_path),
        "ranking_path": str(ranking_path),
    }
    summary_path = family_dir / "combined_evaluation_summary.json"
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print("\nSaved family-level combined outputs:")
    print("  ", combined_results_path)
    print("  ", combined_activity_path)
    print("  ", combined_coverage_path)
    print("  ", compact_path)
    print("  ", ranking_path)
    print("  ", summary_path)

    return {
        "combined_results": combined_results,
        "combined_activity": combined_activity,
        "combined_coverage": combined_coverage,
        "combined_results_path": combined_results_path,
        "combined_activity_path": combined_activity_path,
        "combined_coverage_path": combined_coverage_path,
        "compact_path": compact_path,
        "ranking_path": ranking_path,
        "summary_path": summary_path,
    }


def run_project_evaluation(
    model_families=("kovae",),
    project_root="/home/iailab42/khans1/projects/ir",
    output_root=None,
    pretrained_results_dir=None,
):
    project_root = Path(project_root)

    if output_root is None:
        output_root = project_root / "results/downstream_extended_tsai_aeon"
    else:
        output_root = Path(output_root)

    if pretrained_results_dir is None:
        pretrained_results_dir = project_root / "models/downstream/pretrained/tsai_aeon_results"
    else:
        pretrained_results_dir = Path(pretrained_results_dir)

    all_family_outputs = {}

    for model_family in model_families:
        if model_family not in MODEL_FAMILY_CONFIGS:
            raise ValueError(f"Unknown model family: {model_family}")

        method_outputs = {}
        synthetic_methods = MODEL_FAMILY_CONFIGS[model_family]["synthetic_methods"]

        for synthetic_method in synthetic_methods:
            print("\n" + "#" * 100)
            print(f"RUNNING {model_family} | {synthetic_method}")
            print("#" * 100)

            configure_project_paths(
                project_root=project_root,
                model_family=model_family,
                synthetic_method=synthetic_method,
                output_root=output_root,
                pretrained_results_dir=pretrained_results_dir,
            )

            method_outputs[synthetic_method] = main()

        family_outputs = save_project_combined_outputs(
            method_outputs=method_outputs,
            project_root=project_root,
            output_root=output_root,
            model_family=model_family,
        )
        all_family_outputs[model_family] = {
            "method_outputs": method_outputs,
            "family_outputs": family_outputs,
        }

    return all_family_outputs

## Run cell

Set the frameworks, modalities, and model families here.

For the full friend-style evaluation use:

```python
FRAMEWORKS = ["tsai", "aeon"]
MODALITIES = ["acc", "bvp", "eda", "temp", "fused"]
```

For a faster test, use fewer modalities or only one framework.

In [ ]:
# =========================
# FINAL RUN CONFIG
# =========================

PROJECT_ROOT = Path("/home/iailab42/khans1/projects/ir")
PRETRAINED_RESULTS_DIR = PROJECT_ROOT / "models/downstream/pretrained/tsai_aeon_results"

# Friend-style full evaluation.
# FRAMEWORKS = ["tsai", "aeon"]
FRAMEWORKS = ["tsai"]
MODALITIES = ["acc", "bvp", "eda", "temp", "fused"]

# Keep pretrained model reuse.
USE_REAL_MODELS = True
RUN_REAL_TO_REAL_ONLY = False

# tsai settings from friend's notebook.
EPOCHS_TSAI = 50
BATCH_SIZE = 1024
LR_TSAI = 1e-3
TSAI_ARCH = "InceptionTimePlus"

# aeon settings from friend's notebook.
AEON_N_KERNELS = 5000
AEON_N_JOBS = 8

# Keep aeon compatibility fix.
AEON_FIX_LOW_VARIATION = True
AEON_MIN_STD = 1e-6

# Run both families, or choose only one:
# MODEL_FAMILIES_TO_RUN = ["kovae"]
# MODEL_FAMILIES_TO_RUN = ["timevae"]
MODEL_FAMILIES_TO_RUN = ["kovae", "timevae"]

print("Starting evaluation from final cell only.")
print("MODEL_FAMILIES_TO_RUN:", MODEL_FAMILIES_TO_RUN)
print("FRAMEWORKS:", FRAMEWORKS)
print("MODALITIES:", MODALITIES)

outputs = run_project_evaluation(
    model_families=MODEL_FAMILIES_TO_RUN,
    project_root=PROJECT_ROOT,
    output_root=PROJECT_ROOT / "results/downstream_extended_tsai_aeon",
    pretrained_results_dir=PRETRAINED_RESULTS_DIR,
)

Starting evaluation from final cell only.
MODEL_FAMILIES_TO_RUN: ['kovae', 'timevae']
FRAMEWORKS: ['tsai']
MODALITIES: ['acc', 'bvp', 'eda', 'temp', 'fused']

####################################################################################################
RUNNING kovae | rollout_v1
####################################################################################################

Configured project paths
  PROJECT_ROOT: /home/iailab42/khans1/projects/ir
  model_family: kovae
  synthetic_method: rollout_v1
  synthetic_method_display: KoVAE-Rollout
  REAL_DIR: /home/iailab42/khans1/projects/ir/data/processed/native_rates
  SYN_DIR: /home/iailab42/khans1/projects/ir/data/synthetic_subjects/kovae/rollout_v1
  OUT_DIR: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1
  PRETRAINED_RESULTS_DIR: /home/iailab42/khans1/projects/ir/models/downstream/pretrained/tsai_aeon_results
================================================================================
Native tsai + aeon evaluation
================================================================================
CURRENT_MODEL_FAMILY: kovae
CURRENT_SYNTHETIC_METHOD: rollout_v1
CURRENT_SYNTHETIC_METHOD_DISPLAY: KoVAE-Rollout
RUN_REAL_TO_REAL_ONLY: False
USE_REAL_MODELS: True
FRAMEWORKS: ['tsai']
MODALITIES: ['acc', 'bvp', 'eda', 'temp', 'fused']
OUT_DIR: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1
REAL_DIR: /home/iailab42/khans1/projects/ir/data/processed/native_rates
SYN_DIR: /home/iailab42/khans1/projects/ir/data/synthetic_subjects/kovae/rollout_v1
PRETRAINED_RESULTS_DIR: /home/iailab42/khans1/projects/ir/models/downstream/pretrained/tsai_aeon_results

Loaded real data:
  y: (46925,)
  subjects: (46925,)
  acc: (46925, 256, 3)
  bvp: (46925, 512, 1)
  slow: (46925, 32, 2)

Loaded synthetic data:
  y: (30000,)
  subjects: (30000,)
  acc: (30000, 256, 3)
  bvp: (30000, 512, 1)
  slow: (30000, 32, 2)

Fixed split OK:
  Train: ['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S9', 'S11', 'S12', 'S13']
  Val:   ['S14', 'S15']
  Test:  ['S7', 'S8', 'S10']

Synthetic test subjects: [np.str_('synthetic_subject_01'), np.str_('synthetic_subject_02'), np.str_('synthetic_subject_03')]
  View acc   : train=(30762, 256, 3), val=(6100, 256, 3), test=(10063, 256, 3), syn_all=(30000, 256, 3), syn_test3=(9000, 256, 3)
  View bvp   : train=(30762, 512, 1), val=(6100, 512, 1), test=(10063, 512, 1), syn_all=(30000, 512, 1), syn_test3=(9000, 512, 1)
  View eda   : train=(30762, 32, 1), val=(6100, 32, 1), test=(10063, 32, 1), syn_all=(30000, 32, 1), syn_test3=(9000, 32, 1)
  View temp  : train=(30762, 32, 1), val=(6100, 32, 1), test=(10063, 32, 1), syn_all=(30000, 32, 1), syn_test3=(9000, 32, 1)
  View fused : train=(30762, 512, 6), val=(6100, 512, 6), test=(10063, 512, 6), syn_all=(30000, 512, 6), syn_test3=(9000, 512, 6)

Saved shape report: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/native_input_shape_report.csv

,native_view,native_hz,channels,native_real_train_shape_N_T_C,native_real_val_shape_N_T_C,native_real_test_shape_N_T_C,framework_real_train_shape_N_C_T,framework_real_val_shape_N_C_T,framework_real_test_shape_N_C_T,native_syn_all_shape_N_T_C,native_syn_test3_shape_N_T_C,syn_test_subjects,framework_syn_all_shape_N_C_T,framework_syn_test3_shape_N_C_T
0,acc,32,"ACC_x,ACC_y,ACC_z","[30762, 256, 3]","[6100, 256, 3]","[10063, 256, 3]","[30762, 3, 256]","[6100, 3, 256]","[10063, 3, 256]","[30000, 256, 3]","[9000, 256, 3]","synthetic_subject_01,synthetic_subject_02,synt...","[30000, 3, 256]","[9000, 3, 256]"
1,bvp,64,BVP,"[30762, 512, 1]","[6100, 512, 1]","[10063, 512, 1]","[30762, 1, 512]","[6100, 1, 512]","[10063, 1, 512]","[30000, 512, 1]","[9000, 512, 1]","synthetic_subject_01,synthetic_subject_02,synt...","[30000, 1, 512]","[9000, 1, 512]"
2,eda,4,EDA,"[30762, 32, 1]","[6100, 32, 1]","[10063, 32, 1]","[30762, 1, 32]","[6100, 1, 32]","[10063, 1, 32]","[30000, 32, 1]","[9000, 32, 1]","synthetic_subject_01,synthetic_subject_02,synt...","[30000, 1, 32]","[9000, 1, 32]"
3,temp,4,TEMP,"[30762, 32, 1]","[6100, 32, 1]","[10063, 32, 1]","[30762, 1, 32]","[6100, 1, 32]","[10063, 1, 32]","[30000, 32, 1]","[9000, 32, 1]","synthetic_subject_01,synthetic_subject_02,synt...","[30000, 1, 32]","[9000, 1, 32]"
4,fused,64,"ACC_x,ACC_y,ACC_z,BVP,EDA,TEMP","[30762, 512, 6]","[6100, 512, 6]","[10063, 512, 6]","[30762, 6, 512]","[6100, 6, 512]","[10063, 6, 512]","[30000, 512, 6]","[9000, 512, 6]","synthetic_subject_01,synthetic_subject_02,synt...","[30000, 6, 512]","[9000, 6, 512]"

================================================================================
[tsai] real_to_real | acc
================================================================================
Reusing saved tsai Real->Real metrics.

================================================================================
[tsai] real_to_synthetic | acc
================================================================================
Copied external tsai model into current output folder: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_to_real_acc.pth
Loading tsai Real->Real model: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_to_real_acc.pth

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_acc_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_acc_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_acc_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_acc_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_acc_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_to_synthetic",
  "native_modality": "acc",
  "native_hz": 32,
  "channels": "ACC_x,ACC_y,ACC_z",
  "description": "ACC only",
  "input_shape_train_native_N_T_C": [
    30762,
    256,
    3
  ],
  "input_shape_test_native_N_T_C": [
    9000,
    256,
    3
  ],
  "input_shape_train_framework_N_C_T": [
    30762,
    3,
    256
  ],
  "input_shape_test_framework_N_C_T": [
    9000,
    3,
    256
  ],
  "epochs": 0,
  "best_epoch_by_val_accuracy": 34,
  "best_val_accuracy": 0.7380327582359314,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_to_real_acc.pth",
  "used_saved_real_to_real_model": true,
  "training_reused_from_experiment": "real_to_real",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.098,
  "macro_precision": 0.06483752580472514,
  "macro_recall": 0.1446193527493118,
  "macro_f1": 0.04613452973390134,
  "weighted_precision": 0.1317924591584474,
  "weighted_recall": 0.098,
  "weighted_f1": 0.07998315878984508,
  "balanced_accuracy": 0.1446193527493118
}

================================================================================
[tsai] synthetic_to_real | acc
================================================================================

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.490812</td><td>2.780220</td><td>0.365410</td><td>00:07</td></tr><tr><td>1</td><td>1.104810</td><td>8.537931</td><td>0.305410</td><td>00:07</td></tr><tr><td>2</td><td>0.800309</td><td>12.908846</td><td>0.319180</td><td>00:07</td></tr><tr><td>3</td><td>0.544108</td><td>17.179090</td><td>0.266885</td><td>00:07</td></tr><tr><td>4</td><td>0.361470</td><td>20.539274</td><td>0.232951</td><td>00:07</td></tr><tr><td>5</td><td>0.242827</td><td>29.138273</td><td>0.231967</td><td>00:07</td></tr><tr><td>6</td><td>0.169234</td><td>17.310942</td><td>0.251475</td><td>00:07</td></tr><tr><td>7</td><td>0.119997</td><td>23.323381</td><td>0.218852</td><td>00:07</td></tr><tr><td>8</td><td>0.086896</td><td>36.230591</td><td>0.237377</td><td>00:07</td></tr><tr><td>9</td><td>0.065899</td><td>29.229647</td><td>0.239672</td><td>00:07</td></tr><tr><td>10</td><td>0.049506</td><td>29.434092</td><td>0.247705</td><td>00:07</td></tr><tr><td>11</td><td>0.040773</td><td>45.738659</td><td>0.240492</td><td>00:07</td></tr><tr><td>12</td><td>0.034402</td><td>40.556999</td><td>0.229344</td><td>00:07</td></tr><tr><td>13</td><td>0.027690</td><td>28.057861</td><td>0.272951</td><td>00:07</td></tr><tr><td>14</td><td>0.020534</td><td>31.144150</td><td>0.256721</td><td>00:07</td></tr><tr><td>15</td><td>0.014821</td><td>34.649830</td><td>0.255738</td><td>00:07</td></tr><tr><td>16</td><td>0.012307</td><td>37.577965</td><td>0.230820</td><td>00:07</td></tr><tr><td>17</td><td>0.011039</td><td>31.835981</td><td>0.260164</td><td>00:07</td></tr><tr><td>18</td><td>0.008942</td><td>42.524677</td><td>0.235738</td><td>00:07</td></tr><tr><td>19</td><td>0.006599</td><td>42.264084</td><td>0.250984</td><td>00:07</td></tr><tr><td>20</td><td>0.004853</td><td>37.224663</td><td>0.287541</td><td>00:07</td></tr><tr><td>21</td><td>0.010160</td><td>52.832169</td><td>0.258197</td><td>00:07</td></tr><tr><td>22</td><td>0.007864</td><td>37.539165</td><td>0.276230</td><td>00:07</td></tr><tr><td>23</td><td>0.005660</td><td>42.850105</td><td>0.277377</td><td>00:07</td></tr><tr><td>24</td><td>0.003730</td><td>48.211933</td><td>0.258197</td><td>00:07</td></tr><tr><td>25</td><td>0.002560</td><td>43.610336</td><td>0.246721</td><td>00:07</td></tr><tr><td>26</td><td>0.002327</td><td>46.463924</td><td>0.302623</td><td>00:07</td></tr><tr><td>27</td><td>0.001920</td><td>40.974697</td><td>0.259180</td><td>00:07</td></tr><tr><td>28</td><td>0.001410</td><td>57.022224</td><td>0.234098</td><td>00:07</td></tr><tr><td>29</td><td>0.001145</td><td>45.946926</td><td>0.261148</td><td>00:07</td></tr><tr><td>30</td><td>0.000857</td><td>41.171459</td><td>0.258197</td><td>00:07</td></tr><tr><td>31</td><td>0.000609</td><td>45.992760</td><td>0.252623</td><td>00:07</td></tr><tr><td>32</td><td>0.000442</td><td>44.897587</td><td>0.246557</td><td>00:07</td></tr><tr><td>33</td><td>0.000335</td><td>46.711002</td><td>0.242623</td><td>00:07</td></tr><tr><td>34</td><td>0.000258</td><td>46.273918</td><td>0.242295</td><td>00:07</td></tr><tr><td>35</td><td>0.000214</td><td>44.837383</td><td>0.242131</td><td>00:07</td></tr><tr><td>36</td><td>0.000180</td><td>46.405327</td><td>0.237869</td><td>00:07</td></tr><tr><td>37</td><td>0.000154</td><td>45.991287</td><td>0.232459</td><td>00:07</td></tr><tr><td>38</td><td>0.000139</td><td>46.071793</td><td>0.232131</td><td>00:07</td></tr><tr><td>39</td><td>0.000124</td><td>46.361660</td><td>0.231639</td><td>00:07</td></tr><tr><td>40</td><td>0.000113</td><td>46.177418</td><td>0.232459</td><td>00:07</td></tr><tr><td>41</td><td>0.000108</td><td>46.496025</td><td>0.230984</td><td>00:07</td></tr><tr><td>42</td><td>0.000103</td><td>46.650837</td><td>0.231475</td><td>00:07</td></tr><tr><td>43</td><td>0.000097</td><td>45.939590</td><td>0.233443</td><td>00:07</td></tr><tr><td>44</td><td>0.000091</td><td>46.519474</td><td>0.232295</td><td>00:07</td></tr><tr><td>45</td><td>0.000089</td><td>46.495758</td><td>0.232787</td><td>00:07</td></tr><tr><td>46</td><td>0.000087</td><td>46.411552</td><td>0.233607</td><td>00:07</td></tr><tr><td>47</td><td>0.000085</td><td>46.627544</td><td>0.232295</td><td>00:07</td></tr><tr><td>48</td><td>0.000084</td><td>46.550880</td><td>0.233279</td><td>00:07</td></tr><tr><td>49</td><td>0.000085</td><td>46.579945</td><td>0.232295</td><td>00:07</td></tr></tbody></table></div>

Better model found at epoch 0 with accuracy value: 0.36540982127189636.

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_acc_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_acc_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_acc_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_acc_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_acc_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "synthetic_to_real",
  "native_modality": "acc",
  "native_hz": 32,
  "channels": "ACC_x,ACC_y,ACC_z",
  "description": "ACC only",
  "input_shape_train_native_N_T_C": [
    30000,
    256,
    3
  ],
  "input_shape_test_native_N_T_C": [
    10063,
    256,
    3
  ],
  "input_shape_train_framework_N_C_T": [
    30000,
    3,
    256
  ],
  "input_shape_test_framework_N_C_T": [
    10063,
    3,
    256
  ],
  "epochs": 50,
  "best_epoch_by_val_accuracy": 1,
  "best_val_accuracy": 0.36540982127189636,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_synthetic_to_real_acc.pth",
  "used_saved_real_to_real_model": false,
  "training_reused_from_experiment": "",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.3912352181258074,
  "macro_precision": 0.24974524727953656,
  "macro_recall": 0.3010351091071484,
  "macro_f1": 0.26535472552115724,
  "weighted_precision": 0.33379527679324206,
  "weighted_recall": 0.3912352181258074,
  "weighted_f1": 0.3535493425665378,
  "balanced_accuracy": 0.3010351091071484
}

================================================================================
[tsai] real_plus_synthetic_to_real | acc
================================================================================

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.489479</td><td>1.267392</td><td>0.562131</td><td>00:14</td></tr><tr><td>1</td><td>1.089416</td><td>1.099095</td><td>0.566885</td><td>00:14</td></tr><tr><td>2</td><td>0.821145</td><td>1.026986</td><td>0.626885</td><td>00:14</td></tr><tr><td>3</td><td>0.614837</td><td>0.991608</td><td>0.614754</td><td>00:14</td></tr><tr><td>4</td><td>0.481863</td><td>0.841141</td><td>0.687541</td><td>00:14</td></tr><tr><td>5</td><td>0.391584</td><td>1.072792</td><td>0.600000</td><td>00:14</td></tr><tr><td>6</td><td>0.346316</td><td>1.008440</td><td>0.633279</td><td>00:14</td></tr><tr><td>7</td><td>0.311305</td><td>0.946263</td><td>0.630328</td><td>00:14</td></tr><tr><td>8</td><td>0.295441</td><td>0.872367</td><td>0.642459</td><td>00:14</td></tr><tr><td>9</td><td>0.281229</td><td>0.827414</td><td>0.667049</td><td>00:14</td></tr><tr><td>10</td><td>0.252388</td><td>0.883499</td><td>0.683770</td><td>00:14</td></tr><tr><td>11</td><td>0.246219</td><td>0.767078</td><td>0.717541</td><td>00:14</td></tr><tr><td>12</td><td>0.227707</td><td>0.964804</td><td>0.686066</td><td>00:14</td></tr><tr><td>13</td><td>0.213156</td><td>0.742995</td><td>0.726393</td><td>00:14</td></tr><tr><td>14</td><td>0.207107</td><td>0.702361</td><td>0.731967</td><td>00:14</td></tr><tr><td>15</td><td>0.196601</td><td>0.720607</td><td>0.744590</td><td>00:14</td></tr><tr><td>16</td><td>0.184845</td><td>0.708171</td><td>0.754754</td><td>00:14</td></tr><tr><td>17</td><td>0.173802</td><td>0.772751</td><td>0.750164</td><td>00:14</td></tr><tr><td>18</td><td>0.167734</td><td>0.837144</td><td>0.702459</td><td>00:14</td></tr><tr><td>19</td><td>0.157080</td><td>0.812336</td><td>0.715738</td><td>00:14</td></tr><tr><td>20</td><td>0.148085</td><td>0.775150</td><td>0.742623</td><td>00:14</td></tr><tr><td>21</td><td>0.132062</td><td>0.750702</td><td>0.752787</td><td>00:14</td></tr><tr><td>22</td><td>0.131363</td><td>0.735040</td><td>0.736066</td><td>00:14</td></tr><tr><td>23</td><td>0.119364</td><td>0.854318</td><td>0.725902</td><td>00:14</td></tr><tr><td>24</td><td>0.112090</td><td>1.059359</td><td>0.690984</td><td>00:14</td></tr><tr><td>25</td><td>0.109090</td><td>0.978447</td><td>0.719508</td><td>00:14</td></tr><tr><td>26</td><td>0.098221</td><td>1.017931</td><td>0.689836</td><td>00:12</td></tr><tr><td>27</td><td>0.091883</td><td>1.077643</td><td>0.708197</td><td>00:14</td></tr><tr><td>28</td><td>0.089672</td><td>0.963931</td><td>0.736557</td><td>00:14</td></tr><tr><td>29</td><td>0.078550</td><td>1.132891</td><td>0.689836</td><td>00:14</td></tr><tr><td>30</td><td>0.073337</td><td>1.235082</td><td>0.695410</td><td>00:14</td></tr><tr><td>31</td><td>0.068415</td><td>0.958240</td><td>0.721967</td><td>00:14</td></tr><tr><td>32</td><td>0.065598</td><td>1.012098</td><td>0.719016</td><td>00:14</td></tr><tr><td>33</td><td>0.059493</td><td>1.054494</td><td>0.717869</td><td>00:14</td></tr><tr><td>34</td><td>0.053354</td><td>1.198121</td><td>0.696230</td><td>00:14</td></tr><tr><td>35</td><td>0.050736</td><td>1.098353</td><td>0.693934</td><td>00:14</td></tr><tr><td>36</td><td>0.046022</td><td>1.272030</td><td>0.703771</td><td>00:14</td></tr><tr><td>37</td><td>0.043774</td><td>1.158320</td><td>0.715246</td><td>00:14</td></tr><tr><td>38</td><td>0.039684</td><td>1.211717</td><td>0.707869</td><td>00:14</td></tr><tr><td>39</td><td>0.038262</td><td>1.392399</td><td>0.700656</td><td>00:14</td></tr><tr><td>40</td><td>0.035690</td><td>1.167300</td><td>0.711967</td><td>00:14</td></tr><tr><td>41</td><td>0.032607</td><td>1.222188</td><td>0.700820</td><td>00:14</td></tr><tr><td>42</td><td>0.029833</td><td>1.264438</td><td>0.702623</td><td>00:14</td></tr><tr><td>43</td><td>0.025921</td><td>1.351269</td><td>0.715246</td><td>00:14</td></tr><tr><td>44</td><td>0.024261</td><td>1.424371</td><td>0.705082</td><td>00:14</td></tr><tr><td>45</td><td>0.023044</td><td>1.424125</td><td>0.705410</td><td>00:14</td></tr><tr><td>46</td><td>0.022049</td><td>1.433329</td><td>0.705902</td><td>00:14</td></tr><tr><td>47</td><td>0.020251</td><td>1.440914</td><td>0.707049</td><td>00:14</td></tr><tr><td>48</td><td>0.020056</td><td>1.425151</td><td>0.711967</td><td>00:14</td></tr><tr><td>49</td><td>0.020024</td><td>1.406218</td><td>0.715082</td><td>00:14</td></tr></tbody></table></div>

Better model found at epoch 0 with accuracy value: 0.5621311664581299.
Better model found at epoch 1 with accuracy value: 0.566885232925415.
Better model found at epoch 2 with accuracy value: 0.6268852353096008.
Better model found at epoch 4 with accuracy value: 0.6875410079956055.
Better model found at epoch 11 with accuracy value: 0.717540979385376.
Better model found at epoch 13 with accuracy value: 0.726393461227417.
Better model found at epoch 14 with accuracy value: 0.7319672107696533.
Better model found at epoch 15 with accuracy value: 0.744590163230896.
Better model found at epoch 16 with accuracy value: 0.7547541260719299.

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_acc_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_acc_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_acc_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_acc_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_acc_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_plus_synthetic_to_real",
  "native_modality": "acc",
  "native_hz": 32,
  "channels": "ACC_x,ACC_y,ACC_z",
  "description": "ACC only",
  "input_shape_train_native_N_T_C": [
    60762,
    256,
    3
  ],
  "input_shape_test_native_N_T_C": [
    10063,
    256,
    3
  ],
  "input_shape_train_framework_N_C_T": [
    60762,
    3,
    256
  ],
  "input_shape_test_framework_N_C_T": [
    10063,
    3,
    256
  ],
  "epochs": 50,
  "best_epoch_by_val_accuracy": 17,
  "best_val_accuracy": 0.7547541260719299,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_plus_synthetic_to_real_acc.pth",
  "used_saved_real_to_real_model": false,
  "training_reused_from_experiment": "",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.6199940375633509,
  "macro_precision": 0.7074534028024384,
  "macro_recall": 0.6576153665704711,
  "macro_f1": 0.6738755718434012,
  "weighted_precision": 0.647870382298217,
  "weighted_recall": 0.6199940375633509,
  "weighted_f1": 0.6260435073188102,
  "balanced_accuracy": 0.6576153665704711
}

================================================================================
[tsai] real_to_real | bvp
================================================================================
Reusing saved tsai Real->Real metrics.

================================================================================
[tsai] real_to_synthetic | bvp
================================================================================
Copied external tsai model into current output folder: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_to_real_bvp.pth
Loading tsai Real->Real model: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_to_real_bvp.pth

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_bvp_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_bvp_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_bvp_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_bvp_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_bvp_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_to_synthetic",
  "native_modality": "bvp",
  "native_hz": 64,
  "channels": "BVP",
  "description": "BVP only",
  "input_shape_train_native_N_T_C": [
    30762,
    512,
    1
  ],
  "input_shape_test_native_N_T_C": [
    9000,
    512,
    1
  ],
  "input_shape_train_framework_N_C_T": [
    30762,
    1,
    512
  ],
  "input_shape_test_framework_N_C_T": [
    9000,
    1,
    512
  ],
  "epochs": 0,
  "best_epoch_by_val_accuracy": 15,
  "best_val_accuracy": 0.5247541069984436,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_to_real_bvp.pth",
  "used_saved_real_to_real_model": true,
  "training_reused_from_experiment": "real_to_real",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.096,
  "macro_precision": 0.0934449605971225,
  "macro_recall": 0.1369628759743091,
  "macro_f1": 0.04640150295063203,
  "weighted_precision": 0.1395432130354831,
  "weighted_recall": 0.096,
  "weighted_f1": 0.05529660719477012,
  "balanced_accuracy": 0.1369628759743091
}

================================================================================
[tsai] synthetic_to_real | bvp
================================================================================

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.871287</td><td>3.355357</td><td>0.186721</td><td>00:14</td></tr><tr><td>1</td><td>1.695996</td><td>8.966938</td><td>0.147869</td><td>00:12</td></tr><tr><td>2</td><td>1.539238</td><td>19.443583</td><td>0.184590</td><td>00:14</td></tr><tr><td>3</td><td>1.396645</td><td>25.299660</td><td>0.169672</td><td>00:14</td></tr><tr><td>4</td><td>1.258591</td><td>31.865881</td><td>0.161311</td><td>00:14</td></tr><tr><td>5</td><td>1.134418</td><td>31.269398</td><td>0.147869</td><td>00:14</td></tr><tr><td>6</td><td>1.031840</td><td>32.184841</td><td>0.156393</td><td>00:14</td></tr><tr><td>7</td><td>0.940249</td><td>21.339966</td><td>0.182951</td><td>00:14</td></tr><tr><td>8</td><td>0.863143</td><td>41.110378</td><td>0.146230</td><td>00:14</td></tr><tr><td>9</td><td>0.793859</td><td>27.064442</td><td>0.172131</td><td>00:14</td></tr><tr><td>10</td><td>0.731066</td><td>34.274742</td><td>0.144590</td><td>00:14</td></tr><tr><td>11</td><td>0.671369</td><td>31.171619</td><td>0.154426</td><td>00:14</td></tr><tr><td>12</td><td>0.615195</td><td>30.803255</td><td>0.163770</td><td>00:14</td></tr><tr><td>13</td><td>0.547939</td><td>26.658131</td><td>0.189344</td><td>00:14</td></tr><tr><td>14</td><td>0.481447</td><td>26.380287</td><td>0.214098</td><td>00:14</td></tr><tr><td>15</td><td>0.433858</td><td>28.931728</td><td>0.209508</td><td>00:14</td></tr><tr><td>16</td><td>0.378617</td><td>27.295643</td><td>0.198197</td><td>00:14</td></tr><tr><td>17</td><td>0.329729</td><td>33.218849</td><td>0.184590</td><td>00:14</td></tr><tr><td>18</td><td>0.283835</td><td>27.555391</td><td>0.201639</td><td>00:14</td></tr><tr><td>19</td><td>0.243416</td><td>31.130014</td><td>0.193443</td><td>00:14</td></tr><tr><td>20</td><td>0.204182</td><td>36.628376</td><td>0.152131</td><td>00:14</td></tr><tr><td>21</td><td>0.176448</td><td>38.952644</td><td>0.239180</td><td>00:14</td></tr><tr><td>22</td><td>0.146498</td><td>29.975664</td><td>0.191148</td><td>00:14</td></tr><tr><td>23</td><td>0.119665</td><td>37.479397</td><td>0.189180</td><td>00:14</td></tr><tr><td>24</td><td>0.097462</td><td>44.415977</td><td>0.165410</td><td>00:14</td></tr><tr><td>25</td><td>0.081686</td><td>39.051807</td><td>0.184426</td><td>00:14</td></tr><tr><td>26</td><td>0.066466</td><td>45.857632</td><td>0.174590</td><td>00:14</td></tr><tr><td>27</td><td>0.055170</td><td>41.344227</td><td>0.184262</td><td>00:14</td></tr><tr><td>28</td><td>0.045337</td><td>42.596016</td><td>0.171475</td><td>00:14</td></tr><tr><td>29</td><td>0.036969</td><td>41.581741</td><td>0.154262</td><td>00:14</td></tr><tr><td>30</td><td>0.029434</td><td>41.368587</td><td>0.189508</td><td>00:14</td></tr><tr><td>31</td><td>0.023106</td><td>47.221645</td><td>0.175246</td><td>00:14</td></tr><tr><td>32</td><td>0.018318</td><td>47.735836</td><td>0.193770</td><td>00:14</td></tr><tr><td>33</td><td>0.014859</td><td>49.190544</td><td>0.181148</td><td>00:14</td></tr><tr><td>34</td><td>0.012456</td><td>58.477745</td><td>0.164426</td><td>00:14</td></tr><tr><td>35</td><td>0.010428</td><td>51.961948</td><td>0.163934</td><td>00:14</td></tr><tr><td>36</td><td>0.008412</td><td>52.189205</td><td>0.180492</td><td>00:14</td></tr><tr><td>37</td><td>0.006699</td><td>55.413208</td><td>0.164262</td><td>00:14</td></tr><tr><td>38</td><td>0.005446</td><td>54.323631</td><td>0.170656</td><td>00:14</td></tr><tr><td>39</td><td>0.004518</td><td>56.222153</td><td>0.168361</td><td>00:14</td></tr><tr><td>40</td><td>0.003832</td><td>55.961742</td><td>0.169672</td><td>00:14</td></tr><tr><td>41</td><td>0.003378</td><td>59.785606</td><td>0.166721</td><td>00:14</td></tr><tr><td>42</td><td>0.003055</td><td>57.147232</td><td>0.166230</td><td>00:14</td></tr><tr><td>43</td><td>0.002785</td><td>53.816788</td><td>0.171967</td><td>00:14</td></tr><tr><td>44</td><td>0.002561</td><td>55.254738</td><td>0.169836</td><td>00:14</td></tr><tr><td>45</td><td>0.002382</td><td>56.479465</td><td>0.169180</td><td>00:14</td></tr><tr><td>46</td><td>0.002265</td><td>54.878090</td><td>0.171639</td><td>00:14</td></tr><tr><td>47</td><td>0.002163</td><td>55.328842</td><td>0.170656</td><td>00:14</td></tr><tr><td>48</td><td>0.002109</td><td>55.461922</td><td>0.170984</td><td>00:14</td></tr><tr><td>49</td><td>0.002064</td><td>55.462627</td><td>0.171148</td><td>00:14</td></tr></tbody></table></div>

Better model found at epoch 0 with accuracy value: 0.1867213100194931.
Better model found at epoch 13 with accuracy value: 0.18934425711631775.
Better model found at epoch 14 with accuracy value: 0.21409836411476135.
Better model found at epoch 21 with accuracy value: 0.239180326461792.

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_bvp_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_bvp_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_bvp_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_bvp_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_bvp_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "synthetic_to_real",
  "native_modality": "bvp",
  "native_hz": 64,
  "channels": "BVP",
  "description": "BVP only",
  "input_shape_train_native_N_T_C": [
    30000,
    512,
    1
  ],
  "input_shape_test_native_N_T_C": [
    10063,
    512,
    1
  ],
  "input_shape_train_framework_N_C_T": [
    30000,
    1,
    512
  ],
  "input_shape_test_framework_N_C_T": [
    10063,
    1,
    512
  ],
  "epochs": 50,
  "best_epoch_by_val_accuracy": 22,
  "best_val_accuracy": 0.239180326461792,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_synthetic_to_real_bvp.pth",
  "used_saved_real_to_real_model": false,
  "training_reused_from_experiment": "",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.2713902414786843,
  "macro_precision": 0.1425801562524689,
  "macro_recall": 0.14316914189709384,
  "macro_f1": 0.09562954305892897,
  "weighted_precision": 0.1562473925018268,
  "weighted_recall": 0.2713902414786843,
  "weighted_f1": 0.17389927890321083,
  "balanced_accuracy": 0.14316914189709384
}

================================================================================
[tsai] real_plus_synthetic_to_real | bvp
================================================================================

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.831800</td><td>1.680551</td><td>0.369016</td><td>00:27</td></tr><tr><td>1</td><td>1.639064</td><td>1.471225</td><td>0.406721</td><td>00:27</td></tr><tr><td>2</td><td>1.476713</td><td>1.409224</td><td>0.435574</td><td>00:27</td></tr><tr><td>3</td><td>1.356923</td><td>1.372840</td><td>0.426885</td><td>00:27</td></tr><tr><td>4</td><td>1.260123</td><td>1.332214</td><td>0.480164</td><td>00:27</td></tr><tr><td>5</td><td>1.187305</td><td>1.415744</td><td>0.488525</td><td>00:27</td></tr><tr><td>6</td><td>1.097803</td><td>1.478413</td><td>0.483279</td><td>00:27</td></tr><tr><td>7</td><td>1.025403</td><td>1.489105</td><td>0.473115</td><td>00:27</td></tr><tr><td>8</td><td>0.983047</td><td>1.734709</td><td>0.351803</td><td>00:27</td></tr><tr><td>9</td><td>0.927288</td><td>1.541467</td><td>0.451967</td><td>00:28</td></tr><tr><td>10</td><td>0.897444</td><td>1.410869</td><td>0.508033</td><td>00:27</td></tr><tr><td>11</td><td>0.853062</td><td>1.950530</td><td>0.445738</td><td>00:27</td></tr><tr><td>12</td><td>0.811277</td><td>1.629535</td><td>0.465246</td><td>00:27</td></tr><tr><td>13</td><td>0.777041</td><td>1.905304</td><td>0.468033</td><td>00:27</td></tr><tr><td>14</td><td>0.740503</td><td>1.919738</td><td>0.471475</td><td>00:27</td></tr><tr><td>15</td><td>0.705752</td><td>1.958566</td><td>0.416721</td><td>00:27</td></tr><tr><td>16</td><td>0.674240</td><td>1.700309</td><td>0.465246</td><td>00:28</td></tr><tr><td>17</td><td>0.628773</td><td>1.803646</td><td>0.465574</td><td>00:27</td></tr><tr><td>18</td><td>0.590572</td><td>2.001596</td><td>0.472131</td><td>00:27</td></tr><tr><td>19</td><td>0.551242</td><td>1.898692</td><td>0.461311</td><td>00:27</td></tr><tr><td>20</td><td>0.509959</td><td>2.004558</td><td>0.462951</td><td>00:27</td></tr><tr><td>21</td><td>0.466754</td><td>1.624779</td><td>0.488525</td><td>00:27</td></tr><tr><td>22</td><td>0.423905</td><td>1.715942</td><td>0.484098</td><td>00:27</td></tr><tr><td>23</td><td>0.399829</td><td>1.855886</td><td>0.509016</td><td>00:28</td></tr><tr><td>24</td><td>0.346751</td><td>1.981091</td><td>0.473607</td><td>00:27</td></tr><tr><td>25</td><td>0.323355</td><td>2.619332</td><td>0.463279</td><td>00:27</td></tr><tr><td>26</td><td>0.293083</td><td>1.841237</td><td>0.510000</td><td>00:27</td></tr><tr><td>27</td><td>0.268827</td><td>2.104955</td><td>0.493279</td><td>00:27</td></tr><tr><td>28</td><td>0.240738</td><td>2.100485</td><td>0.500656</td><td>00:27</td></tr><tr><td>29</td><td>0.217133</td><td>2.487913</td><td>0.454918</td><td>00:27</td></tr><tr><td>30</td><td>0.198373</td><td>3.246374</td><td>0.454918</td><td>00:28</td></tr><tr><td>31</td><td>0.177789</td><td>2.436119</td><td>0.488525</td><td>00:27</td></tr><tr><td>32</td><td>0.158419</td><td>3.055389</td><td>0.461967</td><td>00:27</td></tr><tr><td>33</td><td>0.143584</td><td>2.528644</td><td>0.456230</td><td>00:24</td></tr><tr><td>34</td><td>0.129106</td><td>2.620808</td><td>0.483770</td><td>00:27</td></tr><tr><td>35</td><td>0.115504</td><td>2.756349</td><td>0.474098</td><td>00:27</td></tr><tr><td>36</td><td>0.101591</td><td>3.005231</td><td>0.457705</td><td>00:27</td></tr><tr><td>37</td><td>0.092400</td><td>2.515417</td><td>0.492787</td><td>00:27</td></tr><tr><td>38</td><td>0.080946</td><td>2.522899</td><td>0.488033</td><td>00:27</td></tr><tr><td>39</td><td>0.073591</td><td>2.555746</td><td>0.500164</td><td>00:27</td></tr><tr><td>40</td><td>0.064165</td><td>2.616895</td><td>0.489672</td><td>00:27</td></tr><tr><td>41</td><td>0.058883</td><td>2.527219</td><td>0.498525</td><td>00:27</td></tr><tr><td>42</td><td>0.053549</td><td>2.511700</td><td>0.492623</td><td>00:26</td></tr><tr><td>43</td><td>0.047371</td><td>2.451492</td><td>0.506721</td><td>00:28</td></tr><tr><td>44</td><td>0.043860</td><td>2.466499</td><td>0.503770</td><td>00:27</td></tr><tr><td>45</td><td>0.041007</td><td>2.523948</td><td>0.503443</td><td>00:28</td></tr><tr><td>46</td><td>0.039298</td><td>2.596967</td><td>0.500164</td><td>00:28</td></tr><tr><td>47</td><td>0.037769</td><td>2.572651</td><td>0.500820</td><td>00:28</td></tr><tr><td>48</td><td>0.036582</td><td>2.547670</td><td>0.501148</td><td>00:28</td></tr><tr><td>49</td><td>0.036121</td><td>2.533355</td><td>0.500820</td><td>00:28</td></tr></tbody></table></div>

Better model found at epoch 0 with accuracy value: 0.3690163791179657.
Better model found at epoch 1 with accuracy value: 0.4067213237285614.
Better model found at epoch 2 with accuracy value: 0.4355737566947937.
Better model found at epoch 4 with accuracy value: 0.48016393184661865.
Better model found at epoch 5 with accuracy value: 0.48852458596229553.
Better model found at epoch 10 with accuracy value: 0.5080327987670898.
Better model found at epoch 23 with accuracy value: 0.5090163946151733.
Better model found at epoch 26 with accuracy value: 0.5099999904632568.

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_bvp_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_bvp_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_bvp_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_bvp_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_bvp_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_plus_synthetic_to_real",
  "native_modality": "bvp",
  "native_hz": 64,
  "channels": "BVP",
  "description": "BVP only",
  "input_shape_train_native_N_T_C": [
    60762,
    512,
    1
  ],
  "input_shape_test_native_N_T_C": [
    10063,
    512,
    1
  ],
  "input_shape_train_framework_N_C_T": [
    60762,
    1,
    512
  ],
  "input_shape_test_framework_N_C_T": [
    10063,
    1,
    512
  ],
  "epochs": 50,
  "best_epoch_by_val_accuracy": 27,
  "best_val_accuracy": 0.5099999904632568,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_plus_synthetic_to_real_bvp.pth",
  "used_saved_real_to_real_model": false,
  "training_reused_from_experiment": "",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.4551326642154427,
  "macro_precision": 0.5030774889845699,
  "macro_recall": 0.5594621007172424,
  "macro_f1": 0.4952681985524411,
  "weighted_precision": 0.4846143002412084,
  "weighted_recall": 0.4551326642154427,
  "weighted_f1": 0.43628589567614334,
  "balanced_accuracy": 0.5594621007172424
}

================================================================================
[tsai] real_to_real | eda
================================================================================
Reusing saved tsai Real->Real metrics.

================================================================================
[tsai] real_to_synthetic | eda
================================================================================
Copied external tsai model into current output folder: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_to_real_eda.pth
Loading tsai Real->Real model: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_to_real_eda.pth

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_eda_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_eda_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_eda_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_eda_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_eda_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_to_synthetic",
  "native_modality": "eda",
  "native_hz": 4,
  "channels": "EDA",
  "description": "EDA only",
  "input_shape_train_native_N_T_C": [
    30762,
    32,
    1
  ],
  "input_shape_test_native_N_T_C": [
    9000,
    32,
    1
  ],
  "input_shape_train_framework_N_C_T": [
    30762,
    1,
    32
  ],
  "input_shape_test_framework_N_C_T": [
    9000,
    1,
    32
  ],
  "epochs": 0,
  "best_epoch_by_val_accuracy": 49,
  "best_val_accuracy": 0.5367212891578674,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_to_real_eda.pth",
  "used_saved_real_to_real_model": true,
  "training_reused_from_experiment": "real_to_real",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.13133333333333333,
  "macro_precision": 0.08742653548776806,
  "macro_recall": 0.12765068387033335,
  "macro_f1": 0.07883186149466165,
  "weighted_precision": 0.1356630152667355,
  "weighted_recall": 0.13133333333333333,
  "weighted_f1": 0.09566497814900622,
  "balanced_accuracy": 0.12765068387033335
}

================================================================================
[tsai] synthetic_to_real | eda
================================================================================

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.575168</td><td>5.090879</td><td>0.293115</td><td>00:24</td></tr><tr><td>1</td><td>1.379854</td><td>12.284454</td><td>0.252787</td><td>00:24</td></tr><tr><td>2</td><td>1.243801</td><td>8.205637</td><td>0.309016</td><td>00:24</td></tr><tr><td>3</td><td>1.128425</td><td>7.998867</td><td>0.218361</td><td>00:24</td></tr><tr><td>4</td><td>1.024716</td><td>10.408451</td><td>0.192951</td><td>00:24</td></tr><tr><td>5</td><td>0.941147</td><td>8.877580</td><td>0.266721</td><td>00:24</td></tr><tr><td>6</td><td>0.876918</td><td>11.398203</td><td>0.275738</td><td>00:35</td></tr><tr><td>7</td><td>0.830737</td><td>15.083985</td><td>0.252295</td><td>00:35</td></tr><tr><td>8</td><td>0.788187</td><td>14.916616</td><td>0.252623</td><td>00:35</td></tr><tr><td>9</td><td>0.757710</td><td>16.014278</td><td>0.250492</td><td>00:35</td></tr><tr><td>10</td><td>0.726010</td><td>18.075289</td><td>0.278689</td><td>00:35</td></tr><tr><td>11</td><td>0.698160</td><td>10.314461</td><td>0.301803</td><td>00:34</td></tr><tr><td>12</td><td>0.663367</td><td>35.440517</td><td>0.250984</td><td>00:35</td></tr><tr><td>13</td><td>0.639482</td><td>19.737476</td><td>0.299016</td><td>00:35</td></tr><tr><td>14</td><td>0.611520</td><td>20.449583</td><td>0.297049</td><td>00:35</td></tr><tr><td>15</td><td>0.599176</td><td>12.838734</td><td>0.348689</td><td>00:35</td></tr><tr><td>16</td><td>0.580017</td><td>18.609734</td><td>0.295738</td><td>00:35</td></tr><tr><td>17</td><td>0.555893</td><td>29.718580</td><td>0.268033</td><td>00:34</td></tr><tr><td>18</td><td>0.538011</td><td>33.646748</td><td>0.242951</td><td>00:35</td></tr><tr><td>19</td><td>0.522521</td><td>35.902794</td><td>0.247377</td><td>00:35</td></tr><tr><td>20</td><td>0.506197</td><td>24.418020</td><td>0.297377</td><td>00:35</td></tr><tr><td>21</td><td>0.490717</td><td>27.439995</td><td>0.291311</td><td>00:35</td></tr><tr><td>22</td><td>0.475404</td><td>22.052296</td><td>0.289344</td><td>00:35</td></tr><tr><td>23</td><td>0.465983</td><td>25.956697</td><td>0.296066</td><td>00:35</td></tr><tr><td>24</td><td>0.450217</td><td>23.014727</td><td>0.285574</td><td>00:35</td></tr><tr><td>25</td><td>0.433529</td><td>31.266037</td><td>0.279016</td><td>00:35</td></tr><tr><td>26</td><td>0.415474</td><td>33.971687</td><td>0.262295</td><td>00:35</td></tr><tr><td>27</td><td>0.397761</td><td>42.364323</td><td>0.246230</td><td>00:35</td></tr><tr><td>28</td><td>0.379313</td><td>33.005424</td><td>0.283934</td><td>00:35</td></tr><tr><td>29</td><td>0.355806</td><td>34.179581</td><td>0.279836</td><td>00:17</td></tr><tr><td>30</td><td>0.335171</td><td>31.209322</td><td>0.284262</td><td>00:11</td></tr><tr><td>31</td><td>0.312028</td><td>34.081139</td><td>0.276721</td><td>00:11</td></tr><tr><td>32</td><td>0.288532</td><td>41.320099</td><td>0.248525</td><td>00:11</td></tr><tr><td>33</td><td>0.260110</td><td>30.247643</td><td>0.294918</td><td>00:11</td></tr><tr><td>34</td><td>0.230647</td><td>31.978514</td><td>0.286885</td><td>00:11</td></tr><tr><td>35</td><td>0.202857</td><td>29.953747</td><td>0.288197</td><td>00:11</td></tr><tr><td>36</td><td>0.178602</td><td>30.230095</td><td>0.277705</td><td>00:11</td></tr><tr><td>37</td><td>0.154465</td><td>30.721825</td><td>0.292951</td><td>00:11</td></tr><tr><td>38</td><td>0.133315</td><td>29.544075</td><td>0.290000</td><td>00:11</td></tr><tr><td>39</td><td>0.116483</td><td>27.772581</td><td>0.293115</td><td>00:11</td></tr><tr><td>40</td><td>0.099708</td><td>29.575207</td><td>0.287049</td><td>00:11</td></tr><tr><td>41</td><td>0.087288</td><td>31.582653</td><td>0.279836</td><td>00:11</td></tr><tr><td>42</td><td>0.076140</td><td>31.915220</td><td>0.277705</td><td>00:11</td></tr><tr><td>43</td><td>0.066467</td><td>30.622826</td><td>0.284098</td><td>00:11</td></tr><tr><td>44</td><td>0.058989</td><td>30.567019</td><td>0.282131</td><td>00:11</td></tr><tr><td>45</td><td>0.052671</td><td>31.149908</td><td>0.279180</td><td>00:11</td></tr><tr><td>46</td><td>0.048960</td><td>30.420141</td><td>0.280328</td><td>00:11</td></tr><tr><td>47</td><td>0.044853</td><td>30.172474</td><td>0.282787</td><td>00:11</td></tr><tr><td>48</td><td>0.043271</td><td>30.642195</td><td>0.282787</td><td>00:11</td></tr><tr><td>49</td><td>0.041720</td><td>30.243370</td><td>0.283279</td><td>00:11</td></tr></tbody></table></div>

Better model found at epoch 0 with accuracy value: 0.2931147515773773.
Better model found at epoch 2 with accuracy value: 0.3090164065361023.
Better model found at epoch 15 with accuracy value: 0.3486885130405426.

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_eda_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_eda_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_eda_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_eda_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_eda_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "synthetic_to_real",
  "native_modality": "eda",
  "native_hz": 4,
  "channels": "EDA",
  "description": "EDA only",
  "input_shape_train_native_N_T_C": [
    30000,
    32,
    1
  ],
  "input_shape_test_native_N_T_C": [
    10063,
    32,
    1
  ],
  "input_shape_train_framework_N_C_T": [
    30000,
    1,
    32
  ],
  "input_shape_test_framework_N_C_T": [
    10063,
    1,
    32
  ],
  "epochs": 50,
  "best_epoch_by_val_accuracy": 16,
  "best_val_accuracy": 0.3486885130405426,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_synthetic_to_real_eda.pth",
  "used_saved_real_to_real_model": false,
  "training_reused_from_experiment": "",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.3318095995230051,
  "macro_precision": 0.13156435997388807,
  "macro_recall": 0.226276194474752,
  "macro_f1": 0.16105319791506403,
  "weighted_precision": 0.18182875279345614,
  "weighted_recall": 0.3318095995230051,
  "weighted_f1": 0.22889555034370324,
  "balanced_accuracy": 0.226276194474752
}

================================================================================
[tsai] real_plus_synthetic_to_real | eda
================================================================================

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.701225</td><td>1.673905</td><td>0.359344</td><td>00:23</td></tr><tr><td>1</td><td>1.523260</td><td>1.527710</td><td>0.450164</td><td>00:23</td></tr><tr><td>2</td><td>1.414169</td><td>1.450949</td><td>0.452131</td><td>00:23</td></tr><tr><td>3</td><td>1.343522</td><td>1.546943</td><td>0.377049</td><td>00:23</td></tr><tr><td>4</td><td>1.295184</td><td>1.585888</td><td>0.443115</td><td>00:23</td></tr><tr><td>5</td><td>1.261947</td><td>1.928068</td><td>0.286230</td><td>00:23</td></tr><tr><td>6</td><td>1.236506</td><td>1.543829</td><td>0.387705</td><td>00:23</td></tr><tr><td>7</td><td>1.204113</td><td>2.216068</td><td>0.307869</td><td>00:23</td></tr><tr><td>8</td><td>1.179386</td><td>2.196841</td><td>0.336885</td><td>00:23</td></tr><tr><td>9</td><td>1.172063</td><td>1.555246</td><td>0.466229</td><td>00:23</td></tr><tr><td>10</td><td>1.154554</td><td>1.923384</td><td>0.408689</td><td>00:23</td></tr><tr><td>11</td><td>1.149448</td><td>1.621729</td><td>0.424098</td><td>00:23</td></tr><tr><td>12</td><td>1.122635</td><td>3.037106</td><td>0.274590</td><td>00:23</td></tr><tr><td>13</td><td>1.097653</td><td>3.038284</td><td>0.236885</td><td>00:23</td></tr><tr><td>14</td><td>1.079223</td><td>1.761765</td><td>0.456393</td><td>00:23</td></tr><tr><td>15</td><td>1.050622</td><td>2.020649</td><td>0.348852</td><td>00:23</td></tr><tr><td>16</td><td>1.033913</td><td>2.541841</td><td>0.301967</td><td>00:23</td></tr><tr><td>17</td><td>1.020850</td><td>3.671674</td><td>0.213934</td><td>00:23</td></tr><tr><td>18</td><td>0.989391</td><td>7.035371</td><td>0.093443</td><td>00:23</td></tr><tr><td>19</td><td>1.002720</td><td>3.116152</td><td>0.347377</td><td>00:23</td></tr><tr><td>20</td><td>0.980955</td><td>4.367702</td><td>0.206885</td><td>00:23</td></tr><tr><td>21</td><td>0.957683</td><td>2.857634</td><td>0.204426</td><td>00:23</td></tr><tr><td>22</td><td>0.941473</td><td>5.816038</td><td>0.380984</td><td>00:23</td></tr><tr><td>23</td><td>0.932748</td><td>4.412484</td><td>0.174426</td><td>00:23</td></tr><tr><td>24</td><td>0.915027</td><td>4.043206</td><td>0.133443</td><td>00:23</td></tr><tr><td>25</td><td>0.900329</td><td>3.841989</td><td>0.470328</td><td>00:23</td></tr><tr><td>26</td><td>0.891021</td><td>4.181653</td><td>0.276393</td><td>00:23</td></tr><tr><td>27</td><td>0.874237</td><td>2.936762</td><td>0.225902</td><td>00:23</td></tr><tr><td>28</td><td>0.865243</td><td>3.200210</td><td>0.375902</td><td>00:23</td></tr><tr><td>29</td><td>0.860578</td><td>1.409654</td><td>0.457541</td><td>00:23</td></tr><tr><td>30</td><td>0.838515</td><td>2.401511</td><td>0.509836</td><td>00:23</td></tr><tr><td>31</td><td>0.828258</td><td>3.524008</td><td>0.426721</td><td>00:23</td></tr><tr><td>32</td><td>0.817536</td><td>2.562994</td><td>0.506885</td><td>00:23</td></tr><tr><td>33</td><td>0.805735</td><td>3.996898</td><td>0.333607</td><td>00:23</td></tr><tr><td>34</td><td>0.793129</td><td>1.844349</td><td>0.420328</td><td>00:23</td></tr><tr><td>35</td><td>0.780441</td><td>6.514132</td><td>0.349836</td><td>00:23</td></tr><tr><td>36</td><td>0.769062</td><td>2.797346</td><td>0.475082</td><td>00:23</td></tr><tr><td>37</td><td>0.762172</td><td>2.262672</td><td>0.347049</td><td>00:23</td></tr><tr><td>38</td><td>0.751475</td><td>2.970659</td><td>0.503607</td><td>00:23</td></tr><tr><td>39</td><td>0.740608</td><td>2.616436</td><td>0.505902</td><td>00:23</td></tr><tr><td>40</td><td>0.732544</td><td>2.569798</td><td>0.273607</td><td>00:23</td></tr><tr><td>41</td><td>0.721522</td><td>2.686913</td><td>0.267213</td><td>00:23</td></tr><tr><td>42</td><td>0.713323</td><td>1.828443</td><td>0.447377</td><td>00:23</td></tr><tr><td>43</td><td>0.704008</td><td>2.875740</td><td>0.255738</td><td>00:23</td></tr><tr><td>44</td><td>0.696648</td><td>1.567475</td><td>0.510984</td><td>00:23</td></tr><tr><td>45</td><td>0.691400</td><td>1.462388</td><td>0.546393</td><td>00:23</td></tr><tr><td>46</td><td>0.687160</td><td>1.609541</td><td>0.482295</td><td>00:23</td></tr><tr><td>47</td><td>0.682593</td><td>1.612581</td><td>0.509836</td><td>00:23</td></tr><tr><td>48</td><td>0.681936</td><td>1.567557</td><td>0.513607</td><td>00:23</td></tr><tr><td>49</td><td>0.680401</td><td>1.539352</td><td>0.537705</td><td>00:23</td></tr></tbody></table></div>

Better model found at epoch 0 with accuracy value: 0.3593442738056183.
Better model found at epoch 1 with accuracy value: 0.45016393065452576.
Better model found at epoch 2 with accuracy value: 0.45213115215301514.
Better model found at epoch 9 with accuracy value: 0.46622949838638306.
Better model found at epoch 25 with accuracy value: 0.47032785415649414.
Better model found at epoch 30 with accuracy value: 0.5098360776901245.
Better model found at epoch 44 with accuracy value: 0.5109835863113403.
Better model found at epoch 45 with accuracy value: 0.5463934540748596.

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_eda_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_eda_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_eda_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_eda_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_eda_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_plus_synthetic_to_real",
  "native_modality": "eda",
  "native_hz": 4,
  "channels": "EDA",
  "description": "EDA only",
  "input_shape_train_native_N_T_C": [
    60762,
    32,
    1
  ],
  "input_shape_test_native_N_T_C": [
    10063,
    32,
    1
  ],
  "input_shape_train_framework_N_C_T": [
    60762,
    1,
    32
  ],
  "input_shape_test_framework_N_C_T": [
    10063,
    1,
    32
  ],
  "epochs": 50,
  "best_epoch_by_val_accuracy": 46,
  "best_val_accuracy": 0.5463934540748596,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_plus_synthetic_to_real_eda.pth",
  "used_saved_real_to_real_model": false,
  "training_reused_from_experiment": "",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.32694027625956473,
  "macro_precision": 0.330769181692103,
  "macro_recall": 0.30935378526811924,
  "macro_f1": 0.2636468429312876,
  "weighted_precision": 0.34260615457105187,
  "weighted_recall": 0.32694027625956473,
  "weighted_f1": 0.2963715254980806,
  "balanced_accuracy": 0.30935378526811924
}

================================================================================
[tsai] real_to_real | temp
================================================================================
Reusing saved tsai Real->Real metrics.

================================================================================
[tsai] real_to_synthetic | temp
================================================================================
Copied external tsai model into current output folder: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_to_real_temp.pth
Loading tsai Real->Real model: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_to_real_temp.pth

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_temp_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_temp_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_temp_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_temp_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_temp_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_to_synthetic",
  "native_modality": "temp",
  "native_hz": 4,
  "channels": "TEMP",
  "description": "TEMP only",
  "input_shape_train_native_N_T_C": [
    30762,
    32,
    1
  ],
  "input_shape_test_native_N_T_C": [
    9000,
    32,
    1
  ],
  "input_shape_train_framework_N_C_T": [
    30762,
    1,
    32
  ],
  "input_shape_test_framework_N_C_T": [
    9000,
    1,
    32
  ],
  "epochs": 0,
  "best_epoch_by_val_accuracy": 25,
  "best_val_accuracy": 0.3852458894252777,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_to_real_temp.pth",
  "used_saved_real_to_real_model": true,
  "training_reused_from_experiment": "real_to_real",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.28955555555555557,
  "macro_precision": 0.12007447581075459,
  "macro_recall": 0.1815490489751177,
  "macro_f1": 0.14250985135470057,
  "weighted_precision": 0.17305933971485063,
  "weighted_recall": 0.28955555555555557,
  "weighted_f1": 0.214798108683569,
  "balanced_accuracy": 0.1815490489751177
}

================================================================================
[tsai] synthetic_to_real | temp
================================================================================

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.656585</td><td>4.596375</td><td>0.145902</td><td>00:11</td></tr><tr><td>1</td><td>1.448696</td><td>7.588015</td><td>0.164098</td><td>00:11</td></tr><tr><td>2</td><td>1.284701</td><td>9.534206</td><td>0.311148</td><td>00:11</td></tr><tr><td>3</td><td>1.149341</td><td>16.801437</td><td>0.298852</td><td>00:11</td></tr><tr><td>4</td><td>1.049119</td><td>14.023210</td><td>0.311639</td><td>00:11</td></tr><tr><td>5</td><td>0.967878</td><td>19.789747</td><td>0.303279</td><td>00:11</td></tr><tr><td>6</td><td>0.891763</td><td>24.338737</td><td>0.308033</td><td>00:11</td></tr><tr><td>7</td><td>0.825211</td><td>14.789790</td><td>0.308197</td><td>00:11</td></tr><tr><td>8</td><td>0.765630</td><td>21.300373</td><td>0.306393</td><td>00:11</td></tr><tr><td>9</td><td>0.717743</td><td>20.382536</td><td>0.312295</td><td>00:11</td></tr><tr><td>10</td><td>0.670045</td><td>19.299137</td><td>0.304262</td><td>00:11</td></tr><tr><td>11</td><td>0.633427</td><td>30.382822</td><td>0.306885</td><td>00:11</td></tr><tr><td>12</td><td>0.612061</td><td>20.776773</td><td>0.294754</td><td>00:11</td></tr><tr><td>13</td><td>0.587756</td><td>24.735867</td><td>0.294426</td><td>00:11</td></tr><tr><td>14</td><td>0.560779</td><td>21.092390</td><td>0.221967</td><td>00:11</td></tr><tr><td>15</td><td>0.538562</td><td>26.204111</td><td>0.304098</td><td>00:11</td></tr><tr><td>16</td><td>0.521282</td><td>25.959013</td><td>0.132951</td><td>00:11</td></tr><tr><td>17</td><td>0.502071</td><td>21.087841</td><td>0.308525</td><td>00:11</td></tr><tr><td>18</td><td>0.483211</td><td>22.064974</td><td>0.307377</td><td>00:11</td></tr><tr><td>19</td><td>0.465130</td><td>25.543123</td><td>0.124918</td><td>00:11</td></tr><tr><td>20</td><td>0.443208</td><td>24.109493</td><td>0.303607</td><td>00:11</td></tr><tr><td>21</td><td>0.432613</td><td>25.541151</td><td>0.159344</td><td>00:11</td></tr><tr><td>22</td><td>0.411749</td><td>21.769001</td><td>0.280492</td><td>00:11</td></tr><tr><td>23</td><td>0.389074</td><td>20.103525</td><td>0.168689</td><td>00:11</td></tr><tr><td>24</td><td>0.364676</td><td>37.695019</td><td>0.139508</td><td>00:11</td></tr><tr><td>25</td><td>0.335882</td><td>24.645430</td><td>0.137377</td><td>00:11</td></tr><tr><td>26</td><td>0.303911</td><td>19.558323</td><td>0.241148</td><td>00:11</td></tr><tr><td>27</td><td>0.271172</td><td>21.795948</td><td>0.168361</td><td>00:11</td></tr><tr><td>28</td><td>0.238385</td><td>21.631762</td><td>0.105082</td><td>00:11</td></tr><tr><td>29</td><td>0.211956</td><td>20.706619</td><td>0.131639</td><td>00:11</td></tr><tr><td>30</td><td>0.183118</td><td>21.067785</td><td>0.307869</td><td>00:11</td></tr><tr><td>31</td><td>0.161494</td><td>24.675234</td><td>0.134262</td><td>00:11</td></tr><tr><td>32</td><td>0.138483</td><td>24.599241</td><td>0.304262</td><td>00:11</td></tr><tr><td>33</td><td>0.116259</td><td>21.985489</td><td>0.302623</td><td>00:11</td></tr><tr><td>34</td><td>0.095940</td><td>22.088552</td><td>0.303115</td><td>00:11</td></tr><tr><td>35</td><td>0.080813</td><td>21.561127</td><td>0.307213</td><td>00:11</td></tr><tr><td>36</td><td>0.069112</td><td>24.492350</td><td>0.305082</td><td>00:11</td></tr><tr><td>37</td><td>0.059379</td><td>23.728348</td><td>0.304918</td><td>00:11</td></tr><tr><td>38</td><td>0.051021</td><td>22.227577</td><td>0.304426</td><td>00:11</td></tr><tr><td>39</td><td>0.042550</td><td>20.368898</td><td>0.307213</td><td>00:11</td></tr><tr><td>40</td><td>0.035711</td><td>23.166578</td><td>0.308525</td><td>00:11</td></tr><tr><td>41</td><td>0.031302</td><td>22.127218</td><td>0.308361</td><td>00:11</td></tr><tr><td>42</td><td>0.027047</td><td>20.900892</td><td>0.309672</td><td>00:11</td></tr><tr><td>43</td><td>0.022701</td><td>21.272964</td><td>0.307213</td><td>00:11</td></tr><tr><td>44</td><td>0.019295</td><td>24.321806</td><td>0.307049</td><td>00:11</td></tr><tr><td>45</td><td>0.016965</td><td>22.576204</td><td>0.306721</td><td>00:11</td></tr><tr><td>46</td><td>0.015251</td><td>22.219482</td><td>0.307377</td><td>00:11</td></tr><tr><td>47</td><td>0.013891</td><td>22.789362</td><td>0.307869</td><td>00:11</td></tr><tr><td>48</td><td>0.013028</td><td>22.818998</td><td>0.307377</td><td>00:11</td></tr><tr><td>49</td><td>0.012294</td><td>22.076353</td><td>0.307541</td><td>00:11</td></tr></tbody></table></div>

Better model found at epoch 0 with accuracy value: 0.1459016352891922.
Better model found at epoch 1 with accuracy value: 0.1640983670949936.
Better model found at epoch 2 with accuracy value: 0.311147540807724.
Better model found at epoch 4 with accuracy value: 0.31163933873176575.
Better model found at epoch 9 with accuracy value: 0.3122950792312622.

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_temp_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_temp_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_temp_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_temp_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_temp_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "synthetic_to_real",
  "native_modality": "temp",
  "native_hz": 4,
  "channels": "TEMP",
  "description": "TEMP only",
  "input_shape_train_native_N_T_C": [
    30000,
    32,
    1
  ],
  "input_shape_test_native_N_T_C": [
    10063,
    32,
    1
  ],
  "input_shape_train_framework_N_C_T": [
    30000,
    1,
    32
  ],
  "input_shape_test_framework_N_C_T": [
    10063,
    1,
    32
  ],
  "epochs": 50,
  "best_epoch_by_val_accuracy": 10,
  "best_val_accuracy": 0.3122950792312622,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_synthetic_to_real_temp.pth",
  "used_saved_real_to_real_model": false,
  "training_reused_from_experiment": "",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.29345125708039355,
  "macro_precision": 0.18554554979531662,
  "macro_recall": 0.2059954604183004,
  "macro_f1": 0.11482520675409509,
  "weighted_precision": 0.29780368852730305,
  "weighted_recall": 0.29345125708039355,
  "weighted_f1": 0.21675207259236584,
  "balanced_accuracy": 0.2059954604183004
}

================================================================================
[tsai] real_plus_synthetic_to_real | temp
================================================================================

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.694794</td><td>1.663204</td><td>0.360164</td><td>00:22</td></tr><tr><td>1</td><td>1.548383</td><td>1.654731</td><td>0.355410</td><td>00:22</td></tr><tr><td>2</td><td>1.436595</td><td>1.683403</td><td>0.327541</td><td>00:22</td></tr><tr><td>3</td><td>1.350680</td><td>1.643969</td><td>0.357049</td><td>00:22</td></tr><tr><td>4</td><td>1.293040</td><td>1.689260</td><td>0.317377</td><td>00:22</td></tr><tr><td>5</td><td>1.250274</td><td>1.702081</td><td>0.296557</td><td>00:22</td></tr><tr><td>6</td><td>1.210407</td><td>1.938787</td><td>0.292787</td><td>00:22</td></tr><tr><td>7</td><td>1.196405</td><td>1.749177</td><td>0.273443</td><td>00:22</td></tr><tr><td>8</td><td>1.184599</td><td>1.706822</td><td>0.358852</td><td>00:22</td></tr><tr><td>9</td><td>1.156325</td><td>2.034524</td><td>0.333770</td><td>00:22</td></tr><tr><td>10</td><td>1.157495</td><td>1.670809</td><td>0.338361</td><td>00:22</td></tr><tr><td>11</td><td>1.141584</td><td>1.721073</td><td>0.306721</td><td>00:22</td></tr><tr><td>12</td><td>1.127262</td><td>1.868950</td><td>0.388033</td><td>00:22</td></tr><tr><td>13</td><td>1.119594</td><td>1.704336</td><td>0.347049</td><td>00:22</td></tr><tr><td>14</td><td>1.112274</td><td>1.808205</td><td>0.356721</td><td>00:22</td></tr><tr><td>15</td><td>1.097295</td><td>1.813298</td><td>0.363934</td><td>00:22</td></tr><tr><td>16</td><td>1.090508</td><td>1.782619</td><td>0.264918</td><td>00:22</td></tr><tr><td>17</td><td>1.082992</td><td>1.776071</td><td>0.267705</td><td>00:22</td></tr><tr><td>18</td><td>1.073807</td><td>1.795854</td><td>0.346393</td><td>00:22</td></tr><tr><td>19</td><td>1.067692</td><td>1.753876</td><td>0.337213</td><td>00:22</td></tr><tr><td>20</td><td>1.057351</td><td>1.686773</td><td>0.337049</td><td>00:22</td></tr><tr><td>21</td><td>1.046551</td><td>1.842493</td><td>0.336066</td><td>00:22</td></tr><tr><td>22</td><td>1.035451</td><td>1.821769</td><td>0.315574</td><td>00:22</td></tr><tr><td>23</td><td>1.033814</td><td>1.709269</td><td>0.326230</td><td>00:22</td></tr><tr><td>24</td><td>1.026251</td><td>1.756447</td><td>0.331639</td><td>00:22</td></tr><tr><td>25</td><td>1.013921</td><td>1.823244</td><td>0.265574</td><td>00:22</td></tr><tr><td>26</td><td>1.008922</td><td>1.686442</td><td>0.360492</td><td>00:22</td></tr><tr><td>27</td><td>0.998664</td><td>1.804054</td><td>0.387869</td><td>00:22</td></tr><tr><td>28</td><td>0.992760</td><td>1.848027</td><td>0.326393</td><td>00:22</td></tr><tr><td>29</td><td>0.981173</td><td>1.747593</td><td>0.297049</td><td>00:22</td></tr><tr><td>30</td><td>0.972180</td><td>1.849594</td><td>0.294426</td><td>00:22</td></tr><tr><td>31</td><td>0.957716</td><td>1.662281</td><td>0.335246</td><td>00:22</td></tr><tr><td>32</td><td>0.942507</td><td>1.762388</td><td>0.322951</td><td>00:22</td></tr><tr><td>33</td><td>0.929165</td><td>1.941478</td><td>0.296885</td><td>00:22</td></tr><tr><td>34</td><td>0.914786</td><td>1.886317</td><td>0.296557</td><td>00:22</td></tr><tr><td>35</td><td>0.894884</td><td>1.919308</td><td>0.309344</td><td>00:22</td></tr><tr><td>36</td><td>0.877169</td><td>2.041815</td><td>0.269508</td><td>00:22</td></tr><tr><td>37</td><td>0.858667</td><td>2.134003</td><td>0.301967</td><td>00:22</td></tr><tr><td>38</td><td>0.845446</td><td>2.208771</td><td>0.284426</td><td>00:22</td></tr><tr><td>39</td><td>0.827591</td><td>2.321071</td><td>0.284426</td><td>00:22</td></tr><tr><td>40</td><td>0.814361</td><td>2.200397</td><td>0.281311</td><td>00:22</td></tr><tr><td>41</td><td>0.806908</td><td>2.079960</td><td>0.335246</td><td>00:22</td></tr><tr><td>42</td><td>0.795161</td><td>2.264867</td><td>0.313115</td><td>00:22</td></tr><tr><td>43</td><td>0.782390</td><td>2.167018</td><td>0.312951</td><td>00:22</td></tr><tr><td>44</td><td>0.773251</td><td>2.229236</td><td>0.330492</td><td>00:22</td></tr><tr><td>45</td><td>0.766536</td><td>2.215628</td><td>0.336885</td><td>00:22</td></tr><tr><td>46</td><td>0.761448</td><td>2.260066</td><td>0.300820</td><td>00:22</td></tr><tr><td>47</td><td>0.757285</td><td>2.228690</td><td>0.303279</td><td>00:22</td></tr><tr><td>48</td><td>0.755591</td><td>2.236698</td><td>0.310492</td><td>00:22</td></tr><tr><td>49</td><td>0.753264</td><td>2.239146</td><td>0.301803</td><td>00:22</td></tr></tbody></table></div>

Better model found at epoch 0 with accuracy value: 0.36016392707824707.
Better model found at epoch 12 with accuracy value: 0.38803279399871826.

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_temp_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_temp_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_temp_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_temp_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_temp_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_plus_synthetic_to_real",
  "native_modality": "temp",
  "native_hz": 4,
  "channels": "TEMP",
  "description": "TEMP only",
  "input_shape_train_native_N_T_C": [
    60762,
    32,
    1
  ],
  "input_shape_test_native_N_T_C": [
    10063,
    32,
    1
  ],
  "input_shape_train_framework_N_C_T": [
    60762,
    1,
    32
  ],
  "input_shape_test_framework_N_C_T": [
    10063,
    1,
    32
  ],
  "epochs": 50,
  "best_epoch_by_val_accuracy": 13,
  "best_val_accuracy": 0.38803279399871826,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_plus_synthetic_to_real_temp.pth",
  "used_saved_real_to_real_model": false,
  "training_reused_from_experiment": "",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.2576766371857299,
  "macro_precision": 0.139969520205561,
  "macro_recall": 0.2453597045552206,
  "macro_f1": 0.13359749895453066,
  "weighted_precision": 0.2209326915360298,
  "weighted_recall": 0.2576766371857299,
  "weighted_f1": 0.20615254997115387,
  "balanced_accuracy": 0.2453597045552206
}

================================================================================
[tsai] real_to_real | fused
================================================================================
Reusing saved tsai Real->Real metrics.

================================================================================
[tsai] real_to_synthetic | fused
================================================================================
Copied external tsai model into current output folder: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_to_real_fused.pth
Loading tsai Real->Real model: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_to_real_fused.pth

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_fused_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_fused_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_fused_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_fused_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_to_synthetic_fused_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_to_synthetic",
  "native_modality": "fused",
  "native_hz": 64,
  "channels": "ACC_x,ACC_y,ACC_z,BVP,EDA,TEMP",
  "description": "ACC+BVP+EDA+TEMP fused",
  "input_shape_train_native_N_T_C": [
    30762,
    512,
    6
  ],
  "input_shape_test_native_N_T_C": [
    9000,
    512,
    6
  ],
  "input_shape_train_framework_N_C_T": [
    30762,
    6,
    512
  ],
  "input_shape_test_framework_N_C_T": [
    9000,
    6,
    512
  ],
  "epochs": 0,
  "best_epoch_by_val_accuracy": 7,
  "best_val_accuracy": 0.7673770785331726,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_to_real_fused.pth",
  "used_saved_real_to_real_model": true,
  "training_reused_from_experiment": "real_to_real",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.27655555555555555,
  "macro_precision": 0.044220925952872095,
  "macro_recall": 0.12529976019184652,
  "macro_f1": 0.05478618837715965,
  "weighted_precision": 0.08009617976203043,
  "weighted_recall": 0.27655555555555555,
  "weighted_f1": 0.12009241503549452,
  "balanced_accuracy": 0.12529976019184652
}

================================================================================
[tsai] synthetic_to_real | fused
================================================================================

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.379811</td><td>1.857014</td><td>0.512623</td><td>00:06</td></tr><tr><td>1</td><td>0.922251</td><td>4.019769</td><td>0.566393</td><td>00:06</td></tr><tr><td>2</td><td>0.611725</td><td>3.079664</td><td>0.576557</td><td>00:06</td></tr><tr><td>3</td><td>0.397925</td><td>2.641077</td><td>0.576885</td><td>00:06</td></tr><tr><td>4</td><td>0.253513</td><td>2.985929</td><td>0.596557</td><td>00:06</td></tr><tr><td>5</td><td>0.162655</td><td>3.705133</td><td>0.551639</td><td>00:06</td></tr><tr><td>6</td><td>0.106034</td><td>6.494889</td><td>0.483934</td><td>00:06</td></tr><tr><td>7</td><td>0.073867</td><td>7.655079</td><td>0.457705</td><td>00:06</td></tr><tr><td>8</td><td>0.051627</td><td>8.187490</td><td>0.460656</td><td>00:06</td></tr><tr><td>9</td><td>0.036334</td><td>7.613263</td><td>0.506721</td><td>00:06</td></tr><tr><td>10</td><td>0.025209</td><td>18.874140</td><td>0.423770</td><td>00:06</td></tr><tr><td>11</td><td>0.022373</td><td>28.384647</td><td>0.417705</td><td>00:06</td></tr><tr><td>12</td><td>0.021089</td><td>32.352013</td><td>0.345738</td><td>00:06</td></tr><tr><td>13</td><td>0.015358</td><td>22.872452</td><td>0.445902</td><td>00:06</td></tr><tr><td>14</td><td>0.011302</td><td>24.551773</td><td>0.426721</td><td>00:06</td></tr><tr><td>15</td><td>0.009390</td><td>42.949554</td><td>0.359016</td><td>00:06</td></tr><tr><td>16</td><td>0.007303</td><td>33.270088</td><td>0.384590</td><td>00:06</td></tr><tr><td>17</td><td>0.005737</td><td>36.527905</td><td>0.443607</td><td>00:06</td></tr><tr><td>18</td><td>0.006681</td><td>50.577961</td><td>0.382951</td><td>00:06</td></tr><tr><td>19</td><td>0.008123</td><td>40.226540</td><td>0.383115</td><td>00:06</td></tr><tr><td>20</td><td>0.006337</td><td>28.982018</td><td>0.449508</td><td>00:06</td></tr><tr><td>21</td><td>0.006802</td><td>46.665611</td><td>0.371475</td><td>00:06</td></tr><tr><td>22</td><td>0.005443</td><td>46.184723</td><td>0.396721</td><td>00:06</td></tr><tr><td>23</td><td>0.004337</td><td>39.396210</td><td>0.399180</td><td>00:06</td></tr><tr><td>24</td><td>0.004864</td><td>41.632729</td><td>0.349016</td><td>00:06</td></tr><tr><td>25</td><td>0.005155</td><td>43.151711</td><td>0.429016</td><td>00:06</td></tr><tr><td>26</td><td>0.003748</td><td>42.254112</td><td>0.450000</td><td>00:06</td></tr><tr><td>27</td><td>0.002963</td><td>54.913448</td><td>0.400492</td><td>00:06</td></tr><tr><td>28</td><td>0.002216</td><td>40.856480</td><td>0.395738</td><td>00:06</td></tr><tr><td>29</td><td>0.001842</td><td>60.453419</td><td>0.369180</td><td>00:06</td></tr><tr><td>30</td><td>0.001362</td><td>39.837353</td><td>0.413770</td><td>00:06</td></tr><tr><td>31</td><td>0.000952</td><td>40.315037</td><td>0.439836</td><td>00:06</td></tr><tr><td>32</td><td>0.000670</td><td>49.462681</td><td>0.392131</td><td>00:06</td></tr><tr><td>33</td><td>0.000534</td><td>39.240746</td><td>0.446885</td><td>00:06</td></tr><tr><td>34</td><td>0.000435</td><td>45.652649</td><td>0.401803</td><td>00:06</td></tr><tr><td>35</td><td>0.000349</td><td>42.444122</td><td>0.424590</td><td>00:06</td></tr><tr><td>36</td><td>0.000310</td><td>42.127506</td><td>0.434426</td><td>00:06</td></tr><tr><td>37</td><td>0.000395</td><td>66.947784</td><td>0.336230</td><td>00:06</td></tr><tr><td>38</td><td>0.000363</td><td>46.147434</td><td>0.420164</td><td>00:06</td></tr><tr><td>39</td><td>0.000388</td><td>65.602943</td><td>0.395574</td><td>00:06</td></tr><tr><td>40</td><td>0.000381</td><td>55.625580</td><td>0.405410</td><td>00:06</td></tr><tr><td>41</td><td>0.000326</td><td>55.676384</td><td>0.411639</td><td>00:06</td></tr><tr><td>42</td><td>0.000292</td><td>54.144154</td><td>0.387705</td><td>00:06</td></tr><tr><td>43</td><td>0.000243</td><td>55.591774</td><td>0.408525</td><td>00:06</td></tr><tr><td>44</td><td>0.000202</td><td>54.178047</td><td>0.413770</td><td>00:06</td></tr><tr><td>45</td><td>0.000168</td><td>52.989010</td><td>0.417377</td><td>00:06</td></tr><tr><td>46</td><td>0.000149</td><td>52.598534</td><td>0.417541</td><td>00:06</td></tr><tr><td>47</td><td>0.000136</td><td>52.355137</td><td>0.414754</td><td>00:06</td></tr><tr><td>48</td><td>0.000129</td><td>52.483521</td><td>0.416066</td><td>00:06</td></tr><tr><td>49</td><td>0.000123</td><td>52.525166</td><td>0.415410</td><td>00:06</td></tr></tbody></table></div>

Better model found at epoch 0 with accuracy value: 0.5126229524612427.
Better model found at epoch 1 with accuracy value: 0.5663934350013733.
Better model found at epoch 2 with accuracy value: 0.5765573978424072.
Better model found at epoch 3 with accuracy value: 0.5768852233886719.
Better model found at epoch 4 with accuracy value: 0.5965573787689209.

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_fused_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_fused_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_fused_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_fused_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_synthetic_to_real_fused_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "synthetic_to_real",
  "native_modality": "fused",
  "native_hz": 64,
  "channels": "ACC_x,ACC_y,ACC_z,BVP,EDA,TEMP",
  "description": "ACC+BVP+EDA+TEMP fused",
  "input_shape_train_native_N_T_C": [
    30000,
    512,
    6
  ],
  "input_shape_test_native_N_T_C": [
    10063,
    512,
    6
  ],
  "input_shape_train_framework_N_C_T": [
    30000,
    6,
    512
  ],
  "input_shape_test_framework_N_C_T": [
    10063,
    6,
    512
  ],
  "epochs": 50,
  "best_epoch_by_val_accuracy": 5,
  "best_val_accuracy": 0.5965573787689209,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_synthetic_to_real_fused.pth",
  "used_saved_real_to_real_model": false,
  "training_reused_from_experiment": "",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.5075027327834641,
  "macro_precision": 0.6033977510636037,
  "macro_recall": 0.5521501057065452,
  "macro_f1": 0.49359120885414653,
  "weighted_precision": 0.6477247212151828,
  "weighted_recall": 0.5075027327834641,
  "weighted_f1": 0.5107484300219315,
  "balanced_accuracy": 0.5521501057065452
}

================================================================================
[tsai] real_plus_synthetic_to_real | fused
================================================================================

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.395277</td><td>1.017855</td><td>0.703279</td><td>00:12</td></tr><tr><td>1</td><td>0.893515</td><td>0.856359</td><td>0.732787</td><td>00:17</td></tr><tr><td>2</td><td>0.561288</td><td>0.712880</td><td>0.724262</td><td>00:21</td></tr><tr><td>3</td><td>0.361239</td><td>0.696747</td><td>0.720820</td><td>00:21</td></tr><tr><td>4</td><td>0.261108</td><td>0.824562</td><td>0.730164</td><td>00:19</td></tr><tr><td>5</td><td>0.194962</td><td>0.716249</td><td>0.730984</td><td>00:22</td></tr><tr><td>6</td><td>0.159922</td><td>0.683720</td><td>0.734262</td><td>00:22</td></tr><tr><td>7</td><td>0.135342</td><td>0.775905</td><td>0.717213</td><td>00:22</td></tr><tr><td>8</td><td>0.123449</td><td>0.675199</td><td>0.758197</td><td>00:18</td></tr><tr><td>9</td><td>0.113853</td><td>0.920227</td><td>0.692131</td><td>00:23</td></tr><tr><td>10</td><td>0.107223</td><td>0.912710</td><td>0.678197</td><td>00:23</td></tr><tr><td>11</td><td>0.095584</td><td>1.028791</td><td>0.688197</td><td>00:23</td></tr><tr><td>12</td><td>0.079686</td><td>1.177292</td><td>0.707705</td><td>00:21</td></tr><tr><td>13</td><td>0.076631</td><td>1.267655</td><td>0.701967</td><td>00:24</td></tr><tr><td>14</td><td>0.071555</td><td>1.377669</td><td>0.691475</td><td>00:24</td></tr><tr><td>15</td><td>0.061151</td><td>1.062356</td><td>0.708852</td><td>00:24</td></tr><tr><td>16</td><td>0.063333</td><td>1.398172</td><td>0.655246</td><td>00:24</td></tr><tr><td>17</td><td>0.053689</td><td>1.135941</td><td>0.691967</td><td>00:20</td></tr><tr><td>18</td><td>0.057851</td><td>1.203199</td><td>0.685410</td><td>00:17</td></tr><tr><td>19</td><td>0.048798</td><td>1.223923</td><td>0.726066</td><td>00:17</td></tr><tr><td>20</td><td>0.045243</td><td>1.666035</td><td>0.704426</td><td>00:17</td></tr><tr><td>21</td><td>0.038053</td><td>1.323218</td><td>0.697049</td><td>00:17</td></tr><tr><td>22</td><td>0.033054</td><td>1.797669</td><td>0.683443</td><td>00:17</td></tr><tr><td>23</td><td>0.041163</td><td>1.249572</td><td>0.691803</td><td>00:16</td></tr><tr><td>24</td><td>0.035378</td><td>1.419917</td><td>0.681639</td><td>00:17</td></tr><tr><td>25</td><td>0.030660</td><td>1.610636</td><td>0.666066</td><td>00:17</td></tr><tr><td>26</td><td>0.028265</td><td>1.464021</td><td>0.715738</td><td>00:17</td></tr><tr><td>27</td><td>0.022787</td><td>1.214126</td><td>0.726229</td><td>00:17</td></tr><tr><td>28</td><td>0.025231</td><td>1.695345</td><td>0.699836</td><td>00:17</td></tr><tr><td>29</td><td>0.019827</td><td>1.781273</td><td>0.720492</td><td>00:17</td></tr><tr><td>30</td><td>0.016610</td><td>1.823178</td><td>0.677705</td><td>00:17</td></tr><tr><td>31</td><td>0.014741</td><td>1.862819</td><td>0.709344</td><td>00:17</td></tr><tr><td>32</td><td>0.016409</td><td>1.697117</td><td>0.711475</td><td>00:17</td></tr><tr><td>33</td><td>0.013710</td><td>1.831051</td><td>0.688852</td><td>00:16</td></tr><tr><td>34</td><td>0.010087</td><td>2.075464</td><td>0.705246</td><td>00:16</td></tr><tr><td>35</td><td>0.008944</td><td>1.577535</td><td>0.750164</td><td>00:17</td></tr><tr><td>36</td><td>0.008324</td><td>1.868105</td><td>0.699672</td><td>00:17</td></tr><tr><td>37</td><td>0.006983</td><td>2.030030</td><td>0.714918</td><td>00:16</td></tr><tr><td>38</td><td>0.006667</td><td>1.887025</td><td>0.715902</td><td>00:17</td></tr><tr><td>39</td><td>0.005101</td><td>2.094207</td><td>0.716557</td><td>00:17</td></tr><tr><td>40</td><td>0.004213</td><td>2.233679</td><td>0.704754</td><td>00:20</td></tr><tr><td>41</td><td>0.003662</td><td>2.253189</td><td>0.706885</td><td>00:24</td></tr><tr><td>42</td><td>0.003017</td><td>2.111038</td><td>0.722787</td><td>00:25</td></tr><tr><td>43</td><td>0.002512</td><td>2.183668</td><td>0.711311</td><td>00:24</td></tr><tr><td>44</td><td>0.002148</td><td>2.154311</td><td>0.714426</td><td>00:24</td></tr><tr><td>45</td><td>0.002008</td><td>2.155348</td><td>0.717049</td><td>00:24</td></tr><tr><td>46</td><td>0.001961</td><td>2.256253</td><td>0.710820</td><td>00:24</td></tr><tr><td>47</td><td>0.001716</td><td>2.251707</td><td>0.713771</td><td>00:22</td></tr><tr><td>48</td><td>0.001641</td><td>2.237091</td><td>0.717541</td><td>00:24</td></tr><tr><td>49</td><td>0.001545</td><td>2.250302</td><td>0.713934</td><td>00:24</td></tr></tbody></table></div>

Better model found at epoch 0 with accuracy value: 0.703278660774231.
Better model found at epoch 1 with accuracy value: 0.7327868938446045.
Better model found at epoch 6 with accuracy value: 0.7342622876167297.
Better model found at epoch 8 with accuracy value: 0.7581967115402222.

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_fused_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_fused_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_fused_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_fused_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_real_plus_synthetic_to_real_fused_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_plus_synthetic_to_real",
  "native_modality": "fused",
  "native_hz": 64,
  "channels": "ACC_x,ACC_y,ACC_z,BVP,EDA,TEMP",
  "description": "ACC+BVP+EDA+TEMP fused",
  "input_shape_train_native_N_T_C": [
    60762,
    512,
    6
  ],
  "input_shape_test_native_N_T_C": [
    10063,
    512,
    6
  ],
  "input_shape_train_framework_N_C_T": [
    60762,
    6,
    512
  ],
  "input_shape_test_framework_N_C_T": [
    10063,
    6,
    512
  ],
  "epochs": 50,
  "best_epoch_by_val_accuracy": 9,
  "best_val_accuracy": 0.7581967115402222,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_saved_models/best_InceptionTimePlus_real_plus_synthetic_to_real_fused.pth",
  "used_saved_real_to_real_model": false,
  "training_reused_from_experiment": "",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.4933916327139024,
  "macro_precision": 0.49838578154447166,
  "macro_recall": 0.5157075939692768,
  "macro_f1": 0.47930830567033716,
  "weighted_precision": 0.507421285781902,
  "weighted_recall": 0.4933916327139024,
  "weighted_f1": 0.4759504176227868,
  "balanced_accuracy": 0.5157075939692768
}

[tsai] Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_native_downstream_results.csv
[tsai] Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/tsai_native_per_activity_results.csv
Saved coverage report: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/experiment_coverage_report.csv
Expected rows: 20
Actual rows: 20
Rows with errors: 0

================================================================================
DONE
================================================================================
Saved combined aggregate results: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/all_framework_native_results.csv
Saved combined per-activity results: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/all_framework_native_per_activity_results.csv
Saved summary: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/rollout_v1/evaluation_summary.json

Aggregate results:

,model_family,synthetic_method,synthetic_method_display_name,framework,model,experiment,native_modality,native_hz,channels,description,...,lr,accuracy,macro_precision,macro_recall,macro_f1,weighted_precision,weighted_recall,weighted_f1,balanced_accuracy,_loaded_from_result_csv
0,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,real_to_real,acc,32,"ACC_x,ACC_y,ACC_z",ACC only,...,0.001,0.585213,0.661826,0.636217,0.643439,0.608788,0.585213,0.593561,0.636217,/home/iailab42/khans1/projects/ir/models/downstream/pretrained/tsai_aeon_results/tsai_native_downstream_results.csv
1,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,real_to_synthetic,acc,32,"ACC_x,ACC_y,ACC_z",ACC only,...,0.001,0.098000,0.064838,0.144619,0.046135,0.131792,0.098000,0.079983,0.144619,NaN
2,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,synthetic_to_real,acc,32,"ACC_x,ACC_y,ACC_z",ACC only,...,0.001,0.391235,0.249745,0.301035,0.265355,0.333795,0.391235,0.353549,0.301035,NaN
3,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,real_plus_synthetic_to_real,acc,32,"ACC_x,ACC_y,ACC_z",ACC only,...,0.001,0.619994,0.707453,0.657615,0.673876,0.647870,0.619994,0.626044,0.657615,NaN
4,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,real_to_real,bvp,64,BVP,BVP only,...,0.001,0.489317,0.508837,0.555853,0.509720,0.514858,0.489317,0.483713,0.555853,/home/iailab42/khans1/projects/ir/models/downstream/pretrained/tsai_aeon_results/tsai_native_downstream_results.csv
5,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,real_to_synthetic,bvp,64,BVP,BVP only,...,0.001,0.096000,0.093445,0.136963,0.046402,0.139543,0.096000,0.055297,0.136963,NaN
6,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,synthetic_to_real,bvp,64,BVP,BVP only,...,0.001,0.271390,0.142580,0.143169,0.095630,0.156247,0.271390,0.173899,0.143169,NaN
7,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,real_plus_synthetic_to_real,bvp,64,BVP,BVP only,...,0.001,0.455133,0.503077,0.559462,0.495268,0.484614,0.455133,0.436286,0.559462,NaN
8,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,real_to_real,eda,4,EDA,EDA only,...,0.001,0.310146,0.321143,0.301207,0.261016,0.322502,0.310146,0.282839,0.301207,/home/iailab42/khans1/projects/ir/models/downstream/pretrained/tsai_aeon_results/tsai_native_downstream_results.csv
9,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,real_to_synthetic,eda,4,EDA,EDA only,...,0.001,0.131333,0.087427,0.127651,0.078832,0.135663,0.131333,0.095665,0.127651,NaN
10,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,synthetic_to_real,eda,4,EDA,EDA only,...,0.001,0.331810,0.131564,0.226276,0.161053,0.181829,0.331810,0.228896,0.226276,NaN
11,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,real_plus_synthetic_to_real,eda,4,EDA,EDA only,...,0.001,0.326940,0.330769,0.309354,0.263647,0.342606,0.326940,0.296372,0.309354,NaN
12,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,real_to_real,temp,4,TEMP,TEMP only,...,0.001,0.221505,0.292397,0.260643,0.195919,0.316072,0.221505,0.208642,0.260643,/home/iailab42/khans1/projects/ir/models/downstream/pretrained/tsai_aeon_results/tsai_native_downstream_results.csv
13,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,real_to_synthetic,temp,4,TEMP,TEMP only,...,0.001,0.289556,0.120074,0.181549,0.142510,0.173059,0.289556,0.214798,0.181549,NaN
14,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,synthetic_to_real,temp,4,TEMP,TEMP only,...,0.001,0.293451,0.185546,0.205995,0.114825,0.297804,0.293451,0.216752,0.205995,NaN
15,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,real_plus_synthetic_to_real,temp,4,TEMP,TEMP only,...,0.001,0.257677,0.139970,0.245360,0.133597,0.220933,0.257677,0.206153,0.245360,NaN
16,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,real_to_real,fused,64,"ACC_x,ACC_y,ACC_z,BVP,EDA,TEMP",ACC+BVP+EDA+TEMP fused,...,0.001,0.497466,0.539744,0.542232,0.514917,0.547392,0.497466,0.504374,0.542232,/home/iailab42/khans1/projects/ir/models/downstream/pretrained/tsai_aeon_results/tsai_native_downstream_results.csv
17,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,real_to_synthetic,fused,64,"ACC_x,ACC_y,ACC_z,BVP,EDA,TEMP",ACC+BVP+EDA+TEMP fused,...,0.001,0.276556,0.044221,0.125300,0.054786,0.080096,0.276556,0.120092,0.125300,NaN
18,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,synthetic_to_real,fused,64,"ACC_x,ACC_y,ACC_z,BVP,EDA,TEMP",ACC+BVP+EDA+TEMP fused,...,0.001,0.507503,0.603398,0.552150,0.493591,0.647725,0.507503,0.510748,0.552150,NaN
19,kovae,rollout_v1,KoVAE-Rollout,tsai,InceptionTimePlus,real_plus_synthetic_to_real,fused,64,"ACC_x,ACC_y,ACC_z,BVP,EDA,TEMP",ACC+BVP+EDA+TEMP fused,...,0.001,0.493392,0.498386,0.515708,0.479308,0.507421,0.493392,0.475950,0.515708,NaN

Coverage:

,framework,experiment,native_modality,row_count,error_count,status
0,tsai,real_to_real,acc,1,0,ok
1,tsai,real_to_real,bvp,1,0,ok
2,tsai,real_to_real,eda,1,0,ok
3,tsai,real_to_real,temp,1,0,ok
4,tsai,real_to_real,fused,1,0,ok
5,tsai,real_to_synthetic,acc,1,0,ok
6,tsai,real_to_synthetic,bvp,1,0,ok
7,tsai,real_to_synthetic,eda,1,0,ok
8,tsai,real_to_synthetic,temp,1,0,ok
9,tsai,real_to_synthetic,fused,1,0,ok
10,tsai,synthetic_to_real,acc,1,0,ok
11,tsai,synthetic_to_real,bvp,1,0,ok
12,tsai,synthetic_to_real,eda,1,0,ok
13,tsai,synthetic_to_real,temp,1,0,ok
14,tsai,synthetic_to_real,fused,1,0,ok
15,tsai,real_plus_synthetic_to_real,acc,1,0,ok
16,tsai,real_plus_synthetic_to_real,bvp,1,0,ok
17,tsai,real_plus_synthetic_to_real,eda,1,0,ok
18,tsai,real_plus_synthetic_to_real,temp,1,0,ok
19,tsai,real_plus_synthetic_to_real,fused,1,0,ok

####################################################################################################
RUNNING kovae | posterior_bank_v2
####################################################################################################

Configured project paths
  PROJECT_ROOT: /home/iailab42/khans1/projects/ir
  model_family: kovae
  synthetic_method: posterior_bank_v2
  synthetic_method_display: KoVAE-Posterior
  REAL_DIR: /home/iailab42/khans1/projects/ir/data/processed/native_rates
  SYN_DIR: /home/iailab42/khans1/projects/ir/data/synthetic_subjects/kovae/posterior_bank_v2
  OUT_DIR: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2
  PRETRAINED_RESULTS_DIR: /home/iailab42/khans1/projects/ir/models/downstream/pretrained/tsai_aeon_results
================================================================================
Native tsai + aeon evaluation
================================================================================
CURRENT_MODEL_FAMILY: kovae
CURRENT_SYNTHETIC_METHOD: posterior_bank_v2
CURRENT_SYNTHETIC_METHOD_DISPLAY: KoVAE-Posterior
RUN_REAL_TO_REAL_ONLY: False
USE_REAL_MODELS: True
FRAMEWORKS: ['tsai']
MODALITIES: ['acc', 'bvp', 'eda', 'temp', 'fused']
OUT_DIR: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2
REAL_DIR: /home/iailab42/khans1/projects/ir/data/processed/native_rates
SYN_DIR: /home/iailab42/khans1/projects/ir/data/synthetic_subjects/kovae/posterior_bank_v2
PRETRAINED_RESULTS_DIR: /home/iailab42/khans1/projects/ir/models/downstream/pretrained/tsai_aeon_results

Loaded real data:
  y: (46925,)
  subjects: (46925,)
  acc: (46925, 256, 3)
  bvp: (46925, 512, 1)
  slow: (46925, 32, 2)

Loaded synthetic data:
  y: (30000,)
  subjects: (30000,)
  acc: (30000, 256, 3)
  bvp: (30000, 512, 1)
  slow: (30000, 32, 2)

Fixed split OK:
  Train: ['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S9', 'S11', 'S12', 'S13']
  Val:   ['S14', 'S15']
  Test:  ['S7', 'S8', 'S10']

Synthetic test subjects: [np.str_('synthetic_subject_01'), np.str_('synthetic_subject_02'), np.str_('synthetic_subject_03')]
  View acc   : train=(30762, 256, 3), val=(6100, 256, 3), test=(10063, 256, 3), syn_all=(30000, 256, 3), syn_test3=(9000, 256, 3)
  View bvp   : train=(30762, 512, 1), val=(6100, 512, 1), test=(10063, 512, 1), syn_all=(30000, 512, 1), syn_test3=(9000, 512, 1)
  View eda   : train=(30762, 32, 1), val=(6100, 32, 1), test=(10063, 32, 1), syn_all=(30000, 32, 1), syn_test3=(9000, 32, 1)
  View temp  : train=(30762, 32, 1), val=(6100, 32, 1), test=(10063, 32, 1), syn_all=(30000, 32, 1), syn_test3=(9000, 32, 1)
  View fused : train=(30762, 512, 6), val=(6100, 512, 6), test=(10063, 512, 6), syn_all=(30000, 512, 6), syn_test3=(9000, 512, 6)

Saved shape report: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/native_input_shape_report.csv

,native_view,native_hz,channels,native_real_train_shape_N_T_C,native_real_val_shape_N_T_C,native_real_test_shape_N_T_C,framework_real_train_shape_N_C_T,framework_real_val_shape_N_C_T,framework_real_test_shape_N_C_T,native_syn_all_shape_N_T_C,native_syn_test3_shape_N_T_C,syn_test_subjects,framework_syn_all_shape_N_C_T,framework_syn_test3_shape_N_C_T
0,acc,32,"ACC_x,ACC_y,ACC_z","[30762, 256, 3]","[6100, 256, 3]","[10063, 256, 3]","[30762, 3, 256]","[6100, 3, 256]","[10063, 3, 256]","[30000, 256, 3]","[9000, 256, 3]","synthetic_subject_01,synthetic_subject_02,synthetic_subject_03","[30000, 3, 256]","[9000, 3, 256]"
1,bvp,64,BVP,"[30762, 512, 1]","[6100, 512, 1]","[10063, 512, 1]","[30762, 1, 512]","[6100, 1, 512]","[10063, 1, 512]","[30000, 512, 1]","[9000, 512, 1]","synthetic_subject_01,synthetic_subject_02,synthetic_subject_03","[30000, 1, 512]","[9000, 1, 512]"
2,eda,4,EDA,"[30762, 32, 1]","[6100, 32, 1]","[10063, 32, 1]","[30762, 1, 32]","[6100, 1, 32]","[10063, 1, 32]","[30000, 32, 1]","[9000, 32, 1]","synthetic_subject_01,synthetic_subject_02,synthetic_subject_03","[30000, 1, 32]","[9000, 1, 32]"
3,temp,4,TEMP,"[30762, 32, 1]","[6100, 32, 1]","[10063, 32, 1]","[30762, 1, 32]","[6100, 1, 32]","[10063, 1, 32]","[30000, 32, 1]","[9000, 32, 1]","synthetic_subject_01,synthetic_subject_02,synthetic_subject_03","[30000, 1, 32]","[9000, 1, 32]"
4,fused,64,"ACC_x,ACC_y,ACC_z,BVP,EDA,TEMP","[30762, 512, 6]","[6100, 512, 6]","[10063, 512, 6]","[30762, 6, 512]","[6100, 6, 512]","[10063, 6, 512]","[30000, 512, 6]","[9000, 512, 6]","synthetic_subject_01,synthetic_subject_02,synthetic_subject_03","[30000, 6, 512]","[9000, 6, 512]"

================================================================================
[tsai] real_to_real | acc
================================================================================
Reusing saved tsai Real->Real metrics.

================================================================================
[tsai] real_to_synthetic | acc
================================================================================
Copied external tsai model into current output folder: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_to_real_acc.pth
Loading tsai Real->Real model: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_to_real_acc.pth

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_acc_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_acc_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_acc_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_acc_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_acc_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_to_synthetic",
  "native_modality": "acc",
  "native_hz": 32,
  "channels": "ACC_x,ACC_y,ACC_z",
  "description": "ACC only",
  "input_shape_train_native_N_T_C": [
    30762,
    256,
    3
  ],
  "input_shape_test_native_N_T_C": [
    9000,
    256,
    3
  ],
  "input_shape_train_framework_N_C_T": [
    30762,
    3,
    256
  ],
  "input_shape_test_framework_N_C_T": [
    9000,
    3,
    256
  ],
  "epochs": 0,
  "best_epoch_by_val_accuracy": 34,
  "best_val_accuracy": 0.7380327582359314,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_to_real_acc.pth",
  "used_saved_real_to_real_model": true,
  "training_reused_from_experiment": "real_to_real",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.7254444444444444,
  "macro_precision": 0.8501350221558445,
  "macro_recall": 0.692070252485476,
  "macro_f1": 0.74477801049404,
  "weighted_precision": 0.7841628193810023,
  "weighted_recall": 0.7254444444444444,
  "weighted_f1": 0.7238431862686432,
  "balanced_accuracy": 0.692070252485476
}

================================================================================
[tsai] synthetic_to_real | acc
================================================================================

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.497114</td><td>1.602882</td><td>0.461803</td><td>00:06</td></tr><tr><td>1</td><td>1.251302</td><td>1.234706</td><td>0.565246</td><td>00:06</td></tr><tr><td>2</td><td>1.075608</td><td>1.125819</td><td>0.562131</td><td>00:06</td></tr><tr><td>3</td><td>0.926023</td><td>1.033731</td><td>0.631639</td><td>00:06</td></tr><tr><td>4</td><td>0.802309</td><td>1.177276</td><td>0.590492</td><td>00:06</td></tr><tr><td>5</td><td>0.706049</td><td>1.045146</td><td>0.628033</td><td>00:06</td></tr><tr><td>6</td><td>0.641549</td><td>0.999537</td><td>0.646393</td><td>00:06</td></tr><tr><td>7</td><td>0.592973</td><td>1.344974</td><td>0.604590</td><td>00:06</td></tr><tr><td>8</td><td>0.547498</td><td>1.319680</td><td>0.624918</td><td>00:06</td></tr><tr><td>9</td><td>0.517721</td><td>1.334950</td><td>0.626230</td><td>00:06</td></tr><tr><td>10</td><td>0.494374</td><td>1.005567</td><td>0.652295</td><td>00:06</td></tr><tr><td>11</td><td>0.460448</td><td>1.155406</td><td>0.624262</td><td>00:06</td></tr><tr><td>12</td><td>0.432585</td><td>1.049736</td><td>0.682459</td><td>00:06</td></tr><tr><td>13</td><td>0.408157</td><td>1.350094</td><td>0.631803</td><td>00:06</td></tr><tr><td>14</td><td>0.377513</td><td>1.186944</td><td>0.690164</td><td>00:06</td></tr><tr><td>15</td><td>0.352232</td><td>1.258040</td><td>0.659180</td><td>00:06</td></tr><tr><td>16</td><td>0.330748</td><td>1.822066</td><td>0.634262</td><td>00:06</td></tr><tr><td>17</td><td>0.325895</td><td>1.205841</td><td>0.651803</td><td>00:06</td></tr><tr><td>18</td><td>0.301013</td><td>1.150675</td><td>0.677213</td><td>00:06</td></tr><tr><td>19</td><td>0.288168</td><td>1.272662</td><td>0.657541</td><td>00:06</td></tr><tr><td>20</td><td>0.267422</td><td>1.693892</td><td>0.656393</td><td>00:06</td></tr><tr><td>21</td><td>0.261848</td><td>1.153216</td><td>0.699344</td><td>00:06</td></tr><tr><td>22</td><td>0.248881</td><td>1.617881</td><td>0.652623</td><td>00:06</td></tr><tr><td>23</td><td>0.231693</td><td>1.551193</td><td>0.594426</td><td>00:06</td></tr><tr><td>24</td><td>0.221354</td><td>1.534593</td><td>0.696557</td><td>00:06</td></tr><tr><td>25</td><td>0.212974</td><td>1.692300</td><td>0.673115</td><td>00:06</td></tr><tr><td>26</td><td>0.201825</td><td>1.773050</td><td>0.681475</td><td>00:06</td></tr><tr><td>27</td><td>0.190065</td><td>1.387609</td><td>0.708033</td><td>00:06</td></tr><tr><td>28</td><td>0.181251</td><td>1.783633</td><td>0.656885</td><td>00:06</td></tr><tr><td>29</td><td>0.170231</td><td>1.527849</td><td>0.674098</td><td>00:06</td></tr><tr><td>30</td><td>0.156968</td><td>2.304915</td><td>0.667541</td><td>00:05</td></tr><tr><td>31</td><td>0.148178</td><td>2.287450</td><td>0.642787</td><td>00:03</td></tr><tr><td>32</td><td>0.138951</td><td>2.221425</td><td>0.646721</td><td>00:03</td></tr><tr><td>33</td><td>0.126826</td><td>2.002469</td><td>0.668361</td><td>00:03</td></tr><tr><td>34</td><td>0.118030</td><td>2.163458</td><td>0.680656</td><td>00:03</td></tr><tr><td>35</td><td>0.114480</td><td>2.402676</td><td>0.673279</td><td>00:03</td></tr><tr><td>36</td><td>0.105863</td><td>2.396880</td><td>0.652787</td><td>00:03</td></tr><tr><td>37</td><td>0.098588</td><td>2.357530</td><td>0.676721</td><td>00:03</td></tr><tr><td>38</td><td>0.090001</td><td>2.213521</td><td>0.688197</td><td>00:03</td></tr><tr><td>39</td><td>0.083189</td><td>2.364689</td><td>0.671148</td><td>00:03</td></tr><tr><td>40</td><td>0.077740</td><td>2.401799</td><td>0.676230</td><td>00:03</td></tr><tr><td>41</td><td>0.072054</td><td>2.379534</td><td>0.675410</td><td>00:03</td></tr><tr><td>42</td><td>0.067311</td><td>2.374404</td><td>0.664098</td><td>00:03</td></tr><tr><td>43</td><td>0.063210</td><td>2.508984</td><td>0.663115</td><td>00:03</td></tr><tr><td>44</td><td>0.059600</td><td>2.506444</td><td>0.680000</td><td>00:03</td></tr><tr><td>45</td><td>0.056167</td><td>2.467684</td><td>0.674098</td><td>00:03</td></tr><tr><td>46</td><td>0.053312</td><td>2.444487</td><td>0.680000</td><td>00:03</td></tr><tr><td>47</td><td>0.050653</td><td>2.471131</td><td>0.678361</td><td>00:03</td></tr><tr><td>48</td><td>0.049524</td><td>2.493495</td><td>0.676557</td><td>00:03</td></tr><tr><td>49</td><td>0.048619</td><td>2.488809</td><td>0.675902</td><td>00:03</td></tr></tbody></table></div>

Better model found at epoch 0 with accuracy value: 0.46180328726768494.
Better model found at epoch 1 with accuracy value: 0.5652459263801575.
Better model found at epoch 3 with accuracy value: 0.6316393613815308.
Better model found at epoch 6 with accuracy value: 0.6463934183120728.
Better model found at epoch 10 with accuracy value: 0.6522950530052185.
Better model found at epoch 12 with accuracy value: 0.6824589967727661.
Better model found at epoch 14 with accuracy value: 0.6901639103889465.
Better model found at epoch 21 with accuracy value: 0.699344277381897.
Better model found at epoch 27 with accuracy value: 0.7080327868461609.

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_acc_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_acc_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_acc_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_acc_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_acc_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "synthetic_to_real",
  "native_modality": "acc",
  "native_hz": 32,
  "channels": "ACC_x,ACC_y,ACC_z",
  "description": "ACC only",
  "input_shape_train_native_N_T_C": [
    30000,
    256,
    3
  ],
  "input_shape_test_native_N_T_C": [
    10063,
    256,
    3
  ],
  "input_shape_train_framework_N_C_T": [
    30000,
    3,
    256
  ],
  "input_shape_test_framework_N_C_T": [
    10063,
    3,
    256
  ],
  "epochs": 50,
  "best_epoch_by_val_accuracy": 28,
  "best_val_accuracy": 0.7080327868461609,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_synthetic_to_real_acc.pth",
  "used_saved_real_to_real_model": false,
  "training_reused_from_experiment": "",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.6481168637583226,
  "macro_precision": 0.7270309433249034,
  "macro_recall": 0.7434178872871353,
  "macro_f1": 0.7203293601157865,
  "weighted_precision": 0.6746661536167123,
  "weighted_recall": 0.6481168637583226,
  "weighted_f1": 0.6396036337652917,
  "balanced_accuracy": 0.7434178872871353
}

================================================================================
[tsai] real_plus_synthetic_to_real | acc
================================================================================

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.240289</td><td>1.193380</td><td>0.533934</td><td>00:06</td></tr><tr><td>1</td><td>0.976815</td><td>1.015897</td><td>0.637213</td><td>00:06</td></tr><tr><td>2</td><td>0.778655</td><td>1.138810</td><td>0.599016</td><td>00:06</td></tr><tr><td>3</td><td>0.640956</td><td>0.982524</td><td>0.623770</td><td>00:06</td></tr><tr><td>4</td><td>0.557645</td><td>0.967032</td><td>0.683770</td><td>00:06</td></tr><tr><td>5</td><td>0.515880</td><td>0.821692</td><td>0.679836</td><td>00:06</td></tr><tr><td>6</td><td>0.470212</td><td>0.781831</td><td>0.690164</td><td>00:06</td></tr><tr><td>7</td><td>0.451772</td><td>0.768170</td><td>0.710328</td><td>00:06</td></tr><tr><td>8</td><td>0.431067</td><td>0.871338</td><td>0.677213</td><td>00:06</td></tr><tr><td>9</td><td>0.414382</td><td>0.900463</td><td>0.676557</td><td>00:06</td></tr><tr><td>10</td><td>0.384268</td><td>1.069637</td><td>0.692459</td><td>00:06</td></tr><tr><td>11</td><td>0.364426</td><td>0.867463</td><td>0.709344</td><td>00:06</td></tr><tr><td>12</td><td>0.347036</td><td>1.033204</td><td>0.669672</td><td>00:06</td></tr><tr><td>13</td><td>0.327131</td><td>0.790739</td><td>0.713607</td><td>00:06</td></tr><tr><td>14</td><td>0.316268</td><td>1.175310</td><td>0.673770</td><td>00:06</td></tr><tr><td>15</td><td>0.291016</td><td>0.888321</td><td>0.724426</td><td>00:06</td></tr><tr><td>16</td><td>0.275425</td><td>1.199788</td><td>0.695738</td><td>00:06</td></tr><tr><td>17</td><td>0.257476</td><td>0.815106</td><td>0.740820</td><td>00:06</td></tr><tr><td>18</td><td>0.240699</td><td>1.191351</td><td>0.697869</td><td>00:06</td></tr><tr><td>19</td><td>0.226877</td><td>0.992411</td><td>0.710492</td><td>00:06</td></tr><tr><td>20</td><td>0.210117</td><td>1.251309</td><td>0.700656</td><td>00:06</td></tr><tr><td>21</td><td>0.196534</td><td>0.839742</td><td>0.730328</td><td>00:06</td></tr><tr><td>22</td><td>0.182572</td><td>0.897932</td><td>0.727213</td><td>00:06</td></tr><tr><td>23</td><td>0.168824</td><td>1.250633</td><td>0.696557</td><td>00:06</td></tr><tr><td>24</td><td>0.156700</td><td>0.957159</td><td>0.727213</td><td>00:06</td></tr><tr><td>25</td><td>0.150557</td><td>0.936348</td><td>0.747541</td><td>00:06</td></tr><tr><td>26</td><td>0.137324</td><td>0.926797</td><td>0.732623</td><td>00:06</td></tr><tr><td>27</td><td>0.124569</td><td>1.235701</td><td>0.736721</td><td>00:06</td></tr><tr><td>28</td><td>0.119095</td><td>1.193441</td><td>0.730000</td><td>00:06</td></tr><tr><td>29</td><td>0.106983</td><td>1.109522</td><td>0.690000</td><td>00:06</td></tr><tr><td>30</td><td>0.095606</td><td>1.039350</td><td>0.741475</td><td>00:06</td></tr><tr><td>31</td><td>0.093619</td><td>1.336758</td><td>0.696557</td><td>00:06</td></tr><tr><td>32</td><td>0.087658</td><td>1.339600</td><td>0.696230</td><td>00:06</td></tr><tr><td>33</td><td>0.079793</td><td>1.239286</td><td>0.715738</td><td>00:06</td></tr><tr><td>34</td><td>0.072812</td><td>1.158746</td><td>0.722459</td><td>00:06</td></tr><tr><td>35</td><td>0.068647</td><td>1.247086</td><td>0.678197</td><td>00:06</td></tr><tr><td>36</td><td>0.062460</td><td>1.425763</td><td>0.705410</td><td>00:06</td></tr><tr><td>37</td><td>0.057240</td><td>1.311535</td><td>0.713607</td><td>00:06</td></tr><tr><td>38</td><td>0.052919</td><td>1.206318</td><td>0.721311</td><td>00:06</td></tr><tr><td>39</td><td>0.049507</td><td>1.365832</td><td>0.718852</td><td>00:06</td></tr><tr><td>40</td><td>0.045035</td><td>1.337072</td><td>0.705902</td><td>00:06</td></tr><tr><td>41</td><td>0.041222</td><td>1.299226</td><td>0.719344</td><td>00:06</td></tr><tr><td>42</td><td>0.037766</td><td>1.338991</td><td>0.717049</td><td>00:06</td></tr><tr><td>43</td><td>0.033692</td><td>1.406099</td><td>0.715738</td><td>00:06</td></tr><tr><td>44</td><td>0.031179</td><td>1.391734</td><td>0.716393</td><td>00:11</td></tr><tr><td>45</td><td>0.030378</td><td>1.411925</td><td>0.721475</td><td>00:11</td></tr><tr><td>46</td><td>0.027694</td><td>1.455659</td><td>0.716066</td><td>00:11</td></tr><tr><td>47</td><td>0.026335</td><td>1.471913</td><td>0.719508</td><td>00:10</td></tr><tr><td>48</td><td>0.025416</td><td>1.445946</td><td>0.722295</td><td>00:11</td></tr><tr><td>49</td><td>0.024755</td><td>1.457451</td><td>0.720492</td><td>00:11</td></tr></tbody></table></div>

Better model found at epoch 0 with accuracy value: 0.5339344143867493.
Better model found at epoch 1 with accuracy value: 0.6372131109237671.
Better model found at epoch 4 with accuracy value: 0.683770477771759.
Better model found at epoch 6 with accuracy value: 0.6901639103889465.
Better model found at epoch 7 with accuracy value: 0.7103278636932373.
Better model found at epoch 13 with accuracy value: 0.7136065363883972.
Better model found at epoch 15 with accuracy value: 0.7244262099266052.
Better model found at epoch 17 with accuracy value: 0.7408196926116943.
Better model found at epoch 25 with accuracy value: 0.7475410103797913.

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_acc_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_acc_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_acc_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_acc_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_acc_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_plus_synthetic_to_real",
  "native_modality": "acc",
  "native_hz": 32,
  "channels": "ACC_x,ACC_y,ACC_z",
  "description": "ACC only",
  "input_shape_train_native_N_T_C": [
    60762,
    256,
    3
  ],
  "input_shape_test_native_N_T_C": [
    10063,
    256,
    3
  ],
  "input_shape_train_framework_N_C_T": [
    60762,
    3,
    256
  ],
  "input_shape_test_framework_N_C_T": [
    10063,
    3,
    256
  ],
  "epochs": 50,
  "best_epoch_by_val_accuracy": 26,
  "best_val_accuracy": 0.7475410103797913,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_plus_synthetic_to_real_acc.pth",
  "used_saved_real_to_real_model": false,
  "training_reused_from_experiment": "",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.6742522110702573,
  "macro_precision": 0.7277880884434751,
  "macro_recall": 0.7236422870476886,
  "macro_f1": 0.7215681654317341,
  "weighted_precision": 0.6897418148596699,
  "weighted_recall": 0.6742522110702573,
  "weighted_f1": 0.6789352102948492,
  "balanced_accuracy": 0.7236422870476886
}

================================================================================
[tsai] real_to_real | bvp
================================================================================
Reusing saved tsai Real->Real metrics.

================================================================================
[tsai] real_to_synthetic | bvp
================================================================================
Copied external tsai model into current output folder: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_to_real_bvp.pth
Loading tsai Real->Real model: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_to_real_bvp.pth

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_bvp_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_bvp_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_bvp_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_bvp_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_bvp_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_to_synthetic",
  "native_modality": "bvp",
  "native_hz": 64,
  "channels": "BVP",
  "description": "BVP only",
  "input_shape_train_native_N_T_C": [
    30762,
    512,
    1
  ],
  "input_shape_test_native_N_T_C": [
    9000,
    512,
    1
  ],
  "input_shape_train_framework_N_C_T": [
    30762,
    1,
    512
  ],
  "input_shape_test_framework_N_C_T": [
    9000,
    1,
    512
  ],
  "epochs": 0,
  "best_epoch_by_val_accuracy": 15,
  "best_val_accuracy": 0.5247541069984436,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_to_real_bvp.pth",
  "used_saved_real_to_real_model": true,
  "training_reused_from_experiment": "real_to_real",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.5466666666666666,
  "macro_precision": 0.586669294503908,
  "macro_recall": 0.5368204578282563,
  "macro_f1": 0.5284284039164031,
  "weighted_precision": 0.5920607751501533,
  "weighted_recall": 0.5466666666666666,
  "weighted_f1": 0.5492308733440735,
  "balanced_accuracy": 0.5368204578282563
}

================================================================================
[tsai] synthetic_to_real | bvp
================================================================================

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.882541</td><td>1.923351</td><td>0.303115</td><td>00:11</td></tr><tr><td>1</td><td>1.760222</td><td>1.636292</td><td>0.384426</td><td>00:11</td></tr><tr><td>2</td><td>1.623615</td><td>1.485524</td><td>0.429180</td><td>00:11</td></tr><tr><td>3</td><td>1.491303</td><td>1.510264</td><td>0.478689</td><td>00:11</td></tr><tr><td>4</td><td>1.374331</td><td>1.389271</td><td>0.503279</td><td>00:11</td></tr><tr><td>5</td><td>1.287010</td><td>1.610595</td><td>0.443443</td><td>00:11</td></tr><tr><td>6</td><td>1.215901</td><td>1.633740</td><td>0.425410</td><td>00:10</td></tr><tr><td>7</td><td>1.162686</td><td>1.467117</td><td>0.478689</td><td>00:09</td></tr><tr><td>8</td><td>1.121412</td><td>1.648916</td><td>0.377049</td><td>00:12</td></tr><tr><td>9</td><td>1.077199</td><td>2.009943</td><td>0.365082</td><td>00:12</td></tr><tr><td>10</td><td>1.050174</td><td>1.545329</td><td>0.470328</td><td>00:12</td></tr><tr><td>11</td><td>1.017453</td><td>1.526959</td><td>0.516230</td><td>00:12</td></tr><tr><td>12</td><td>0.980709</td><td>1.436043</td><td>0.496721</td><td>00:12</td></tr><tr><td>13</td><td>0.941329</td><td>1.931933</td><td>0.421311</td><td>00:12</td></tr><tr><td>14</td><td>0.911045</td><td>1.770235</td><td>0.383770</td><td>00:12</td></tr><tr><td>15</td><td>0.880471</td><td>1.780718</td><td>0.429672</td><td>00:12</td></tr><tr><td>16</td><td>0.849281</td><td>1.921893</td><td>0.367213</td><td>00:12</td></tr><tr><td>17</td><td>0.827472</td><td>1.642229</td><td>0.500984</td><td>00:12</td></tr><tr><td>18</td><td>0.793546</td><td>1.943264</td><td>0.430984</td><td>00:12</td></tr><tr><td>19</td><td>0.763489</td><td>1.797539</td><td>0.421148</td><td>00:12</td></tr><tr><td>20</td><td>0.724051</td><td>1.677750</td><td>0.505246</td><td>00:12</td></tr><tr><td>21</td><td>0.696889</td><td>2.205786</td><td>0.380984</td><td>00:12</td></tr><tr><td>22</td><td>0.664786</td><td>2.458787</td><td>0.436557</td><td>00:11</td></tr><tr><td>23</td><td>0.631972</td><td>2.155272</td><td>0.417869</td><td>00:11</td></tr><tr><td>24</td><td>0.598848</td><td>1.891457</td><td>0.459180</td><td>00:12</td></tr><tr><td>25</td><td>0.564627</td><td>1.981376</td><td>0.420984</td><td>00:12</td></tr><tr><td>26</td><td>0.532286</td><td>2.019217</td><td>0.448033</td><td>00:12</td></tr><tr><td>27</td><td>0.502358</td><td>2.106662</td><td>0.449016</td><td>00:12</td></tr><tr><td>28</td><td>0.471355</td><td>1.918341</td><td>0.487377</td><td>00:12</td></tr><tr><td>29</td><td>0.437799</td><td>2.302520</td><td>0.434098</td><td>00:12</td></tr><tr><td>30</td><td>0.415745</td><td>2.315484</td><td>0.435410</td><td>00:12</td></tr><tr><td>31</td><td>0.390945</td><td>1.929175</td><td>0.494262</td><td>00:12</td></tr><tr><td>32</td><td>0.363011</td><td>2.233206</td><td>0.456557</td><td>00:11</td></tr><tr><td>33</td><td>0.334981</td><td>1.979938</td><td>0.489508</td><td>00:07</td></tr><tr><td>34</td><td>0.308682</td><td>2.075093</td><td>0.486557</td><td>00:08</td></tr><tr><td>35</td><td>0.286332</td><td>2.437981</td><td>0.394754</td><td>00:08</td></tr><tr><td>36</td><td>0.265230</td><td>2.723022</td><td>0.412459</td><td>00:08</td></tr><tr><td>37</td><td>0.245838</td><td>2.347927</td><td>0.475738</td><td>00:08</td></tr><tr><td>38</td><td>0.229432</td><td>2.704097</td><td>0.386557</td><td>00:08</td></tr><tr><td>39</td><td>0.216615</td><td>2.178247</td><td>0.482295</td><td>00:08</td></tr><tr><td>40</td><td>0.204428</td><td>2.211429</td><td>0.472295</td><td>00:08</td></tr><tr><td>41</td><td>0.190515</td><td>2.274863</td><td>0.448033</td><td>00:08</td></tr><tr><td>42</td><td>0.179082</td><td>2.288700</td><td>0.447705</td><td>00:09</td></tr><tr><td>43</td><td>0.169959</td><td>2.246226</td><td>0.462295</td><td>00:08</td></tr><tr><td>44</td><td>0.161488</td><td>2.340491</td><td>0.449016</td><td>00:08</td></tr><tr><td>45</td><td>0.154441</td><td>2.282892</td><td>0.454590</td><td>00:08</td></tr><tr><td>46</td><td>0.149192</td><td>2.221779</td><td>0.462623</td><td>00:09</td></tr><tr><td>47</td><td>0.145304</td><td>2.283635</td><td>0.455410</td><td>00:09</td></tr><tr><td>48</td><td>0.142182</td><td>2.280970</td><td>0.453607</td><td>00:07</td></tr><tr><td>49</td><td>0.140509</td><td>2.271822</td><td>0.456066</td><td>00:08</td></tr></tbody></table></div>

Better model found at epoch 0 with accuracy value: 0.30311474204063416.
Better model found at epoch 1 with accuracy value: 0.3844262361526489.
Better model found at epoch 2 with accuracy value: 0.4291803240776062.
Better model found at epoch 3 with accuracy value: 0.4786885380744934.
Better model found at epoch 4 with accuracy value: 0.5032786726951599.
Better model found at epoch 11 with accuracy value: 0.516229510307312.

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_bvp_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_bvp_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_bvp_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_bvp_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_bvp_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "synthetic_to_real",
  "native_modality": "bvp",
  "native_hz": 64,
  "channels": "BVP",
  "description": "BVP only",
  "input_shape_train_native_N_T_C": [
    30000,
    512,
    1
  ],
  "input_shape_test_native_N_T_C": [
    10063,
    512,
    1
  ],
  "input_shape_train_framework_N_C_T": [
    30000,
    1,
    512
  ],
  "input_shape_test_framework_N_C_T": [
    10063,
    1,
    512
  ],
  "epochs": 50,
  "best_epoch_by_val_accuracy": 12,
  "best_val_accuracy": 0.516229510307312,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_synthetic_to_real_bvp.pth",
  "used_saved_real_to_real_model": false,
  "training_reused_from_experiment": "",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.44857398390142106,
  "macro_precision": 0.4989269806038382,
  "macro_recall": 0.42336643882483105,
  "macro_f1": 0.4276318193652523,
  "weighted_precision": 0.4711049461302368,
  "weighted_recall": 0.44857398390142106,
  "weighted_f1": 0.4383550022418561,
  "balanced_accuracy": 0.42336643882483105
}

================================================================================
[tsai] real_plus_synthetic_to_real | bvp
================================================================================

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.843162</td><td>1.708715</td><td>0.385410</td><td>00:17</td></tr><tr><td>1</td><td>1.606564</td><td>1.509512</td><td>0.424098</td><td>00:16</td></tr><tr><td>2</td><td>1.404301</td><td>1.313354</td><td>0.527705</td><td>00:17</td></tr><tr><td>3</td><td>1.258647</td><td>1.400080</td><td>0.479344</td><td>00:17</td></tr><tr><td>4</td><td>1.157379</td><td>1.335176</td><td>0.542623</td><td>00:17</td></tr><tr><td>5</td><td>1.083167</td><td>1.540684</td><td>0.469016</td><td>00:17</td></tr><tr><td>6</td><td>1.012669</td><td>1.829353</td><td>0.415246</td><td>00:17</td></tr><tr><td>7</td><td>0.973849</td><td>1.455715</td><td>0.428033</td><td>00:19</td></tr><tr><td>8</td><td>0.921851</td><td>1.451130</td><td>0.510656</td><td>00:25</td></tr><tr><td>9</td><td>0.879915</td><td>1.438513</td><td>0.487705</td><td>00:25</td></tr><tr><td>10</td><td>0.827521</td><td>1.692730</td><td>0.503934</td><td>00:25</td></tr><tr><td>11</td><td>0.780462</td><td>1.742414</td><td>0.433934</td><td>00:23</td></tr><tr><td>12</td><td>0.734204</td><td>1.916701</td><td>0.454918</td><td>00:25</td></tr><tr><td>13</td><td>0.690712</td><td>2.635705</td><td>0.420000</td><td>00:25</td></tr><tr><td>14</td><td>0.621776</td><td>2.123329</td><td>0.402131</td><td>00:25</td></tr><tr><td>15</td><td>0.575244</td><td>2.034169</td><td>0.435410</td><td>00:25</td></tr><tr><td>16</td><td>0.531967</td><td>2.345461</td><td>0.465574</td><td>00:25</td></tr><tr><td>17</td><td>0.487285</td><td>1.964971</td><td>0.517049</td><td>00:25</td></tr><tr><td>18</td><td>0.453579</td><td>2.624811</td><td>0.447869</td><td>00:25</td></tr><tr><td>19</td><td>0.416190</td><td>2.697285</td><td>0.390000</td><td>00:25</td></tr><tr><td>20</td><td>0.380820</td><td>2.075087</td><td>0.503115</td><td>00:18</td></tr><tr><td>21</td><td>0.361522</td><td>3.074938</td><td>0.393770</td><td>00:13</td></tr><tr><td>22</td><td>0.332068</td><td>2.102034</td><td>0.481967</td><td>00:13</td></tr><tr><td>23</td><td>0.304081</td><td>2.187469</td><td>0.467377</td><td>00:13</td></tr><tr><td>24</td><td>0.284105</td><td>2.364479</td><td>0.446066</td><td>00:13</td></tr><tr><td>25</td><td>0.255041</td><td>2.246927</td><td>0.480656</td><td>00:13</td></tr><tr><td>26</td><td>0.233333</td><td>2.576461</td><td>0.454590</td><td>00:13</td></tr><tr><td>27</td><td>0.219473</td><td>2.572398</td><td>0.402623</td><td>00:13</td></tr><tr><td>28</td><td>0.195530</td><td>2.300554</td><td>0.489508</td><td>00:13</td></tr><tr><td>29</td><td>0.183245</td><td>2.554958</td><td>0.451639</td><td>00:13</td></tr><tr><td>30</td><td>0.164707</td><td>2.383029</td><td>0.484590</td><td>00:13</td></tr><tr><td>31</td><td>0.150258</td><td>2.788119</td><td>0.447377</td><td>00:13</td></tr><tr><td>32</td><td>0.132752</td><td>2.890039</td><td>0.440000</td><td>00:13</td></tr><tr><td>33</td><td>0.118077</td><td>3.010958</td><td>0.421148</td><td>00:13</td></tr><tr><td>34</td><td>0.103894</td><td>2.511498</td><td>0.477705</td><td>00:13</td></tr><tr><td>35</td><td>0.092578</td><td>2.340973</td><td>0.490000</td><td>00:13</td></tr><tr><td>36</td><td>0.081380</td><td>2.433236</td><td>0.476066</td><td>00:13</td></tr><tr><td>37</td><td>0.071172</td><td>2.816986</td><td>0.473934</td><td>00:13</td></tr><tr><td>38</td><td>0.064042</td><td>2.529777</td><td>0.493607</td><td>00:13</td></tr><tr><td>39</td><td>0.056527</td><td>3.183676</td><td>0.437049</td><td>00:13</td></tr><tr><td>40</td><td>0.049751</td><td>2.682289</td><td>0.467377</td><td>00:13</td></tr><tr><td>41</td><td>0.044722</td><td>2.570023</td><td>0.481475</td><td>00:13</td></tr><tr><td>42</td><td>0.038796</td><td>2.746381</td><td>0.468689</td><td>00:13</td></tr><tr><td>43</td><td>0.034868</td><td>2.792361</td><td>0.459672</td><td>00:13</td></tr><tr><td>44</td><td>0.031752</td><td>2.817849</td><td>0.466066</td><td>00:13</td></tr><tr><td>45</td><td>0.029556</td><td>2.849579</td><td>0.475082</td><td>00:13</td></tr><tr><td>46</td><td>0.027736</td><td>2.790229</td><td>0.471475</td><td>00:13</td></tr><tr><td>47</td><td>0.026424</td><td>2.792611</td><td>0.472459</td><td>00:13</td></tr><tr><td>48</td><td>0.025212</td><td>2.786109</td><td>0.470984</td><td>00:13</td></tr><tr><td>49</td><td>0.024639</td><td>2.779324</td><td>0.472787</td><td>00:13</td></tr></tbody></table></div>

Better model found at epoch 0 with accuracy value: 0.3854098320007324.
Better model found at epoch 1 with accuracy value: 0.4240983724594116.
Better model found at epoch 2 with accuracy value: 0.5277048945426941.
Better model found at epoch 4 with accuracy value: 0.5426229238510132.

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_bvp_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_bvp_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_bvp_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_bvp_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_bvp_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_plus_synthetic_to_real",
  "native_modality": "bvp",
  "native_hz": 64,
  "channels": "BVP",
  "description": "BVP only",
  "input_shape_train_native_N_T_C": [
    60762,
    512,
    1
  ],
  "input_shape_test_native_N_T_C": [
    10063,
    512,
    1
  ],
  "input_shape_train_framework_N_C_T": [
    60762,
    1,
    512
  ],
  "input_shape_test_framework_N_C_T": [
    10063,
    1,
    512
  ],
  "epochs": 50,
  "best_epoch_by_val_accuracy": 5,
  "best_val_accuracy": 0.5426229238510132,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_plus_synthetic_to_real_bvp.pth",
  "used_saved_real_to_real_model": false,
  "training_reused_from_experiment": "",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.4886216833946139,
  "macro_precision": 0.572163437221948,
  "macro_recall": 0.4257562007331783,
  "macro_f1": 0.4441604712607341,
  "weighted_precision": 0.5344423871730605,
  "weighted_recall": 0.4886216833946139,
  "weighted_f1": 0.4686940428802761,
  "balanced_accuracy": 0.4257562007331783
}

================================================================================
[tsai] real_to_real | eda
================================================================================
Reusing saved tsai Real->Real metrics.

================================================================================
[tsai] real_to_synthetic | eda
================================================================================
Copied external tsai model into current output folder: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_to_real_eda.pth
Loading tsai Real->Real model: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_to_real_eda.pth

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_eda_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_eda_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_eda_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_eda_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_eda_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_to_synthetic",
  "native_modality": "eda",
  "native_hz": 4,
  "channels": "EDA",
  "description": "EDA only",
  "input_shape_train_native_N_T_C": [
    30762,
    32,
    1
  ],
  "input_shape_test_native_N_T_C": [
    9000,
    32,
    1
  ],
  "input_shape_train_framework_N_C_T": [
    30762,
    1,
    32
  ],
  "input_shape_test_framework_N_C_T": [
    9000,
    1,
    32
  ],
  "epochs": 0,
  "best_epoch_by_val_accuracy": 49,
  "best_val_accuracy": 0.5367212891578674,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_to_real_eda.pth",
  "used_saved_real_to_real_model": true,
  "training_reused_from_experiment": "real_to_real",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.23722222222222222,
  "macro_precision": 0.24012209088436232,
  "macro_recall": 0.2642240786412887,
  "macro_f1": 0.20043074904518796,
  "weighted_precision": 0.28635330605311915,
  "weighted_recall": 0.23722222222222222,
  "weighted_f1": 0.20426840917596234,
  "balanced_accuracy": 0.2642240786412887
}

================================================================================
[tsai] synthetic_to_real | eda
================================================================================

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.815222</td><td>1.952024</td><td>0.184426</td><td>00:11</td></tr><tr><td>1</td><td>1.700022</td><td>1.444966</td><td>0.448033</td><td>00:11</td></tr><tr><td>2</td><td>1.637473</td><td>1.373170</td><td>0.441967</td><td>00:11</td></tr><tr><td>3</td><td>1.598943</td><td>1.713320</td><td>0.358689</td><td>00:11</td></tr><tr><td>4</td><td>1.579607</td><td>1.567706</td><td>0.433770</td><td>00:11</td></tr><tr><td>5</td><td>1.566136</td><td>1.750071</td><td>0.393607</td><td>00:11</td></tr><tr><td>6</td><td>1.549132</td><td>1.928065</td><td>0.356230</td><td>00:11</td></tr><tr><td>7</td><td>1.541432</td><td>1.428087</td><td>0.460820</td><td>00:11</td></tr><tr><td>8</td><td>1.528475</td><td>7.981460</td><td>0.264754</td><td>00:11</td></tr><tr><td>9</td><td>1.531349</td><td>1.453182</td><td>0.409016</td><td>00:11</td></tr><tr><td>10</td><td>1.520504</td><td>1.479778</td><td>0.467213</td><td>00:11</td></tr><tr><td>11</td><td>1.509469</td><td>1.398640</td><td>0.485246</td><td>00:11</td></tr><tr><td>12</td><td>1.496486</td><td>1.911111</td><td>0.432787</td><td>00:11</td></tr><tr><td>13</td><td>1.494828</td><td>1.501106</td><td>0.498033</td><td>00:11</td></tr><tr><td>14</td><td>1.484382</td><td>1.752584</td><td>0.385082</td><td>00:11</td></tr><tr><td>15</td><td>1.473102</td><td>2.024938</td><td>0.452787</td><td>00:11</td></tr><tr><td>16</td><td>1.457739</td><td>4.402077</td><td>0.399508</td><td>00:11</td></tr><tr><td>17</td><td>1.443486</td><td>2.443886</td><td>0.421311</td><td>00:11</td></tr><tr><td>18</td><td>1.431314</td><td>1.684871</td><td>0.465902</td><td>00:11</td></tr><tr><td>19</td><td>1.416422</td><td>2.699889</td><td>0.265082</td><td>00:11</td></tr><tr><td>20</td><td>1.409104</td><td>15.109109</td><td>0.318361</td><td>00:11</td></tr><tr><td>21</td><td>1.418012</td><td>2.184451</td><td>0.401967</td><td>00:11</td></tr><tr><td>22</td><td>1.407948</td><td>2.618802</td><td>0.405574</td><td>00:11</td></tr><tr><td>23</td><td>1.390752</td><td>1.817308</td><td>0.410164</td><td>00:11</td></tr><tr><td>24</td><td>1.370185</td><td>2.062010</td><td>0.406885</td><td>00:11</td></tr><tr><td>25</td><td>1.348704</td><td>3.329812</td><td>0.316066</td><td>00:11</td></tr><tr><td>26</td><td>1.323804</td><td>3.038370</td><td>0.436557</td><td>00:11</td></tr><tr><td>27</td><td>1.297895</td><td>1.662256</td><td>0.434590</td><td>00:11</td></tr><tr><td>28</td><td>1.276769</td><td>3.322520</td><td>0.432951</td><td>00:11</td></tr><tr><td>29</td><td>1.255968</td><td>8.949919</td><td>0.240328</td><td>00:11</td></tr><tr><td>30</td><td>1.241227</td><td>2.513379</td><td>0.304754</td><td>00:11</td></tr><tr><td>31</td><td>1.228424</td><td>2.349146</td><td>0.458361</td><td>00:11</td></tr><tr><td>32</td><td>1.216912</td><td>2.721049</td><td>0.468197</td><td>00:11</td></tr><tr><td>33</td><td>1.201487</td><td>2.745145</td><td>0.364754</td><td>00:11</td></tr><tr><td>34</td><td>1.186421</td><td>3.331242</td><td>0.403771</td><td>00:11</td></tr><tr><td>35</td><td>1.173289</td><td>2.799664</td><td>0.446066</td><td>00:11</td></tr><tr><td>36</td><td>1.159922</td><td>2.805542</td><td>0.433115</td><td>00:11</td></tr><tr><td>37</td><td>1.146273</td><td>2.029567</td><td>0.471311</td><td>00:11</td></tr><tr><td>38</td><td>1.134469</td><td>1.769283</td><td>0.355246</td><td>00:11</td></tr><tr><td>39</td><td>1.122518</td><td>1.874019</td><td>0.487541</td><td>00:11</td></tr><tr><td>40</td><td>1.111493</td><td>1.763120</td><td>0.406229</td><td>00:11</td></tr><tr><td>41</td><td>1.099734</td><td>2.194485</td><td>0.470328</td><td>00:11</td></tr><tr><td>42</td><td>1.091944</td><td>2.041866</td><td>0.419344</td><td>00:11</td></tr><tr><td>43</td><td>1.084280</td><td>1.961226</td><td>0.460164</td><td>00:11</td></tr><tr><td>44</td><td>1.076158</td><td>2.221742</td><td>0.464426</td><td>00:11</td></tr><tr><td>45</td><td>1.069989</td><td>2.474288</td><td>0.445574</td><td>00:11</td></tr><tr><td>46</td><td>1.065305</td><td>2.347035</td><td>0.458197</td><td>00:11</td></tr><tr><td>47</td><td>1.061419</td><td>1.704535</td><td>0.457869</td><td>00:11</td></tr><tr><td>48</td><td>1.058388</td><td>2.060329</td><td>0.457869</td><td>00:11</td></tr><tr><td>49</td><td>1.055870</td><td>2.050147</td><td>0.457869</td><td>00:11</td></tr></tbody></table></div>

Better model found at epoch 0 with accuracy value: 0.1844262331724167.
Better model found at epoch 1 with accuracy value: 0.44803279638290405.
Better model found at epoch 7 with accuracy value: 0.46081966161727905.
Better model found at epoch 10 with accuracy value: 0.46721312403678894.
Better model found at epoch 11 with accuracy value: 0.4852459132671356.
Better model found at epoch 13 with accuracy value: 0.4980327785015106.

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_eda_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_eda_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_eda_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_eda_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_eda_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "synthetic_to_real",
  "native_modality": "eda",
  "native_hz": 4,
  "channels": "EDA",
  "description": "EDA only",
  "input_shape_train_native_N_T_C": [
    30000,
    32,
    1
  ],
  "input_shape_test_native_N_T_C": [
    10063,
    32,
    1
  ],
  "input_shape_train_framework_N_C_T": [
    30000,
    1,
    32
  ],
  "input_shape_test_framework_N_C_T": [
    10063,
    1,
    32
  ],
  "epochs": 50,
  "best_epoch_by_val_accuracy": 14,
  "best_val_accuracy": 0.4980327785015106,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_synthetic_to_real_eda.pth",
  "used_saved_real_to_real_model": false,
  "training_reused_from_experiment": "",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.3324058431879161,
  "macro_precision": 0.2090592164992573,
  "macro_recall": 0.2993548592639479,
  "macro_f1": 0.20790302973313382,
  "weighted_precision": 0.2528942879486846,
  "weighted_recall": 0.3324058431879161,
  "weighted_f1": 0.25795995413331024,
  "balanced_accuracy": 0.2993548592639479
}

================================================================================
[tsai] real_plus_synthetic_to_real | eda
================================================================================

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.720415</td><td>1.480329</td><td>0.462459</td><td>00:22</td></tr><tr><td>1</td><td>1.635856</td><td>1.434403</td><td>0.468197</td><td>00:22</td></tr><tr><td>2</td><td>1.595353</td><td>1.404120</td><td>0.482951</td><td>00:22</td></tr><tr><td>3</td><td>1.564988</td><td>1.417636</td><td>0.454590</td><td>00:22</td></tr><tr><td>4</td><td>1.538558</td><td>1.510260</td><td>0.467869</td><td>00:22</td></tr><tr><td>5</td><td>1.522446</td><td>1.545361</td><td>0.387541</td><td>00:22</td></tr><tr><td>6</td><td>1.506993</td><td>2.951174</td><td>0.372459</td><td>00:22</td></tr><tr><td>7</td><td>1.494660</td><td>2.891628</td><td>0.358197</td><td>00:22</td></tr><tr><td>8</td><td>1.477664</td><td>3.113627</td><td>0.304098</td><td>00:22</td></tr><tr><td>9</td><td>1.471388</td><td>2.663896</td><td>0.383115</td><td>00:22</td></tr><tr><td>10</td><td>1.460256</td><td>2.298547</td><td>0.436066</td><td>00:22</td></tr><tr><td>11</td><td>1.439383</td><td>2.297424</td><td>0.329836</td><td>00:22</td></tr><tr><td>12</td><td>1.427316</td><td>8.866204</td><td>0.217213</td><td>00:22</td></tr><tr><td>13</td><td>1.416549</td><td>4.567428</td><td>0.286393</td><td>00:22</td></tr><tr><td>14</td><td>1.412714</td><td>3.750523</td><td>0.311475</td><td>00:22</td></tr><tr><td>15</td><td>1.395514</td><td>8.445724</td><td>0.352951</td><td>00:22</td></tr><tr><td>16</td><td>1.388156</td><td>4.238888</td><td>0.330328</td><td>00:22</td></tr><tr><td>17</td><td>1.370069</td><td>1.342261</td><td>0.543279</td><td>00:22</td></tr><tr><td>18</td><td>1.379307</td><td>4.677209</td><td>0.319836</td><td>00:22</td></tr><tr><td>19</td><td>1.353743</td><td>1.678545</td><td>0.405738</td><td>00:22</td></tr><tr><td>20</td><td>1.344754</td><td>2.154721</td><td>0.306230</td><td>00:22</td></tr><tr><td>21</td><td>1.333262</td><td>4.450672</td><td>0.346393</td><td>00:22</td></tr><tr><td>22</td><td>1.312773</td><td>2.332064</td><td>0.406885</td><td>00:22</td></tr><tr><td>23</td><td>1.300321</td><td>3.871718</td><td>0.324262</td><td>00:22</td></tr><tr><td>24</td><td>1.292945</td><td>2.278924</td><td>0.388033</td><td>00:22</td></tr><tr><td>25</td><td>1.282189</td><td>2.910571</td><td>0.276885</td><td>00:22</td></tr><tr><td>26</td><td>1.272605</td><td>3.787525</td><td>0.331967</td><td>00:22</td></tr><tr><td>27</td><td>1.259797</td><td>1.624562</td><td>0.411967</td><td>00:22</td></tr><tr><td>28</td><td>1.254052</td><td>5.999341</td><td>0.162295</td><td>00:22</td></tr><tr><td>29</td><td>1.243762</td><td>1.968561</td><td>0.377705</td><td>00:22</td></tr><tr><td>30</td><td>1.228630</td><td>3.242481</td><td>0.279344</td><td>00:22</td></tr><tr><td>31</td><td>1.211457</td><td>1.607587</td><td>0.464754</td><td>00:22</td></tr><tr><td>32</td><td>1.199529</td><td>2.028733</td><td>0.265902</td><td>00:22</td></tr><tr><td>33</td><td>1.191035</td><td>1.867426</td><td>0.409508</td><td>00:22</td></tr><tr><td>34</td><td>1.179781</td><td>1.620638</td><td>0.409344</td><td>00:22</td></tr><tr><td>35</td><td>1.167624</td><td>1.499520</td><td>0.478689</td><td>00:22</td></tr><tr><td>36</td><td>1.157348</td><td>2.796044</td><td>0.413115</td><td>00:22</td></tr><tr><td>37</td><td>1.149405</td><td>1.892437</td><td>0.420492</td><td>00:22</td></tr><tr><td>38</td><td>1.135841</td><td>1.661738</td><td>0.461967</td><td>00:22</td></tr><tr><td>39</td><td>1.124786</td><td>1.471597</td><td>0.510984</td><td>00:22</td></tr><tr><td>40</td><td>1.115393</td><td>2.239497</td><td>0.412459</td><td>00:22</td></tr><tr><td>41</td><td>1.107499</td><td>1.866495</td><td>0.404918</td><td>00:22</td></tr><tr><td>42</td><td>1.102222</td><td>1.992224</td><td>0.388361</td><td>00:22</td></tr><tr><td>43</td><td>1.091602</td><td>1.957280</td><td>0.431148</td><td>00:22</td></tr><tr><td>44</td><td>1.084049</td><td>1.578187</td><td>0.550492</td><td>00:22</td></tr><tr><td>45</td><td>1.080725</td><td>1.741961</td><td>0.431803</td><td>00:22</td></tr><tr><td>46</td><td>1.076567</td><td>1.580211</td><td>0.528197</td><td>00:22</td></tr><tr><td>47</td><td>1.074714</td><td>1.557435</td><td>0.532131</td><td>00:22</td></tr><tr><td>48</td><td>1.071611</td><td>1.627548</td><td>0.525246</td><td>00:22</td></tr><tr><td>49</td><td>1.069448</td><td>1.610688</td><td>0.535082</td><td>00:22</td></tr></tbody></table></div>

Better model found at epoch 0 with accuracy value: 0.4624590277671814.
Better model found at epoch 1 with accuracy value: 0.46819671988487244.
Better model found at epoch 2 with accuracy value: 0.4829508066177368.
Better model found at epoch 17 with accuracy value: 0.543278694152832.
Better model found at epoch 44 with accuracy value: 0.5504918098449707.

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_eda_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_eda_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_eda_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_eda_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_eda_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_plus_synthetic_to_real",
  "native_modality": "eda",
  "native_hz": 4,
  "channels": "EDA",
  "description": "EDA only",
  "input_shape_train_native_N_T_C": [
    60762,
    32,
    1
  ],
  "input_shape_test_native_N_T_C": [
    10063,
    32,
    1
  ],
  "input_shape_train_framework_N_C_T": [
    60762,
    1,
    32
  ],
  "input_shape_test_framework_N_C_T": [
    10063,
    1,
    32
  ],
  "epochs": 50,
  "best_epoch_by_val_accuracy": 45,
  "best_val_accuracy": 0.5504918098449707,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_plus_synthetic_to_real_eda.pth",
  "used_saved_real_to_real_model": false,
  "training_reused_from_experiment": "",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.2704958759813177,
  "macro_precision": 0.27192199397553896,
  "macro_recall": 0.2637439340941805,
  "macro_f1": 0.21900818312211015,
  "weighted_precision": 0.2910804209580314,
  "weighted_recall": 0.2704958759813177,
  "weighted_f1": 0.24519081220250488,
  "balanced_accuracy": 0.2637439340941805
}

================================================================================
[tsai] real_to_real | temp
================================================================================
Reusing saved tsai Real->Real metrics.

================================================================================
[tsai] real_to_synthetic | temp
================================================================================
Copied external tsai model into current output folder: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_to_real_temp.pth
Loading tsai Real->Real model: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_to_real_temp.pth

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_temp_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_temp_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_temp_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_temp_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_temp_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_to_synthetic",
  "native_modality": "temp",
  "native_hz": 4,
  "channels": "TEMP",
  "description": "TEMP only",
  "input_shape_train_native_N_T_C": [
    30762,
    32,
    1
  ],
  "input_shape_test_native_N_T_C": [
    9000,
    32,
    1
  ],
  "input_shape_train_framework_N_C_T": [
    30762,
    1,
    32
  ],
  "input_shape_test_framework_N_C_T": [
    9000,
    1,
    32
  ],
  "epochs": 0,
  "best_epoch_by_val_accuracy": 25,
  "best_val_accuracy": 0.3852458894252777,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_to_real_temp.pth",
  "used_saved_real_to_real_model": true,
  "training_reused_from_experiment": "real_to_real",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.3635555555555556,
  "macro_precision": 0.36077430619978823,
  "macro_recall": 0.295782378828804,
  "macro_f1": 0.28817121211503044,
  "weighted_precision": 0.38153078160286946,
  "weighted_recall": 0.3635555555555556,
  "weighted_f1": 0.3269054209967614,
  "balanced_accuracy": 0.295782378828804
}

================================================================================
[tsai] synthetic_to_real | temp
================================================================================

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.848642</td><td>1.990881</td><td>0.196393</td><td>00:11</td></tr><tr><td>1</td><td>1.715968</td><td>1.551806</td><td>0.372295</td><td>00:11</td></tr><tr><td>2</td><td>1.650741</td><td>1.562652</td><td>0.305246</td><td>00:11</td></tr><tr><td>3</td><td>1.612194</td><td>1.535177</td><td>0.399344</td><td>00:11</td></tr><tr><td>4</td><td>1.590562</td><td>1.570164</td><td>0.283771</td><td>00:11</td></tr><tr><td>5</td><td>1.576165</td><td>1.886605</td><td>0.341967</td><td>00:11</td></tr><tr><td>6</td><td>1.562700</td><td>1.693367</td><td>0.273443</td><td>00:11</td></tr><tr><td>7</td><td>1.550422</td><td>1.696638</td><td>0.282459</td><td>00:11</td></tr><tr><td>8</td><td>1.544336</td><td>2.302433</td><td>0.207541</td><td>00:11</td></tr><tr><td>9</td><td>1.540137</td><td>1.788717</td><td>0.322459</td><td>00:11</td></tr><tr><td>10</td><td>1.535335</td><td>2.729294</td><td>0.256885</td><td>00:11</td></tr><tr><td>11</td><td>1.532589</td><td>2.305514</td><td>0.210000</td><td>00:11</td></tr><tr><td>12</td><td>1.527038</td><td>1.792606</td><td>0.241311</td><td>00:11</td></tr><tr><td>13</td><td>1.512003</td><td>2.473985</td><td>0.305410</td><td>00:11</td></tr><tr><td>14</td><td>1.498877</td><td>10.505644</td><td>0.169016</td><td>00:11</td></tr><tr><td>15</td><td>1.498602</td><td>2.067929</td><td>0.333279</td><td>00:11</td></tr><tr><td>16</td><td>1.484321</td><td>3.780989</td><td>0.287869</td><td>00:11</td></tr><tr><td>17</td><td>1.482046</td><td>2.477545</td><td>0.227213</td><td>00:11</td></tr><tr><td>18</td><td>1.472917</td><td>2.156221</td><td>0.346557</td><td>00:11</td></tr><tr><td>19</td><td>1.456690</td><td>3.003647</td><td>0.330328</td><td>00:11</td></tr><tr><td>20</td><td>1.434947</td><td>2.972545</td><td>0.331148</td><td>00:11</td></tr><tr><td>21</td><td>1.427830</td><td>2.281331</td><td>0.345574</td><td>00:11</td></tr><tr><td>22</td><td>1.411514</td><td>2.232238</td><td>0.295082</td><td>00:11</td></tr><tr><td>23</td><td>1.398635</td><td>2.618379</td><td>0.370492</td><td>00:11</td></tr><tr><td>24</td><td>1.382212</td><td>5.323696</td><td>0.351311</td><td>00:11</td></tr><tr><td>25</td><td>1.362843</td><td>3.585421</td><td>0.355082</td><td>00:11</td></tr><tr><td>26</td><td>1.339656</td><td>10.163588</td><td>0.207377</td><td>00:11</td></tr><tr><td>27</td><td>1.335581</td><td>3.739051</td><td>0.327869</td><td>00:11</td></tr><tr><td>28</td><td>1.325933</td><td>5.440699</td><td>0.289508</td><td>00:11</td></tr><tr><td>29</td><td>1.312386</td><td>8.163543</td><td>0.159836</td><td>00:11</td></tr><tr><td>30</td><td>1.297924</td><td>9.753522</td><td>0.216721</td><td>00:11</td></tr><tr><td>31</td><td>1.285436</td><td>3.009957</td><td>0.310492</td><td>00:11</td></tr><tr><td>32</td><td>1.277259</td><td>7.567861</td><td>0.241967</td><td>00:11</td></tr><tr><td>33</td><td>1.270097</td><td>4.789240</td><td>0.288525</td><td>00:11</td></tr><tr><td>34</td><td>1.261718</td><td>6.542915</td><td>0.363115</td><td>00:11</td></tr><tr><td>35</td><td>1.252636</td><td>3.969809</td><td>0.300656</td><td>00:11</td></tr><tr><td>36</td><td>1.245784</td><td>5.525165</td><td>0.211148</td><td>00:11</td></tr><tr><td>37</td><td>1.240211</td><td>3.758971</td><td>0.294426</td><td>00:11</td></tr><tr><td>38</td><td>1.233895</td><td>5.239677</td><td>0.378033</td><td>00:11</td></tr><tr><td>39</td><td>1.227893</td><td>3.815494</td><td>0.241803</td><td>00:11</td></tr><tr><td>40</td><td>1.222337</td><td>4.675764</td><td>0.271803</td><td>00:11</td></tr><tr><td>41</td><td>1.214366</td><td>3.087204</td><td>0.390820</td><td>00:11</td></tr><tr><td>42</td><td>1.209650</td><td>4.214728</td><td>0.323279</td><td>00:11</td></tr><tr><td>43</td><td>1.207487</td><td>1.745401</td><td>0.405082</td><td>00:11</td></tr><tr><td>44</td><td>1.203228</td><td>2.851300</td><td>0.307705</td><td>00:11</td></tr><tr><td>45</td><td>1.200676</td><td>2.716070</td><td>0.394262</td><td>00:11</td></tr><tr><td>46</td><td>1.196835</td><td>2.278487</td><td>0.387705</td><td>00:11</td></tr><tr><td>47</td><td>1.193788</td><td>1.927523</td><td>0.365574</td><td>00:11</td></tr><tr><td>48</td><td>1.192823</td><td>1.894667</td><td>0.410984</td><td>00:11</td></tr><tr><td>49</td><td>1.191373</td><td>1.968086</td><td>0.392131</td><td>00:11</td></tr></tbody></table></div>

Better model found at epoch 0 with accuracy value: 0.1963934451341629.
Better model found at epoch 1 with accuracy value: 0.372295081615448.
Better model found at epoch 3 with accuracy value: 0.399344265460968.
Better model found at epoch 43 with accuracy value: 0.40508195757865906.
Better model found at epoch 48 with accuracy value: 0.4109835922718048.

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_temp_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_temp_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_temp_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_temp_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_synthetic_to_real_temp_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "synthetic_to_real",
  "native_modality": "temp",
  "native_hz": 4,
  "channels": "TEMP",
  "description": "TEMP only",
  "input_shape_train_native_N_T_C": [
    30000,
    32,
    1
  ],
  "input_shape_test_native_N_T_C": [
    10063,
    32,
    1
  ],
  "input_shape_train_framework_N_C_T": [
    30000,
    1,
    32
  ],
  "input_shape_test_framework_N_C_T": [
    10063,
    1,
    32
  ],
  "epochs": 50,
  "best_epoch_by_val_accuracy": 49,
  "best_val_accuracy": 0.4109835922718048,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_synthetic_to_real_temp.pth",
  "used_saved_real_to_real_model": false,
  "training_reused_from_experiment": "",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.17638875086952202,
  "macro_precision": 0.28840955012577274,
  "macro_recall": 0.2274809504818927,
  "macro_f1": 0.14653207722234304,
  "weighted_precision": 0.33175883129329453,
  "weighted_recall": 0.17638875086952202,
  "weighted_f1": 0.14912153336573877,
  "balanced_accuracy": 0.2274809504818927
}

================================================================================
[tsai] real_plus_synthetic_to_real | temp
================================================================================

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.720159</td><td>1.593584</td><td>0.358197</td><td>00:22</td></tr><tr><td>1</td><td>1.639294</td><td>1.567875</td><td>0.407869</td><td>00:22</td></tr><tr><td>2</td><td>1.604224</td><td>1.614283</td><td>0.289672</td><td>00:22</td></tr><tr><td>3</td><td>1.584094</td><td>1.745996</td><td>0.263607</td><td>00:22</td></tr><tr><td>4</td><td>1.564189</td><td>1.606914</td><td>0.355082</td><td>00:22</td></tr><tr><td>5</td><td>1.547469</td><td>1.964954</td><td>0.330000</td><td>00:22</td></tr><tr><td>6</td><td>1.536684</td><td>2.276822</td><td>0.221967</td><td>00:22</td></tr><tr><td>7</td><td>1.532139</td><td>2.758578</td><td>0.238361</td><td>00:22</td></tr><tr><td>8</td><td>1.525781</td><td>1.818734</td><td>0.347049</td><td>00:22</td></tr><tr><td>9</td><td>1.522285</td><td>2.334329</td><td>0.336721</td><td>00:22</td></tr><tr><td>10</td><td>1.516349</td><td>1.675669</td><td>0.321148</td><td>00:22</td></tr><tr><td>11</td><td>1.523188</td><td>3.041232</td><td>0.264754</td><td>00:22</td></tr><tr><td>12</td><td>1.516734</td><td>1.850807</td><td>0.312787</td><td>00:22</td></tr><tr><td>13</td><td>1.509742</td><td>4.105322</td><td>0.201639</td><td>00:22</td></tr><tr><td>14</td><td>1.502578</td><td>1.777611</td><td>0.330328</td><td>00:22</td></tr><tr><td>15</td><td>1.496246</td><td>3.629897</td><td>0.200656</td><td>00:22</td></tr><tr><td>16</td><td>1.494732</td><td>4.871512</td><td>0.136557</td><td>00:22</td></tr><tr><td>17</td><td>1.488819</td><td>2.019666</td><td>0.308033</td><td>00:22</td></tr><tr><td>18</td><td>1.481619</td><td>1.828516</td><td>0.350820</td><td>00:22</td></tr><tr><td>19</td><td>1.477158</td><td>4.869492</td><td>0.130656</td><td>00:22</td></tr><tr><td>20</td><td>1.471619</td><td>2.364656</td><td>0.327705</td><td>00:22</td></tr><tr><td>21</td><td>1.465716</td><td>2.424759</td><td>0.159672</td><td>00:22</td></tr><tr><td>22</td><td>1.457168</td><td>6.822350</td><td>0.185082</td><td>00:22</td></tr><tr><td>23</td><td>1.448860</td><td>3.394695</td><td>0.093443</td><td>00:22</td></tr><tr><td>24</td><td>1.443351</td><td>1.879831</td><td>0.306885</td><td>00:22</td></tr><tr><td>25</td><td>1.438576</td><td>2.112189</td><td>0.218361</td><td>00:22</td></tr><tr><td>26</td><td>1.442502</td><td>2.063449</td><td>0.216557</td><td>00:22</td></tr><tr><td>27</td><td>1.432830</td><td>2.506120</td><td>0.202295</td><td>00:22</td></tr><tr><td>28</td><td>1.425434</td><td>2.862409</td><td>0.135902</td><td>00:22</td></tr><tr><td>29</td><td>1.415559</td><td>7.560222</td><td>0.171475</td><td>00:22</td></tr><tr><td>30</td><td>1.413834</td><td>2.307195</td><td>0.217541</td><td>00:22</td></tr><tr><td>31</td><td>1.407072</td><td>1.939706</td><td>0.305246</td><td>00:22</td></tr><tr><td>32</td><td>1.396979</td><td>2.053972</td><td>0.283934</td><td>00:22</td></tr><tr><td>33</td><td>1.389416</td><td>1.944180</td><td>0.322459</td><td>00:22</td></tr><tr><td>34</td><td>1.383220</td><td>7.368420</td><td>0.217377</td><td>00:22</td></tr><tr><td>35</td><td>1.377151</td><td>1.773787</td><td>0.329508</td><td>00:22</td></tr><tr><td>36</td><td>1.367900</td><td>1.786933</td><td>0.311475</td><td>00:22</td></tr><tr><td>37</td><td>1.365126</td><td>4.077385</td><td>0.231148</td><td>00:22</td></tr><tr><td>38</td><td>1.357514</td><td>4.762042</td><td>0.250820</td><td>00:22</td></tr><tr><td>39</td><td>1.349507</td><td>1.968929</td><td>0.307213</td><td>00:22</td></tr><tr><td>40</td><td>1.348399</td><td>2.843581</td><td>0.320820</td><td>00:22</td></tr><tr><td>41</td><td>1.343774</td><td>3.892492</td><td>0.242131</td><td>00:22</td></tr><tr><td>42</td><td>1.337976</td><td>1.960901</td><td>0.326066</td><td>00:22</td></tr><tr><td>43</td><td>1.332198</td><td>1.780022</td><td>0.332787</td><td>00:22</td></tr><tr><td>44</td><td>1.329587</td><td>1.703253</td><td>0.345082</td><td>00:22</td></tr><tr><td>45</td><td>1.326496</td><td>1.708879</td><td>0.356557</td><td>00:22</td></tr><tr><td>46</td><td>1.323512</td><td>1.679551</td><td>0.362295</td><td>00:22</td></tr><tr><td>47</td><td>1.321058</td><td>1.683174</td><td>0.364426</td><td>00:22</td></tr><tr><td>48</td><td>1.320818</td><td>1.695114</td><td>0.365902</td><td>00:22</td></tr><tr><td>49</td><td>1.318207</td><td>1.692941</td><td>0.361475</td><td>00:22</td></tr></tbody></table></div>

Better model found at epoch 0 with accuracy value: 0.3581967353820801.
Better model found at epoch 1 with accuracy value: 0.4078688621520996.

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_temp_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_temp_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_temp_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_temp_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_plus_synthetic_to_real_temp_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_plus_synthetic_to_real",
  "native_modality": "temp",
  "native_hz": 4,
  "channels": "TEMP",
  "description": "TEMP only",
  "input_shape_train_native_N_T_C": [
    60762,
    32,
    1
  ],
  "input_shape_test_native_N_T_C": [
    10063,
    32,
    1
  ],
  "input_shape_train_framework_N_C_T": [
    60762,
    1,
    32
  ],
  "input_shape_test_framework_N_C_T": [
    10063,
    1,
    32
  ],
  "epochs": 50,
  "best_epoch_by_val_accuracy": 2,
  "best_val_accuracy": 0.4078688621520996,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_plus_synthetic_to_real_temp.pth",
  "used_saved_real_to_real_model": false,
  "training_reused_from_experiment": "",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.25091920898340453,
  "macro_precision": 0.10646632461613786,
  "macro_recall": 0.21108497081511987,
  "macro_f1": 0.1265452657090242,
  "weighted_precision": 0.1837954224741018,
  "weighted_recall": 0.25091920898340453,
  "weighted_f1": 0.20142694015981916,
  "balanced_accuracy": 0.21108497081511987
}

================================================================================
[tsai] real_to_real | fused
================================================================================
Reusing saved tsai Real->Real metrics.

================================================================================
[tsai] real_to_synthetic | fused
================================================================================
Copied external tsai model into current output folder: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_to_real_fused.pth
Loading tsai Real->Real model: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_to_real_fused.pth

Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_fused_predictions.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_fused_confusion_matrix.csv
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_fused_confusion_matrix_counts.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_fused_confusion_matrix_normalized.png
Saved: /home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_real_to_synthetic_fused_per_activity_metrics.csv
{
  "framework": "tsai",
  "model": "InceptionTimePlus",
  "experiment": "real_to_synthetic",
  "native_modality": "fused",
  "native_hz": 64,
  "channels": "ACC_x,ACC_y,ACC_z,BVP,EDA,TEMP",
  "description": "ACC+BVP+EDA+TEMP fused",
  "input_shape_train_native_N_T_C": [
    30762,
    512,
    6
  ],
  "input_shape_test_native_N_T_C": [
    9000,
    512,
    6
  ],
  "input_shape_train_framework_N_C_T": [
    30762,
    6,
    512
  ],
  "input_shape_test_framework_N_C_T": [
    9000,
    6,
    512
  ],
  "epochs": 0,
  "best_epoch_by_val_accuracy": 7,
  "best_val_accuracy": 0.7673770785331726,
  "saved_best_model_file": "/home/iailab42/khans1/projects/ir/results/downstream_extended_tsai_aeon/kovae/posterior_bank_v2/tsai_saved_models/best_InceptionTimePlus_real_to_real_fused.pth",
  "used_saved_real_to_real_model": true,
  "training_reused_from_experiment": "real_to_real",
  "batch_size": 1024,
  "lr": 0.001,
  "accuracy": 0.8266666666666667,
  "macro_precision": 0.8814758251070867,
  "macro_recall": 0.8362499187556844,
  "macro_f1": 0.8533965853104009,
  "weighted_precision": 0.8390122763841745,
  "weighted_recall": 0.8266666666666667,
  "weighted_f1": 0.8278951174364177,
  "balanced_accuracy": 0.8362499187556844
}

================================================================================
[tsai] synthetic_to_real | fused
================================================================================

<div><div><progress max="50" value="30"></progress> 60.00% [30/50 03:15&lt;02:10]</div><div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.469365</td><td>1.499293</td><td>0.681639</td><td>00:06</td></tr><tr><td>1</td><td>1.097378</td><td>0.894736</td><td>0.744590</td><td>00:06</td></tr><tr><td>2</td><td>0.856090</td><td>0.762600</td><td>0.744262</td><td>00:06</td></tr><tr><td>3</td><td>0.687649</td><td>0.656238</td><td>0.760000</td><td>00:06</td></tr><tr><td>4</td><td>0.567964</td><td>0.728294</td><td>0.732131</td><td>00:06</td></tr><tr><td>5</td><td>0.484262</td><td>0.704745</td><td>0.773443</td><td>00:06</td></tr><tr><td>6</td><td>0.424306</td><td>0.680822</td><td>0.747213</td><td>00:06</td></tr><tr><td>7</td><td>0.378036</td><td>0.725990</td><td>0.755410</td><td>00:06</td></tr><tr><td>8</td><td>0.346398</td><td>0.695414</td><td>0.755738</td><td>00:06</td></tr><tr><td>9</td><td>0.323037</td><td>0.630804</td><td>0.749672</td><td>00:06</td></tr><tr><td>10</td><td>0.301861</td><td>0.645142</td><td>0.758852</td><td>00:06</td></tr><tr><td>11</td><td>0.285588</td><td>0.821823</td><td>0.721311</td><td>00:06</td></tr><tr><td>12</td><td>0.264415</td><td>0.761519</td><td>0.725574</td><td>00:06</td></tr><tr><td>13</td><td>0.255036</td><td>0.926520</td><td>0.744426</td><td>00:06</td></tr><tr><td>14</td><td>0.240910</td><td>0.597581</td><td>0.768525</td><td>00:06</td></tr><tr><td>15</td><td>0.232178</td><td>0.725602</td><td>0.722295</td><td>00:06</td></tr><tr><td>16</td><td>0.221818</td><td>1.083848</td><td>0.720492</td><td>00:06</td></tr><tr><td>17</td><td>0.209874</td><td>0.772034</td><td>0.742295</td><td>00:06</td></tr><tr><td>18</td><td>0.198001</td><td>1.136147</td><td>0.743934</td><td>00:06</td></tr><tr><td>19</td><td>0.195619</td><td>0.873174</td><td>0.728852</td><td>00:06</td></tr><tr><td>20</td><td>0.183633</td><td>0.805366</td><td>0.770492</td><td>00:06</td></tr><tr><td>21</td><td>0.173961</td><td>0.832871</td><td>0.769836</td><td>00:06</td></tr><tr><td>22</td><td>0.166986</td><td>0.931580</td><td>0.737049</td><td>00:06</td></tr><tr><td>23</td><td>0.157293</td><td>0.815852</td><td>0.728033</td><td>00:06</td></tr><tr><td>24</td><td>0.151741</td><td>0.917921</td><td>0.735902</td><td>00:06</td></tr><tr><td>25</td><td>0.144512</td><td>0.849750</td><td>0.748852</td><td>00:06</td></tr><tr><td>26</td><td>0.135931</td><td>1.123443</td><td>0.720656</td><td>00:06</td></tr><tr><td>27</td><td>0.129981</td><td>0.758092</td><td>0.792459</td><td>00:06</td></tr><tr><td>28</td><td>0.126092</td><td>0.871379</td><td>0.755246</td><td>00:06</td></tr><tr><td>29</td><td>0.121763</td><td>1.142549</td><td>0.689180</td><td>00:06</td></tr></tbody></table></div><div><progress max="29" value="21"></progress> 72.41% [21/29 00:04&lt;00:01... 0.1193]</div></div>

Better model found at epoch 0 with accuracy value: 0.6816393733024597.
Better model found at epoch 1 with accuracy value: 0.744590163230896.
Better model found at epoch 3 with accuracy value: 0.7599999904632568.
Better model found at epoch 5 with accuracy value: 0.7734426259994507.
Better model found at epoch 27 with accuracy value: 0.7924590110778809.